# Trabajo Final CEIA
### Mg. Ing. Diego Martín Méndez
##### Universidad de Buenos Aires
##### Facultad de Ingeniería
##### Laboratorio de Sistemas Embebidos
##### Carrera de Especialización en Inteligencia Artificial

In [1]:
import requests
import pandas as pd
import numpy as np
import time
from dotenv import load_dotenv
import os
from datetime import datetime
from pathlib import Path

In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\mging\anaconda3\envs\env_python_310\lib\site-packages (20.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
fundamentals = pd.read_parquet("archivos/fundamentals.parquet")
fundamentals.head(20)

,symbol,date,fiscalYear,period,grossProfitMargin,ebitMargin,ebitdaMargin,operatingProfitMargin,pretaxProfitMargin,continuousOperationsProfitMargin,netProfitMargin,bottomLineProfitMargin,receivablesTurnover,payablesTurnover,inventoryTurnover,fixedAssetTurnover,assetTurnover,currentRatio,quickRatio,solvencyRatio,cashRatio,priceToEarningsRatio,priceToEarningsGrowthRatio,forwardPriceToEarningsGrowthRatio,priceToBookRatio,priceToSalesRatio,priceToFreeCashFlowRatio,priceToOperatingCashFlowRatio,debtToAssetsRatio,debtToEquityRatio,debtToCapitalRatio,longTermDebtToCapitalRatio,financialLeverageRatio,workingCapitalTurnoverRatio,operatingCashFlowRatio,operatingCashFlowSalesRatio,freeCashFlowOperatingCashFlowRatio,debtServiceCoverageRatio,interestCoverageRatio,shortTermOperatingCashFlowCoverageRatio,operatingCashFlowCoverageRatio,capitalExpenditureCoverageRatio,dividendPaidAndCapexCoverageRatio,dividendPayoutRatio,dividendYield,dividendYieldPercentage,revenuePerShare,netIncomePerShare,interestDebtPerShare,cashPerShare,bookValuePerShare,tangibleBookValuePerShare,shareholdersEquityPerShare,operatingCashFlowPerShare,capexPerShare,freeCashFlowPerShare,netIncomePerEBT,ebtPerEbit,priceToFairValue,debtToMarketCap,effectiveTaxRate,enterpriseValueMultiple,dividendPerShare,marketCap,enterpriseValue,evToSales,evToOperatingCashFlow,evToFreeCashFlow,evToEBITDA,netDebtToEBITDA,incomeQuality,grahamNumber,grahamNetNet,taxBurden,interestBurden,workingCapital,investedCapital,returnOnAssets,operatingReturnOnAssets,returnOnTangibleAssets,returnOnEquity,returnOnInvestedCapital,returnOnCapitalEmployed,earningsYield,freeCashFlowYield,capexToOperatingCashFlow,capexToDepreciation,capexToRevenue,salesGeneralAndAdministrativeToRevenue,researchAndDevelopementToRevenue,stockBasedCompensationToRevenue,intangiblesToTotalAssets,averageReceivables,averagePayables,averageInventory,daysOfSalesOutstanding,daysOfPayablesOutstanding,daysOfInventoryOutstanding,operatingCycle,cashConversionCycle,freeCashFlowToEquity,freeCashFlowToFirm,tangibleAssetValue,netCurrentAssetValue,stockPrice,numberOfShares,marketCapitalization,minusCashAndCashEquivalents,addTotalDebt,reportedCurrency,cashAndCashEquivalents,shortTermInvestments,cashAndShortTermInvestments,netReceivables,accountsReceivables,otherReceivables,inventory,prepaids,otherCurrentAssets,totalCurrentAssets,propertyPlantEquipmentNet,goodwill,intangibleAssets,goodwillAndIntangibleAssets,longTermInvestments,taxAssets,otherNonCurrentAssets,totalNonCurrentAssets,otherAssets,totalAssets,totalPayables,accountPayables,otherPayables,accruedExpenses,shortTermDebt,capitalLeaseObligationsCurrent,taxPayables,deferredRevenue,otherCurrentLiabilities,totalCurrentLiabilities,longTermDebt,capitalLeaseObligationsNonCurrent,deferredRevenueNonCurrent,deferredTaxLiabilitiesNonCurrent,otherNonCurrentLiabilities,totalNonCurrentLiabilities,otherLiabilities,capitalLeaseObligations,totalLiabilities,treasuryStock,preferredStock,commonStock,retainedEarnings,additionalPaidInCapital,accumulatedOtherComprehensiveIncomeLoss,otherTotalStockholdersEquity,totalStockholdersEquity,totalEquity,minorityInterest,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt,acceptedDate,revenue,costOfRevenue,grossProfit,researchAndDevelopmentExpenses,generalAndAdministrativeExpenses,sellingAndMarketingExpenses,sellingGeneralAndAdministrativeExpenses,otherExpenses,operatingExpenses,costAndExpenses,netInterestIncome,interestIncome,interestExpense,depreciationAndAmortization,ebitda,ebit,nonOperatingIncomeExcludingInterest,operatingIncome,totalOtherIncomeExpensesNet,incomeBeforeTax,incomeTaxExpense,netIncomeFromContinuingOperations,netIncomeFromDiscontinuedOperations,otherAdjustmentsToNetIncome,netIncome,netIncomeDeductions,bottomLineNetIncome,eps,epsDiluted,weightedAverageShsOut,weightedAverageShsOutDil,deferredIncomeTax,stockBasedCompensation,changeInWorkingCapital,accountsPayables,otherWorkingCapital,otherNonCashItems,netCashProvidedByOperatingActivities,investmentsInPropertyPlantAndEquipment,acquisitionsNet,purchasesOfInvestments,salesMaturitiesOfInvestments,otherInvestingActivities,netCashProvidedByInvestingActivities,netDebtIssuance,longTermNetDebtIssuance,shortTermNetDebtIssuance,netStockIssuance,netCommonStockIssuance,commonStockIssuance,commonStockRepurchased,netPreferredStockIssuance,netDividendsPaid,commonDividendsPaid,preferredDividendsPaid,otherFinancingActivities,netCashProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow,incomeTaxesPaid,interestPaid
0,HMY,2025-06-30,2025,Q4,0.400571,0.304421,0.370099,0.281703,0.295388,0.180084,0.177581,0.177581,9.184158,3.276621,5.760000,0.761462,0.474240,1.719890,1.411124,0.308406,1.057556,5.979035,-0.348547,-0.348547,3.236253,4.247059,28.838103,12.526131,0.028760,0.046211,0.044170,0.037783,1.606779,4.394429,1.005974,0.339056,0.434360,158.728814,0.000000,211.220339,5.590848,1.767910,1.464567,0.223686,0.009353,0.935294,58.138341,10.324281,3.525789,20.722906,76.735333,76.725843,76.297180,19.712148,11.149970,8.562178,0.601179,1.048580,3.236253,0.012511,0.390347,10.676222,2.309399,1.561006e+11,1.452286e+11,3.951262,11.653719,26.829605,10.676222,-0.799235,1.909300,133.129840,-17.361622,0.601179,0.970328,8.918000e+09,5.719300e+10,0.084216,0.141449,0.084223,0.135317,0.096854,0.159011,0.041813,0.034676,0.565640,2.920050,0.191783,0.021249,0.000000,0.009740,0.000077,3.952500e+09,6.208000e+09,3.673000e+09,9.799483,27.467320,15.625000,25.424483,-2.042837,1.628500e+10,1.078405e+09,4.850600e+10,-7.685000e+09,246.92,632198987.0,1.561006e+11,1.310100e+10,2.229000e+09,ZAR,1.310100e+10,0.0,1.310100e+10,4.002000e+09,4.002000e+09,0.0,3.825000e+09,0.000000e+00,3.780000e+08,2.130600e+10,4.826900e+10,0.0,6.000000e+06,6000000.0,1.970000e+08,0.000000e+00,7.725000e+09,5.619700e+10,0.0,7.750300e+10,6.724000e+09,6.724000e+09,0.000000e+00,0.000000e+00,5.900000e+07,0.0,0.0,0.000000e+00,5.605000e+09,1.238800e+10,1.894000e+09,276000000.0,0.000000e+00,0.000000e+00,1.443300e+10,1.660300e+10,0.000000e+00,276000000.0,2.899100e+10,0.0,0.0,3.293400e+10,1.458400e+10,0.000000e+00,7.170000e+08,0.000000e+00,4.823500e+10,4.851200e+10,277000000.0,7.750300e+10,1.970000e+08,2.229000e+09,-1.087200e+10,2025-08-28 10:30:09,3.675500e+10,2.203200e+10,1.472300e+10,0.00,781000000.0,385000000.0,1.166000e+09,3.203000e+09,4.369000e+09,2.640100e+10,487000000.0,4.870000e+08,0.0,2.414000e+09,1.360300e+10,1.118900e+10,-8.350000e+08,1.035400e+10,5.030000e+08,1.085700e+10,4.238000e+09,6.619000e+09,0.000000e+00,0.0,6.527000e+09,0.000000e+00,6.527000e+09,10.48,10.32,632198987.0,633000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HMY,2024-12-31,2025,Q2,0.392558,0.275545,0.340917,0.269325,0.278641,0.213484,0.211545,0.211545,9.516013,3.963633,6.407555,0.844056,0.539088,1.839063,1.460786,0.450070,1.009454,3.083338,0.015435,0.015435,2.114589,2.609062,18.015088,9.514301,0.029421,0.044233,0.042359,0.042359,1.503426,8.256308,1.094220,0.274225,0.528130,119.093023,0.000000,118.430233,5.024667,2.119226,1.885064,0.075983,0.006161,0.616079,59.419928,12.570000,3.242890,15.032165,73.663368,73.644170,73.314601,16.294444,7.688866,8.605578,0.759204,1.034590,2.114589,0.021805,0.233839,7.071091,0.955109,9.690316e+10,8.953416e+10,2.410656,8.790786,16.645130,7.071091,-0.581978,1.296296,143.997229,-14.027861,0.759204,1.011237,7.810000e+09,5.182500e+10,0.114041,0.154658,0.114061,0.171453,0.128430,0.167869,0.081081,0.055509,0.471870,1.979407,0.129399,0.023317,0.000000,0.009181,0.000174,3.076000e+09,5.660500e+09,3.562000e+09,9.457742,22.706440,14.045920,23.503662,0.797222,1.274800e+10,-1.160109e+09,4.603200e+10,-5.734000e+09,155.03,625059665.0,9.690316e+10,9.396000e+09,2.027000e+09,ZAR,9.396000e+09,0.0,9.396000e+09,3.903000e+09,3.903000e+09,0.0,3.521000e+09,0.000000e+00,2.980000e+08,1.711800e+10,4.400300e+10,0.0,1.200000e+07,12000000.0,1.400000e+08,1.650000e+08,7.458000e+09,5.177800e+10,0.0,6.889600e+10,5.692000e+09,5.692000e+09,0.000000e+00,0.000000e+00,8.600000e+07,0.0,0.0,0.000000e+00,3.530000e+09,9.308000e+09,2.027000e+09,0.0,0.000000e+00,3.169000e+09,8.348000e+09,1.354400e+10,0.000000e+00,0.0,2.285200e+10,0.0,0.0,3.293400e+10,9.498000e+09,0.000000e+00,3.394000e+09,0.000000e+00,4.582600e+10,4.604400e+10,218000000.0,6.889600e+10,1.400000e+08,2.027000e+09,-7.369000e+09,2024-12-31 00:00:00,3.714100e+10,2.256100e+10,1.458000e+10,0.00,866000000.0,530000000.0,1.396000e+09,3.181000e+09,4.577000e+09,2.713800e+10,319000000.0,3.190000e+08,0.0,2.428000e+09,1.266200e+10,1.023400e+10,-2.310000e+08,1.000300e+10,3.460000e+08,1.034900e+10,2.420000e+09,7.929000e+09,0.000000e+00,0.0,7.857000e+09,0.000000e+00,7.857000e+09,12.65,12.57,625059665.0,625000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HMY,2024-06-30,2024,Q4,0.259098,0.153010,0.227168,0.226329,0.142680,0.091498,0.089452,0.089452,13.257003,3.924320,6.131002,0.721075,0.493136,1.115131,0.765664,0.250013,0.455189,9.835938,-0.176089,-0.176089,2.573448,3.519362,25.437524,12.123604,0.037893,0.056188,0.053199,0.041942,1.482808,11.740500,0.839476,0.290290,0.476603,14.494475,19.116147,961.666667,3.777826,1.910596,1.450478,0.538808,0.013695,1.369487,47.128270,4.215700,4.179344,7.479825,64.727671,64.697638,64.451050,13.680871,7.160525,6.520346,0.626939,0.630409,2.573448,0.017097,0.358721,15.137722,2.271451,1.049298e+11,1.025278e+11,3.438799,11.846076,24.855221,15.137722,-0.354643,3.245219,78.188181,-17.847175,0.626939,0.932486,1.187000e+09,4.255400e+10,0.044112,0.112237,0.044126,0.065409,0.085828,0.134556,0.025417,0.039312,0.523397,2.048847,0.151937,0.020023,0.000000,0.000000,0.000314,2.768000e+09,5.395000e+09,3.408000e+09,6.788865,22.933907,14.679493,21.468358,-1.465549,6.527000e+09,3.311514e+09,4.093000e+10,-8.014000e+09,165.86,632635150.0,1.049298e+11,4.693000e+09,2.291000e+09,ZAR,4.693000e+09,39000000.0,4.732000e+09,2.249000e+09,1.428000e+09,821000000.0,3.603000e+09,3.550000e+08,5.580000e+08,1.149700e+10,4.134800e+10,0.0,1.900000e+07,19000000.0,2.530000e+08,1.400000e+08,7.203000e+09,4.896300e+10,0.0,6.046000e+10,8.580000e+09,5.629000e+09,2.951000e+09,1.084000e+09,9.000000e+06,260000000.0,366000000.0,8.500000e+07,2.920000e+08,1.031000e+10,1.785000e+09,246000000.0,0.000000e+00,2.951000e+09,7.170000e+09,1.215200e+10,-2.951000e+09,506000000.0,1.951100e+10,0.0,0.0,3.293400e+10,2.238000e+09,0.000000e+00,6.081000e+09,-4.790000e+08,4.077400e+10,4.094900e+10,175000000.0,6.046000e+10,2.920000e+08,2.291000e+09,-2.402000e+09,2024-10-31 12:23:52,2.981500e+10,2.209000e+10,7.725000e+09,0.00,597000000.0,0.0,5.970000e+08,3.800000e+08,9.770000e+08,2.306700e+10,102000000.0,4.550000e+08,353000000.0,2.211000e+09,6.773000e+09,4.562000e+09,2.186000e+09,6.748000e+09,-2.494000e+09,4.254000e+09,1.526000e+09,2.728000e+09,0.000000e+00,0.0,2.667000e+09,0.000000e+00,2.667000e+09,4.22,4.22,632635150.0,632635150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HMY,2023-12-31,2024,Q2,0.269864,0.231783,0.308896,0.156127,0.239545,0.190248,0.187555,0.187555,9.602677,4.516760,7.255213,0.742578,0.527950,1.615239,1.107335,0.421685,0.549636,2.937062,0.000000,0.000000,1.746030,2.203448,22.241646,9.942763,0.056234,0.084402,0.077833,0.077534,1.500916,11.069262,1.105754,0.221613,0.447034,17.929978,11.124153,499.642857,2.080607,1.808428,1.802505,0.002147,0.000183,0.018276,50.991922,9.563813,6.147011,6.006462,64.579968,64.537964,64.350565,11.300485,6.248788,5.051696,0.782965,1.534294,1.746030,0.048340,0.205793,7.121500,0.020535,6.954963e+10,6.943463e+10,2.199804,9.926323,22.204869,7.121500,-0.011795,1.181588,117.674665,-19.420436,0.782965,1.033488,3.892000e+09,4.642400e+10,0.099020,0.084221,0.099063,0.148620,0.073192,0.092181,0.085119,0.044961,0.552966,1.624528,0.122545,0.000604,0.000000,0.000023,0.000435,2.746500e+09,3.183000e+09,3.239000e+09,9.372386,19.925786,12.404873,21.777259,1.851473,3.242000e+09,2.295419e+09,3.994900e+10,-9.593000e+09,112.36,619000000.0,6.954963e+10,3.477000e+09,3.362000e+09,ZAR,3.477000e+09,241000000.0,3.718000e+09,3.287000e+09,3.287000e+09,0.0,3.213000e+09,-2.820000e+08,2.820000e+08,1.021800e+10,4.250600e+10,24578544.0,1.421456e+06,26000000.0,6.599000e+09,1.260000e+08,3.110000e+08,4.956800e+10,0.0,5.978600e+10,5.161000e+09,5.161000e+09,0.000000e+00,0.000000e+00,1.400000e+07,0.0,0.0,2.250000e+08,9.260000e+08,6.326000e+09,3.348000e+09,0.0,0.000000e+00,2.775000e+09,7.362000e+09,1.348500e+10,0.000000e+00,0.0,1.981100e+10,0.0,0.0,3.293400e+10,5.000000e+08,0.000000e+00,6.399000e+09,0.000000e+00,3.983300e+10,3.997500e+10,142000000.0,5.978600e+10,6.840000e+09,3.362000e+09,-1.150000e+08,2023-12-29 19:00:00,3.156400e+10,2.331100e+10,8.518000e+09,0.00,19052982.0,677947018.0,6.970000e+08,2.990000e+08,9.960000e+08,2.663600e+10,-89000000.0,3.540000e+08,443000000.0,2.434000e+09,9.750000e+09,7.316000e+09,-2.388000e+09,4.928000e+09,2.633000e+09,7.561000e+09,1.556000e+09,6.005000e+09,5.758173e+09,0.0,5.920000e+09,0.000000e+00,5.920000e+09,9.56,9.53,619000000.0,621000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HMY,2023-06-30,2023,Q4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.263725,0.788263,0.000000,0.417504,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.099493,0.163852,0.140784,0.138591,1.646863,0.000000,1.002330,0.000000,0.419730,0.000000,0.000000,0.000000,1.208604,1.723335,1.659354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,2.828000e+09,0.000000,0.410867,0.978885,0.000000,0.000000,2.308957,NaN,0.000000,0.000000,0.000000,1.811000e+09,4.335100e+10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.580270,2.398799,0.000000,0.000000,0.000000,0.000000,0.000577,2.269000e+09,2.896000e+09,3.004500e+09,0.000000,0.000000,0.000000,0.000000,0.000000,6.100000e+07,0.000000e+00,3.484700e+10,-1.368200e+10,78.99,617000000.0,4.873827e+10,2.867000e+09,5.695000e+09,ZAR,2.867000e+09,0.0,2.867000e+09,2.206000e+09,1.428000e+09,12000000.0,3.265000e+09,1.890000e+08,1.510000e+08,8.678000e+09,4.150700e+10,0.0,3.300000e+07,33000000.0,1.110000e+08,1.890000e+08,6.722000e+09,4.856200e+10,0.0,5.724000e+10,1.550000e+09,1.205000e+09,3.450000e+08,1.061000e+09,0.000000e+00,113000000.0,345000000.0,2.850000e+08,3.868000e+09,6.867000e+09,5.592000e+09,0.0,1.050000e+08,2.294000e+09,7.502000e+09,1.549300e+10,0.000000e+00,113000000.0,2.236000e+10,0.0,0.0,3.293400e+10,-4.955000e+09,0.000000e+00,6.778000e+09,0.000000e+00,3.475700e+10,3.488000e+10,123000000.0,5.724000e+10,1.110000e+08,5.695000e+09,2.828000e+09,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,HMY,2022-12-31,2023,Q2,0.131765,0.003986,0.083332,0.108366,0.102004,0.002386,0.080131,0.002358,9.841338,4.344016,7.261662,0.589550,0.430218,1.516481,0.971604,0.169806,0.435862,4.840083,0.000000,0.000000,1.123108,1.551357,-61.279951,11.616200,0.129440,0.217816,0.178858,0.178858,1.682754,8.964844,0.608618,0.133551,-0.189560,2.558838,6.021792,22.050360,0.443881,0.840647,0.839732,0.002160,0.000112,0.011157,37.196110,2.980551,11.860616,3.557536,51.525122,51.460292,51.379254,4.967585,5.909238,-0.941653,0.785562,0.941295,1.123108,0.197845,0.213584,21.079273,0.006438,3.560365e+10,4.031365e+10,1.756586,13.152904,-69.386664,21.079273,2.462773,1.666667,58.699370,-26.317666,0.785562,25.590767,2.601000e+09,4.156900e+10,0.034474,0.049664,0.034500,0.058011,0.040369,0.051481,0.051652,-0.016319,1.189560,2.002197,0.158867,0.000742,0.000000,0.000035,0.000750,1.217692e+09,2.926500e+09,2.781000e+09,9.145098,20.718157,12.393857,21.538955,0.820798,-5.291000e+09,-1.835060e+09,3.175100e+10,-1.391700e+10,57.70,617000000.0,3.560365e+10,2.195000e+09,6.905000e+09,ZAR,2.195000e+09,0.0,2.195000e+09,2.332000e+09,2.332000e+09,0.0,2.744000e+09,0.000000e+00,3.660000e+08,7.637000e+09,3.892800e+10,0.0,4.000000e+07,40000000.0,1.010000e+08,1.780000e+08,6.461000e+09,4.570800e+10,0.0,5.334500e+10,4.587000e+09,4.587000e+09,0.000000e+00,0.000000e+00,1.390000e+08,0.0,0.0,2.970000e+08,1.300000e+07,5.036000e+09,6.905000e+09,0.0,2.240000e+08,2.365000e+09,7.024000e+09,1.651800e+10,0.000000e+00,0.0,2.155400e+10,0.0,0.0,3.293400e+10,-7.935000e+09,0.000000e+00,6.702000e+09,0.000000e+00,3.170100e+10,3.179100e+10,90000000.0,5.334500e+10,1.010000e+08,6.905000e+09,4.710000e+09,2022-12-30 19:00:00,2.295000e+10,1.992600e+10,3.024000e+09,0.00,17036326.0,561963674.0,5.790000e+08,-4.200000e+07,5.370000e+08,2.046300e+10,-106000000.0,3.070000e+08,413000000.0,1.821000e+09,1.912478e+09,9.147830e+07,2.395522e+09,2.487000e+09,-2.417531e+09,2.341000e+09,5.000000e+08,5.475752e+07,1.784890e+09,0.0,1.839000e+09,1.784890e+09,5.411020e+07,2.98,2.97,617000000.0,620000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,HMY,2022-06-30,2022,Q4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.506332,0.939899,0.000000,0.492060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.077914,0.121409,0.108265,0.095728,1.558241,0.000000,0.651859,0.000000,0.061363,0.000000,0.000000,129.720000,0.889224,1.065375,1.062714,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.199000e+09,0.000000,0.369719,6.025126,0.000000,0.000000,-1.329643,NaN,0.000000,0.000000,0.000000,2.519000e+09,3.543900e+10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.938637,1.530417,0.000000,0.000000,0.000000,0.000000,0.001025,9.936921e+08,2.731500e+09,2.524000e+09,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000e+09,0.000000e+00,3.006900e+10,-9.197000e+09,50.90,616444438.0,3.137802e+10,2.448000e+09,3.647000e+09,ZAR,2.448000e+09,0.0,2.448000e+09,1.033843e+08,8.838427e+07,15000000.0,2.818000e+09,1.578616e+09,5.460000e+08,7.494000e+09,3.287200e+10,0.0,4.800000e+07,48000000.0,1.250000e+08,2.030000e+08,6.066000e+09,3.931400e+10,0.0,4.680800e+10,1.434000e+09,1.266000e+09,1.680000e+08,9.240000e+08,2.500000e+07,197000000.0,168000000.0,3.090000e+08,2.086000e+09,4.975000e+09,3.180000e+09,245000000.0,3.780000e+08,1.586000e+09,6.327000e+09,1.171600e+10,0.000000e+00,442000000.0,1.669100e+10,0.0,0.0,3.293400e+10,-9.639000e+09,0.000000e+00,6.744000e+09,0.000000e+00,3.003900e+10,3.011700e+10,78000000.0,4.680800e+10,1.250000e+08,3.647000e+09,1.199000e+09,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
fundamentals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651247 entries, 0 to 651246
Columns: 230 entries, symbol to interestPaid
dtypes: datetime64[ns](1), float64(224), int64(1), object(4)
memory usage: 1.1+ GB

In [6]:
def revisar_nulos(df):
    
    pd.set_option('display.max_rows', None)

    result = []

    for col in df.columns:

        nan_count = df[col].isna().sum()
        none_count = (df[col] == None).sum()
        null_string_count = (df[col] == "Null").sum()
        empty_string_count = (df[col] == "").sum()
        zero_count = (df[col] == 0).sum()
        dtype = df[col].dtype

        result.append({
            "column": col,
            "dtype": dtype,
            "NaN": nan_count,
            "None": none_count,
            "Null_string": null_string_count,
            "Empty_string": empty_string_count,
            "Zero": zero_count
        })

    return pd.DataFrame(result)

In [7]:
revisar_nulos(fundamentals)

,column,dtype,NaN,None,Null_string,Empty_string,Zero
0,symbol,object,0,0,0,0,0
1,date,datetime64[ns],0,0,0,0,0
2,fiscalYear,int64,0,0,0,0,0
3,period,object,0,0,0,0,0
4,grossProfitMargin,float64,0,0,0,0,77509
5,ebitMargin,float64,0,0,0,0,111790
6,ebitdaMargin,float64,0,0,0,0,85158
7,operatingProfitMargin,float64,0,0,0,0,74563
8,pretaxProfitMargin,float64,0,0,0,0,104519
9,continuousOperationsProfitMargin,float64,0,0,0,0,77515
10,netProfitMargin,float64,0,0,0,0,75259
11,bottomLineProfitMargin,float64,0,0,0,0,75904
12,receivablesTurnover,float64,0,0,0,0,154449
13,payablesTurnover,float64,0,0,0,0,231383
14,inventoryTurnover,float64,0,0,0,0,351401
15,fixedAssetTurnover,float64,0,0,0,0,160478
16,assetTurnover,float64,0,0,0,0,101300
17,currentRatio,float64,0,0,0,0,67196
18,quickRatio,float64,0,0,0,0,67232
19,solvencyRatio,float64,0,0,0,0,51830
20,cashRatio,float64,0,0,0,0,74639
21,priceToEarningsRatio,float64,0,0,0,0,29970
22,priceToEarningsGrowthRatio,float64,0,0,0,0,72945
23,forwardPriceToEarningsGrowthRatio,float64,0,0,0,0,72945
24,priceToBookRatio,float64,0,0,0,0,59362
25,priceToSalesRatio,float64,0,0,0,0,83002
26,priceToFreeCashFlowRatio,float64,0,0,0,0,75104
27,priceToOperatingCashFlowRatio,float64,0,0,0,0,75000
28,debtToAssetsRatio,float64,0,0,0,0,133910
29,debtToEquityRatio,float64,0,0,0,0,133741
30,debtToCapitalRatio,float64,0,0,0,0,133301
31,longTermDebtToCapitalRatio,float64,0,0,0,0,207304
32,financialLeverageRatio,float64,0,0,0,0,39936
33,workingCapitalTurnoverRatio,float64,0,0,0,0,121596
34,operatingCashFlowRatio,float64,0,0,0,0,96099
35,operatingCashFlowSalesRatio,float64,0,0,0,0,115810
36,freeCashFlowOperatingCashFlowRatio,float64,0,0,0,0,61985
37,debtServiceCoverageRatio,float64,0,0,0,0,162436
38,interestCoverageRatio,float64,0,0,0,0,256398
39,shortTermOperatingCashFlowCoverageRatio,float64,0,0,0,0,293011
40,operatingCashFlowCoverageRatio,float64,0,0,0,0,156334
41,capitalExpenditureCoverageRatio,float64,0,0,0,0,167248
42,dividendPaidAndCapexCoverageRatio,float64,0,0,0,0,118877
43,dividendPayoutRatio,float64,0,0,0,0,349411
44,dividendYield,float64,0,0,0,0,353342
45,dividendYieldPercentage,float64,0,0,0,0,353342
46,revenuePerShare,float64,0,0,0,0,82979
47,netIncomePerShare,float64,0,0,0,0,29946
48,interestDebtPerShare,float64,0,0,0,0,120584
49,cashPerShare,float64,0,0,0,0,71723
50,bookValuePerShare,float64,0,0,0,0,61045
51,tangibleBookValuePerShare,float64,0,0,0,0,60572
52,shareholdersEquityPerShare,float64,0,0,0,0,59341
53,operatingCashFlowPerShare,float64,0,0,0,0,74978
54,capexPerShare,float64,0,0,0,0,174700
55,freeCashFlowPerShare,float64,0,0,0,0,75082
56,netIncomePerEBT,float64,0,0,0,0,51380
57,ebtPerEbit,float64,0,0,0,0,53478
58,priceToFairValue,float64,0,0,0,0,59362
59,debtToMarketCap,float64,0,0,0,0,166793
60,effectiveTaxRate,float64,0,0,0,0,155374
61,enterpriseValueMultiple,float64,0,0,0,0,70766
62,dividendPerShare,float64,0,0,0,0,353341
63,marketCap,float64,306,0,0,0,23654
64,enterpriseValue,float64,306,0,0,0,45130
65,evToSales,float64,306,0,0,0,107182
66,evToOperatingCashFlow,float64,306,0,0,0,79172
67,evToFreeCashFlow,float64,306,0,0,0,79283
68,evToEBITDA,float64,306,0,0,0,70754
69,netDebtToEBITDA,float64,306,0,0,0,67181
70,incomeQuality,float64,306,0,0,0,65952
71,grahamNumber,float64,237031,0,0,0,32953
72,grahamNetNet,float64,306,0,0,0,59125
73,taxBurden,float64,306,0,0,0,51366
74,interestBurden,float64,306,0,0,0,93434
75,workingCapital,float64,306,0,0,0,44544
76,investedCapital,float64,306,0,0,0,38910
77,returnOnAssets,float64,306,0,0,0,51497
78,operatingReturnOnAssets,float64,306,0,0,0,71846
79,returnOnTangibleAssets,float64,306,0,0,0,51413
80,returnOnEquity,float64,306,0,0,0,49255
81,returnOnInvestedCapital,float64,306,0,0,0,72549
82,returnOnCapitalEmployed,float64,306,0,0,0,52690
83,earningsYield,float64,306,0,0,0,29943
84,freeCashFlowYield,float64,306,0,0,0,75082
85,capexToOperatingCashFlow,float64,306,0,0,0,167226
86,capexToDepreciation,float64,306,0,0,0,192369
87,capexToRevenue,float64,306,0,0,0,186989
88,salesGeneralAndAdministrativeToRevenue,float64,306,0,0,0,291312
89,researchAndDevelopementToRevenue,float64,306,0,0,0,496506
90,stockBasedCompensationToRevenue,float64,306,0,0,0,377138
91,intangiblesToTotalAssets,float64,306,0,0,0,260094
92,averageReceivables,float64,306,0,0,0,139547
93,averagePayables,float64,306,0,0,0,158424
94,averageInventory,float64,306,0,0,0,333806
95,daysOfSalesOutstanding,float64,306,0,0,0,154424
96,daysOfPayablesOutstanding,float64,306,0,0,0,231336
97,daysOfInventoryOutstanding,float64,306,0,0,0,351267
98,operatingCycle,float64,306,0,0,0,146589
99,cashConversionCycle,float64,306,0,0,0,131595
100,freeCashFlowToEquity,float64,306,0,0,0,59930
101,freeCashFlowToFirm,float64,306,0,0,0,92358
102,tangibleAssetValue,float64,306,0,0,0,38248
103,netCurrentAssetValue,float64,306,0,0,0,36856
104,stockPrice,float64,14,0,0,0,11
105,numberOfShares,float64,10327,0,0,0,6697
106,marketCapitalization,float64,10341,0,0,0,6707
107,minusCashAndCashEquivalents,float64,0,0,0,0,53636
108,addTotalDebt,float64,0,0,0,0,133256
109,reportedCurrency,object,37225,0,0,0,0
110,cashAndCashEquivalents,float64,37226,0,0,0,17636
111,shortTermInvestments,float64,37226,0,0,0,426537
112,cashAndShortTermInvestments,float64,37226,0,0,0,15553
113,netReceivables,float64,37226,0,0,0,99159
114,accountsReceivables,float64,37424,0,0,0,227009
115,otherReceivables,float64,37228,0,0,0,389209
116,inventory,float64,37226,0,0,0,299027
117,prepaids,float64,37227,0,0,0,389462
118,otherCurrentAssets,float64,37225,0,0,0,199207
119,totalCurrentAssets,float64,37226,0,0,0,13459
120,propertyPlantEquipmentNet,float64,37226,0,0,0,97939
121,goodwill,float64,37227,0,0,0,360834
122,intangibleAssets,float64,37227,0,0,0,270940
123,goodwillAndIntangibleAssets,float64,37227,0,0,0,223840
124,longTermInvestments,float64,37227,0,0,0,312420
125,taxAssets,float64,37227,0,0,0,433612
126,otherNonCurrentAssets,float64,37225,0,0,0,67725
127,totalNonCurrentAssets,float64,37226,0,0,0,19145
128,otherAssets,float64,37225,0,0,0,550011
129,totalAssets,float64,37226,0,0,0,3165
130,totalPayables,float64,37228,0,0,0,109057
131,accountPayables,float64,37226,0,0,0,121106
132,otherPayables,float64,37230,0,0,0,452706
133,accruedExpenses,float64,37226,0,0,0,339503
134,shortTermDebt,float64,37227,0,0,0,239702
135,capitalLeaseObligationsCurrent,float64,37227,0,0,0,520266
136,taxPayables,float64,37227,0,0,0,460070
137,deferredRevenue,float64,37226,0,0,0,397600
138,otherCurrentLiabilities,float64,37225,0,0,0,135696
139,totalCurrentLiabilities,float64,37226,0,0,0,26001
140,longTermDebt,float64,37226,0,0,0,171167
141,capitalLeaseObligationsNonCurrent,float64,37226,0,0,0,476454
142,deferredRevenueNonCurrent,float64,37226,0,0,0,514994
143,deferredTaxLiabilitiesNonCurrent,float64,37230,0,0,0,395426
144,otherNonCurrentLiabilities,float64,37228,0,0,0,142825
145,totalNonCurrentLiabilities,float64,37226,0,0,0,55633
146,otherLiabilities,float64,37225,0,0,0,531556
147,capitalLeaseObligations,float64,37225,0,0,0,467757
148,totalLiabilities,float64,37226,0,0,0,3540
149,treasuryStock,float64,41089,0,0,0,451082
150,preferredStock,float64,37225,0,0,0,507399
151,commonStock,float64,37226,0,0,0,97535
152,retainedEarnings,float64,37226,0,0,0,29674
153,additionalPaidInCapital,float64,37226,0,0,0,245702
154,accumulatedOtherComprehensiveIncomeLoss,float64,37229,0,0,0,166386
155,otherTotalStockholdersEquity,float64,37228,0,0,0,375191
156,totalStockholdersEquity,float64,37226,0,0,0,988
157,totalEquity,float64,37226,0,0,0,8056
158,minorityInterest,float64,37225,0,0,0,452117
159,totalLiabilitiesAndTotalEquity,float64,37229,0,0,0,14547
160,totalInvestments,float64,37228,0,0,0,242757
161,totalDebt,float64,37225,0,0,0,97139
162,netDebt,float64,37225,0,0,0,6269
163,acceptedDate,object,12890,0,0,0,0
164,revenue,float64,12879,0,0,0,59946
165,costOfRevenue,float64,12876,0,0,0,138160
166,grossProfit,float64,12876,0,0,0,55028
167,researchAndDevelopmentExpenses,float64,12886,0,0,0,461903
168,generalAndAdministrativeExpenses,float64,12888,0,0,0,240246
169,sellingAndMarketingExpenses,float64,12889,0,0,0,462435
170,sellingGeneralAndAdministrativeExpenses,float64,12877,0,0,0,63754
171,otherExpenses,float64,12876,0,0,0,259777
172,operatingExpenses,float64,12877,0,0,0,21097
173,costAndExpenses,float64,12876,0,0,0,20786
174,netInterestIncome,float64,12876,0,0,0,212300
175,interestIncome,float64,13372,0,0,0,351614
176,interestExpense,float64,13466,0,0,0,241835
177,depreciationAndAmortization,float64,12876,0,0,0,68664
178,ebitda,float64,12876,0,0,0,21042
179,ebit,float64,12879,0,0,0,53083
180,nonOperatingIncomeExcludingInterest,float64,12881,0,0,0,335907
181,operatingIncome,float64,12876,0,0,0,8349
182,totalOtherIncomeExpensesNet,float64,12877,0,0,0,116549
183,incomeBeforeTax,float64,12877,0,0,0,40189
184,incomeTaxExpense,float64,12880,0,0,0,127756
185,netIncomeFromContinuingOperations,float64,14459,0,0,0,7838
186,netIncomeFromDiscontinuedOperations,float64,12888,0,0,0,593786
187,otherAdjustmentsToNetIncome,float64,17823,0,0,0,600185
188,netIncome,float64,12876,0,0,0,6418
189,netIncomeDeductions,float64,17855,0,0,0,604083
190,bottomLineNetIncome,float64,13002,0,0,0,7053
191,eps,float64,12913,0,0,0,7939
192,epsDiluted,float64,12917,0,0,0,7991
193,weightedAverageShsOut,float64,20978,0,0,0,5045
194,weightedAverageShsOutDil,float64,20978,0,0,0,4917
195,deferredIncomeTax,float64,651238,0,0,0,8
196,stockBasedCompensation,float64,651238,0,0,0,8
197,changeInWorkingCapital,float64,651238,0,0,0,0
198,accountsPayables,float64,651238,0,0,0,5
199,otherWorkingCapital,float64,651238,0,0,0,3
200,otherNonCashItems,float64,651238,0,0,0,0
201,netCashProvidedByOperatingActivities,float64,651238,0,0,0,1
202,investmentsInPropertyPlantAndEquipment,float64,651238,0,0,0,8
203,acquisitionsNet,float64,651238,0,0,0,9
204,purchasesOfInvestments,float64,651238,0,0,0,5
205,salesMaturitiesOfInvestments,float64,651238,0,0,0,5
206,otherInvestingActivities,float64,651238,0,0,0,8
207,netCashProvidedByInvestingActivities,float64,651238,0,0,0,5
208,netDebtIssuance,float64,651238,0,0,0,5
209,longTermNetDebtIssuance,float64,651238,0,0,0,7
210,shortTermNetDebtIssuance,float64,651238,0,0,0,6
211,netStockIssuance,float64,651238,0,0,0,7
212,netCommonStockIssuance,float64,651238,0,0,0,7
213,commonStockIssuance,float64,651238,0,0,0,8
214,commonStockRepurchased,float64,651238,0,0,0,7
215,netPreferredStockIssuance,float64,651238,0,0,0,9
216,netDividendsPaid,float64,651238,0,0,0,6
217,commonDividendsPaid,float64,651238,0,0,0,6
218,preferredDividendsPaid,float64,651238,0,0,0,9
219,otherFinancingActivities,float64,651238,0,0,0,3
220,netCashProvidedByFinancingActivities,float64,651238,0,0,0,4
221,effectOfForexChangesOnCash,float64,651238,0,0,0,7
222,netChangeInCash,float64,651238,0,0,0,2
223,cashAtEndOfPeriod,float64,651238,0,0,0,3
224,cashAtBeginningOfPeriod,float64,651238,0,0,0,5
225,operatingCashFlow,float64,651238,0,0,0,0
226,capitalExpenditure,float64,651238,0,0,0,7
227,freeCashFlow,float64,651238,0,0,0,0
228,incomeTaxesPaid,float64,651238,0,0,0,9
229,interestPaid,float64,651238,0,0,0,5

In [8]:
# fundamentals_recortado = fundamentals.head(1000)

In [9]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\mging\anaconda3\envs\env_python_310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\mging\anaconda3\envs\env_python_310\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
# fundamentals_recortado.to_excel("archivos/fundamentals_recortado.xlsx", index=False)

In [11]:
# Columnas que ya vienen como ratios y/o medidas relativas de origen (ratios, márgenes, yields, returns, turnovers, coberturas, múltiplos. las dejo tal cual vienen.

original_ratio_cols = [
    "grossProfitMargin",
    "ebitMargin",
    "ebitdaMargin",
    "operatingProfitMargin",
    "pretaxProfitMargin",
    "continuousOperationsProfitMargin",
    "netProfitMargin",
    "bottomLineProfitMargin",
    "receivablesTurnover",
    "payablesTurnover",
    "inventoryTurnover",
    "fixedAssetTurnover",
    "assetTurnover",
    "currentRatio",
    "quickRatio",
    "solvencyRatio",
    "cashRatio",
    "priceToEarningsRatio",
    "priceToEarningsGrowthRatio",
    "forwardPriceToEarningsGrowthRatio",
    "priceToBookRatio",
    "priceToSalesRatio",
    "priceToFreeCashFlowRatio",
    "priceToOperatingCashFlowRatio",
    "debtToAssetsRatio",
    "debtToEquityRatio",
    "debtToCapitalRatio",
    "longTermDebtToCapitalRatio",
    "financialLeverageRatio",
    "workingCapitalTurnoverRatio",
    "operatingCashFlowRatio",
    "operatingCashFlowSalesRatio",
    "freeCashFlowOperatingCashFlowRatio",
    "debtServiceCoverageRatio",
    "interestCoverageRatio",
    "shortTermOperatingCashFlowCoverageRatio",
    "operatingCashFlowCoverageRatio",
    "capitalExpenditureCoverageRatio",
    "dividendPaidAndCapexCoverageRatio",
    "dividendPayoutRatio",
    "dividendYield",
    "dividendYieldPercentage",
    "netIncomePerEBT",
    "ebtPerEbit",
    "priceToFairValue",
    "debtToMarketCap",
    "evToSales",
    "evToOperatingCashFlow",
    "evToFreeCashFlow",
    "evToEBITDA",
    "netDebtToEBITDA",
    "incomeQuality",
    "taxBurden",
    "interestBurden",
    "returnOnAssets",
    "operatingReturnOnAssets",
    "returnOnTangibleAssets",
    "returnOnEquity",
    "returnOnInvestedCapital",
    "returnOnCapitalEmployed",
    "earningsYield",
    "freeCashFlowYield",
    "capexToOperatingCashFlow",
    "capexToDepreciation",
    "capexToRevenue",
    "salesGeneralAndAdministrativeToRevenue",
    "researchAndDevelopementToRevenue",
    "stockBasedCompensationToRevenue",
    "intangiblesToTotalAssets",
    "freeCashFlowToEquity",
    "freeCashFlowToFirm",
]

# dejo solo las que efectivamente existan en el dataframe
original_ratio_cols = [c for c in original_ratio_cols if c in fundamentals.columns]



# Otras columnas relativas de origen que no son ratios.

original_relative_cols = [
    "revenuePerShare",
    "netIncomePerShare",
    "interestDebtPerShare",
    "cashPerShare",
    "bookValuePerShare",
    "tangibleBookValuePerShare",
    "shareholdersEquityPerShare",
    "operatingCashFlowPerShare",
    "capexPerShare",
    "freeCashFlowPerShare",
    "daysOfSalesOutstanding",
    "daysOfPayablesOutstanding",
    "daysOfInventoryOutstanding",
    "operatingCycle",
    "cashConversionCycle",
    "enterpriseValueMultiple",
]

original_relative_cols = [c for c in original_relative_cols if c in fundamentals.columns]

In [12]:
len(original_ratio_cols)

71

In [13]:
len(original_relative_cols)

16

In [14]:
# Funciones auxiliares:

def dividir(num, den):
    """
    División segura:
    - convierte 0 en NaN en el denominador
    - reemplaza inf/-inf por NaN
    """
    den = den.replace(0, np.nan)
    out = num / den
    return out.replace([np.inf, -np.inf], np.nan)

def add_ratio(df, new_col, num_col, den_col, abs_num=False, abs_den=False):
    """
    Crea ratio solo si existen ambas columnas.
    """
    if num_col in df.columns and den_col in df.columns:
        num = df[num_col].abs() if abs_num else df[num_col]
        den = df[den_col].abs() if abs_den else df[den_col]
        df[new_col] = dividir(num, den)

In [15]:
# Creación de ratios:

df_ratios = fundamentals.copy()


# Ratios de márgenes y rentabilidad sobre ventas:

add_ratio(df_ratios, "c_grossProfit_to_revenue", "grossProfit", "revenue")
add_ratio(df_ratios, "c_ebitda_to_revenue", "ebitda", "revenue")
add_ratio(df_ratios, "c_ebit_to_revenue", "ebit", "revenue")
add_ratio(df_ratios, "c_operatingIncome_to_revenue", "operatingIncome", "revenue")
add_ratio(df_ratios, "c_incomeBeforeTax_to_revenue", "incomeBeforeTax", "revenue")
add_ratio(df_ratios, "c_netIncome_to_revenue", "netIncome", "revenue")
add_ratio(df_ratios, "c_bottomLineNetIncome_to_revenue", "bottomLineNetIncome", "revenue")
add_ratio(df_ratios, "c_netIncomeFromContinuingOperations_to_revenue", "netIncomeFromContinuingOperations", "revenue")
add_ratio(df_ratios, "c_costOfRevenue_to_revenue", "costOfRevenue", "revenue")
add_ratio(df_ratios, "c_operatingExpenses_to_revenue", "operatingExpenses", "revenue")
add_ratio(df_ratios, "c_costAndExpenses_to_revenue", "costAndExpenses", "revenue")
add_ratio(df_ratios, "c_researchAndDevelopmentExpenses_to_revenue", "researchAndDevelopmentExpenses", "revenue")
add_ratio(df_ratios, "c_generalAndAdministrativeExpenses_to_revenue", "generalAndAdministrativeExpenses", "revenue")
add_ratio(df_ratios, "c_sellingAndMarketingExpenses_to_revenue", "sellingAndMarketingExpenses", "revenue")
add_ratio(df_ratios, "c_sellingGeneralAndAdministrativeExpenses_to_revenue", "sellingGeneralAndAdministrativeExpenses", "revenue")
add_ratio(df_ratios, "c_depreciationAndAmortization_to_revenue", "depreciationAndAmortization", "revenue")
add_ratio(df_ratios, "c_interestExpense_to_revenue", "interestExpense", "revenue")
add_ratio(df_ratios, "c_incomeTaxExpense_to_revenue", "incomeTaxExpense", "revenue")
add_ratio(df_ratios, "c_stockBasedCompensation_to_revenue", "stockBasedCompensation", "revenue")
add_ratio(df_ratios, "c_otherExpenses_to_revenue", "otherExpenses", "revenue")
add_ratio(df_ratios, "c_nonOperatingIncomeExcludingInterest_to_revenue", "nonOperatingIncomeExcludingInterest", "revenue")
add_ratio(df_ratios, "c_totalOtherIncomeExpensesNet_to_revenue", "totalOtherIncomeExpensesNet", "revenue")


# Ratios sobre retornos sobre activos, equity y capital:

add_ratio(df_ratios, "c_revenue_to_totalAssets", "revenue", "totalAssets")
add_ratio(df_ratios, "c_grossProfit_to_totalAssets", "grossProfit", "totalAssets")
add_ratio(df_ratios, "c_ebitda_to_totalAssets", "ebitda", "totalAssets")
add_ratio(df_ratios, "c_ebit_to_totalAssets", "ebit", "totalAssets")
add_ratio(df_ratios, "c_operatingIncome_to_totalAssets", "operatingIncome", "totalAssets")
add_ratio(df_ratios, "c_netIncome_to_totalAssets", "netIncome", "totalAssets")
add_ratio(df_ratios, "c_operatingCashFlow_to_totalAssets", "operatingCashFlow", "totalAssets")
add_ratio(df_ratios, "c_freeCashFlow_to_totalAssets", "freeCashFlow", "totalAssets")

add_ratio(df_ratios, "c_netIncome_to_totalEquity", "netIncome", "totalEquity")
add_ratio(df_ratios, "c_operatingIncome_to_totalEquity", "operatingIncome", "totalEquity")
add_ratio(df_ratios, "c_totalDebt_to_totalEquity", "totalDebt", "totalEquity")
add_ratio(df_ratios, "c_totalLiabilities_to_totalEquity", "totalLiabilities", "totalEquity")
add_ratio(df_ratios, "c_netDebt_to_totalEquity", "netDebt", "totalEquity")

add_ratio(df_ratios, "c_netIncome_to_investedCapital", "netIncome", "investedCapital")
add_ratio(df_ratios, "c_operatingIncome_to_investedCapital", "operatingIncome", "investedCapital")
add_ratio(df_ratios, "c_ebit_to_investedCapital", "ebit", "investedCapital")

add_ratio(df_ratios, "c_netIncome_to_tangibleAssetValue", "netIncome", "tangibleAssetValue")
add_ratio(df_ratios, "c_operatingIncome_to_tangibleAssetValue", "operatingIncome", "tangibleAssetValue")


# Ratios sobre estructura de capital, apalancamiento y solvencia:

add_ratio(df_ratios, "c_totalDebt_to_totalAssets", "totalDebt", "totalAssets")
add_ratio(df_ratios, "c_totalLiabilities_to_totalAssets", "totalLiabilities", "totalAssets")
add_ratio(df_ratios, "c_netDebt_to_totalAssets", "netDebt", "totalAssets")
add_ratio(df_ratios, "c_longTermDebt_to_totalAssets", "longTermDebt", "totalAssets")
add_ratio(df_ratios, "c_shortTermDebt_to_totalAssets", "shortTermDebt", "totalAssets")

add_ratio(df_ratios, "c_longTermDebt_to_totalDebt", "longTermDebt", "totalDebt")
add_ratio(df_ratios, "c_shortTermDebt_to_totalDebt", "shortTermDebt", "totalDebt")

add_ratio(df_ratios, "c_totalDebt_to_capital", "totalDebt", "investedCapital")
add_ratio(df_ratios, "c_longTermDebt_to_capital", "longTermDebt", "investedCapital")

add_ratio(df_ratios, "c_cashAndCashEquivalents_to_totalDebt", "cashAndCashEquivalents", "totalDebt")
add_ratio(df_ratios, "c_cashAndShortTermInvestments_to_totalDebt", "cashAndShortTermInvestments", "totalDebt")
add_ratio(df_ratios, "c_cashAndCashEquivalents_to_totalAssets", "cashAndCashEquivalents", "totalAssets")
add_ratio(df_ratios, "c_cashAndShortTermInvestments_to_totalAssets", "cashAndShortTermInvestments", "totalAssets")

add_ratio(df_ratios, "c_workingCapital_to_totalAssets", "workingCapital", "totalAssets")
add_ratio(df_ratios, "c_workingCapital_to_revenue", "workingCapital", "revenue")
add_ratio(df_ratios, "c_investedCapital_to_totalAssets", "investedCapital", "totalAssets")


# Ratios sobre liquidez y composición del balance:

add_ratio(df_ratios, "c_totalCurrentAssets_to_totalCurrentLiabilities", "totalCurrentAssets", "totalCurrentLiabilities")
add_ratio(df_ratios, "c_cashAndCashEquivalents_to_totalCurrentLiabilities", "cashAndCashEquivalents", "totalCurrentLiabilities")
add_ratio(df_ratios, "c_cashAndShortTermInvestments_to_totalCurrentLiabilities", "cashAndShortTermInvestments", "totalCurrentLiabilities")
add_ratio(df_ratios, "c_netReceivables_to_totalCurrentLiabilities", "netReceivables", "totalCurrentLiabilities")
add_ratio(df_ratios, "c_inventory_to_totalCurrentAssets", "inventory", "totalCurrentAssets")
add_ratio(df_ratios, "c_netReceivables_to_totalCurrentAssets", "netReceivables", "totalCurrentAssets")
add_ratio(df_ratios, "c_otherCurrentAssets_to_totalCurrentAssets", "otherCurrentAssets", "totalCurrentAssets")
add_ratio(df_ratios, "c_prepaids_to_totalCurrentAssets", "prepaids", "totalCurrentAssets")

add_ratio(df_ratios, "c_totalCurrentAssets_to_totalAssets", "totalCurrentAssets", "totalAssets")
add_ratio(df_ratios, "c_totalNonCurrentAssets_to_totalAssets", "totalNonCurrentAssets", "totalAssets")
add_ratio(df_ratios, "c_propertyPlantEquipmentNet_to_totalAssets", "propertyPlantEquipmentNet", "totalAssets")
add_ratio(df_ratios, "c_inventory_to_totalAssets", "inventory", "totalAssets")
add_ratio(df_ratios, "c_netReceivables_to_totalAssets", "netReceivables", "totalAssets")
add_ratio(df_ratios, "c_goodwill_to_totalAssets", "goodwill", "totalAssets")
add_ratio(df_ratios, "c_intangibleAssets_to_totalAssets", "intangibleAssets", "totalAssets")
add_ratio(df_ratios, "c_goodwillAndIntangibleAssets_to_totalAssets", "goodwillAndIntangibleAssets", "totalAssets")
add_ratio(df_ratios, "c_longTermInvestments_to_totalAssets", "longTermInvestments", "totalAssets")
add_ratio(df_ratios, "c_totalInvestments_to_totalAssets", "totalInvestments", "totalAssets")

add_ratio(df_ratios, "c_totalCurrentLiabilities_to_totalLiabilities", "totalCurrentLiabilities", "totalLiabilities")
add_ratio(df_ratios, "c_totalNonCurrentLiabilities_to_totalLiabilities", "totalNonCurrentLiabilities", "totalLiabilities")
add_ratio(df_ratios, "c_accountPayables_to_totalLiabilities", "accountPayables", "totalLiabilities")
add_ratio(df_ratios, "c_totalPayables_to_totalLiabilities", "totalPayables", "totalLiabilities")
add_ratio(df_ratios, "c_shortTermDebt_to_totalLiabilities", "shortTermDebt", "totalLiabilities")
add_ratio(df_ratios, "c_longTermDebt_to_totalLiabilities", "longTermDebt", "totalLiabilities")


# Ratios sobre eficiencia / rotación:

add_ratio(df_ratios, "c_revenue_to_averageReceivables", "revenue", "averageReceivables")
add_ratio(df_ratios, "c_costOfRevenue_to_averagePayables", "costOfRevenue", "averagePayables")
add_ratio(df_ratios, "c_costOfRevenue_to_averageInventory", "costOfRevenue", "averageInventory")
add_ratio(df_ratios, "c_revenue_to_propertyPlantEquipmentNet", "revenue", "propertyPlantEquipmentNet")
add_ratio(df_ratios, "c_revenue_to_workingCapital", "revenue", "workingCapital")


# Ratios sobre cash flow y coberturas:

add_ratio(df_ratios, "c_operatingCashFlow_to_revenue", "operatingCashFlow", "revenue")
add_ratio(df_ratios, "c_freeCashFlow_to_revenue", "freeCashFlow", "revenue")
add_ratio(df_ratios, "c_operatingCashFlow_to_totalDebt", "operatingCashFlow", "totalDebt")
add_ratio(df_ratios, "c_freeCashFlow_to_totalDebt", "freeCashFlow", "totalDebt")
add_ratio(df_ratios, "c_operatingCashFlow_to_totalCurrentLiabilities", "operatingCashFlow", "totalCurrentLiabilities")
add_ratio(df_ratios, "c_operatingCashFlow_to_netIncome", "operatingCashFlow", "netIncome")
add_ratio(df_ratios, "c_freeCashFlow_to_netIncome", "freeCashFlow", "netIncome")
add_ratio(df_ratios, "c_freeCashFlow_to_operatingCashFlow", "freeCashFlow", "operatingCashFlow")

# Cobertura de intereses. Uso valor absoluto(interestExpense) para evitar signos contables negativos.
add_ratio(df_ratios, "c_ebit_to_interestExpense", "ebit", "interestExpense", abs_den=True)
add_ratio(df_ratios, "c_operatingIncome_to_interestExpense", "operatingIncome", "interestExpense", abs_den=True)
add_ratio(df_ratios, "c_operatingCashFlow_to_interestExpense", "operatingCashFlow", "interestExpense", abs_den=True)

# Capex y dividendos. Normalmente vienen con signo negativo, así que tomo abs del numerador.
add_ratio(df_ratios, "c_capitalExpenditure_to_operatingCashFlow", "capitalExpenditure", "operatingCashFlow", abs_num=True)
add_ratio(df_ratios, "c_investmentsInPropertyPlantAndEquipment_to_operatingCashFlow", "investmentsInPropertyPlantAndEquipment", "operatingCashFlow", abs_num=True)
add_ratio(df_ratios, "c_netDividendsPaid_to_operatingCashFlow", "netDividendsPaid", "operatingCashFlow", abs_num=True)
add_ratio(df_ratios, "c_commonDividendsPaid_to_operatingCashFlow", "commonDividendsPaid", "operatingCashFlow", abs_num=True)

if {"netDividendsPaid", "capitalExpenditure", "operatingCashFlow"}.issubset(df_ratios.columns):
    df_ratios["c_dividendsPaid_plus_capex_to_operatingCashFlow"] = dividir(
        df_ratios["netDividendsPaid"].abs() + df_ratios["capitalExpenditure"].abs(),
        df_ratios["operatingCashFlow"]
    )


# Ratios sobre mpuestos y calidad de resultado:

add_ratio(df_ratios, "c_incomeTaxExpense_to_incomeBeforeTax", "incomeTaxExpense", "incomeBeforeTax")
add_ratio(df_ratios, "c_netIncome_to_incomeBeforeTax", "netIncome", "incomeBeforeTax")
add_ratio(df_ratios, "c_incomeBeforeTax_to_ebit", "incomeBeforeTax", "ebit")
add_ratio(df_ratios, "c_operatingCashFlow_to_netIncome_quality", "operatingCashFlow", "netIncome")


# Ratios sobre valuación y mercado:

add_ratio(df_ratios, "c_marketCap_to_revenue", "marketCap", "revenue")
add_ratio(df_ratios, "c_marketCap_to_operatingCashFlow", "marketCap", "operatingCashFlow")
add_ratio(df_ratios, "c_marketCap_to_freeCashFlow", "marketCap", "freeCashFlow")
add_ratio(df_ratios, "c_marketCap_to_netIncome", "marketCap", "netIncome")

add_ratio(df_ratios, "c_revenue_to_marketCap", "revenue", "marketCap")
add_ratio(df_ratios, "c_operatingCashFlow_to_marketCap", "operatingCashFlow", "marketCap")
add_ratio(df_ratios, "c_freeCashFlow_to_marketCap", "freeCashFlow", "marketCap")
add_ratio(df_ratios, "c_netIncome_to_marketCap", "netIncome", "marketCap")
add_ratio(df_ratios, "c_totalEquity_to_marketCap", "totalEquity", "marketCap")
add_ratio(df_ratios, "c_totalDebt_to_marketCap", "totalDebt", "marketCap")
add_ratio(df_ratios, "c_netDebt_to_marketCap", "netDebt", "marketCap")

add_ratio(df_ratios, "c_enterpriseValue_to_revenue", "enterpriseValue", "revenue")
add_ratio(df_ratios, "c_enterpriseValue_to_operatingCashFlow", "enterpriseValue", "operatingCashFlow")
add_ratio(df_ratios, "c_enterpriseValue_to_freeCashFlow", "enterpriseValue", "freeCashFlow")
add_ratio(df_ratios, "c_enterpriseValue_to_ebitda", "enterpriseValue", "ebitda")
add_ratio(df_ratios, "c_enterpriseValue_to_ebit", "enterpriseValue", "ebit")

# Ratios basados en precio por acción:
add_ratio(df_ratios, "c_stockPrice_to_eps", "stockPrice", "eps")
add_ratio(df_ratios, "c_stockPrice_to_bookValuePerShare", "stockPrice", "bookValuePerShare")
add_ratio(df_ratios, "c_stockPrice_to_revenuePerShare", "stockPrice", "revenuePerShare")
add_ratio(df_ratios, "c_stockPrice_to_operatingCashFlowPerShare", "stockPrice", "operatingCashFlowPerShare")
add_ratio(df_ratios, "c_stockPrice_to_freeCashFlowPerShare", "stockPrice", "freeCashFlowPerShare")
add_ratio(df_ratios, "c_dividendPerShare_to_stockPrice", "dividendPerShare", "stockPrice")


# Ratios sobre payouts y dividendos:

add_ratio(df_ratios, "c_netDividendsPaid_to_netIncome", "netDividendsPaid", "netIncome", abs_num=True)
add_ratio(df_ratios, "c_commonDividendsPaid_to_netIncome", "commonDividendsPaid", "netIncome", abs_num=True)
add_ratio(df_ratios, "c_netDividendsPaid_to_freeCashFlow", "netDividendsPaid", "freeCashFlow", abs_num=True)
add_ratio(df_ratios, "c_commonDividendsPaid_to_freeCashFlow", "commonDividendsPaid", "freeCashFlow", abs_num=True)
add_ratio(df_ratios, "c_netDividendsPaid_to_marketCap", "netDividendsPaid", "marketCap", abs_num=True)
add_ratio(df_ratios, "c_commonDividendsPaid_to_marketCap", "commonDividendsPaid", "marketCap", abs_num=True)


# Ratios sobre per-share útiles derivados (relativos, aunque no "ratio" clásico)

add_ratio(df_ratios, "c_revenue_to_weightedAverageShsOut", "revenue", "weightedAverageShsOut")
add_ratio(df_ratios, "c_netIncome_to_weightedAverageShsOut", "netIncome", "weightedAverageShsOut")
add_ratio(df_ratios, "c_operatingCashFlow_to_weightedAverageShsOut", "operatingCashFlow", "weightedAverageShsOut")
add_ratio(df_ratios, "c_freeCashFlow_to_weightedAverageShsOut", "freeCashFlow", "weightedAverageShsOut")
add_ratio(df_ratios, "c_totalEquity_to_weightedAverageShsOut", "totalEquity", "weightedAverageShsOut")
add_ratio(df_ratios, "c_cashAndCashEquivalents_to_weightedAverageShsOut", "cashAndCashEquivalents", "weightedAverageShsOut")

C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\3818856884.py:143: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_ratios["c_dividendsPaid_plus_capex_to_operatingCashFlow"] = dividir(
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)
C:\Users\mging\AppData\Local\Temp\ipykernel_49516\1077468015.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = dividir(num, den)

In [16]:

# Lista final de ratios (c_) creados:

created_c_cols = [c for c in df_ratios.columns if c.startswith("c_")]

print("Cantidad de ratios nuevos creados:", len(created_c_cols))
print("\nColumnas originales que ya eran ratios / relativas de origen:")
print(original_ratio_cols)

print("\nOtras columnas relativas de origen (per-share / días / ciclos / múltiplos):")
print(original_relative_cols)

Cantidad de ratios nuevos creados: 139

Columnas originales que ya eran ratios / relativas de origen:
['grossProfitMargin', 'ebitMargin', 'ebitdaMargin', 'operatingProfitMargin', 'pretaxProfitMargin', 'continuousOperationsProfitMargin', 'netProfitMargin', 'bottomLineProfitMargin', 'receivablesTurnover', 'payablesTurnover', 'inventoryTurnover', 'fixedAssetTurnover', 'assetTurnover', 'currentRatio', 'quickRatio', 'solvencyRatio', 'cashRatio', 'priceToEarningsRatio', 'priceToEarningsGrowthRatio', 'forwardPriceToEarningsGrowthRatio', 'priceToBookRatio', 'priceToSalesRatio', 'priceToFreeCashFlowRatio', 'priceToOperatingCashFlowRatio', 'debtToAssetsRatio', 'debtToEquityRatio', 'debtToCapitalRatio', 'longTermDebtToCapitalRatio', 'financialLeverageRatio', 'workingCapitalTurnoverRatio', 'operatingCashFlowRatio', 'operatingCashFlowSalesRatio', 'freeCashFlowOperatingCashFlowRatio', 'debtServiceCoverageRatio', 'interestCoverageRatio', 'shortTermOperatingCashFlowCoverageRatio', 'operatingCashFlowCoverageRatio', 'capitalExpenditureCoverageRatio', 'dividendPaidAndCapexCoverageRatio', 'dividendPayoutRatio', 'dividendYield', 'dividendYieldPercentage', 'netIncomePerEBT', 'ebtPerEbit', 'priceToFairValue', 'debtToMarketCap', 'evToSales', 'evToOperatingCashFlow', 'evToFreeCashFlow', 'evToEBITDA', 'netDebtToEBITDA', 'incomeQuality', 'taxBurden', 'interestBurden', 'returnOnAssets', 'operatingReturnOnAssets', 'returnOnTangibleAssets', 'returnOnEquity', 'returnOnInvestedCapital', 'returnOnCapitalEmployed', 'earningsYield', 'freeCashFlowYield', 'capexToOperatingCashFlow', 'capexToDepreciation', 'capexToRevenue', 'salesGeneralAndAdministrativeToRevenue', 'researchAndDevelopementToRevenue', 'stockBasedCompensationToRevenue', 'intangiblesToTotalAssets', 'freeCashFlowToEquity', 'freeCashFlowToFirm']

Otras columnas relativas de origen (per-share / días / ciclos / múltiplos):
['revenuePerShare', 'netIncomePerShare', 'interestDebtPerShare', 'cashPerShare', 'bookValuePerShare', 'tangibleBookValuePerShare', 'shareholdersEquityPerShare', 'operatingCashFlowPerShare', 'capexPerShare', 'freeCashFlowPerShare', 'daysOfSalesOutstanding', 'daysOfPayablesOutstanding', 'daysOfInventoryOutstanding', 'operatingCycle', 'cashConversionCycle', 'enterpriseValueMultiple']

In [17]:
df_ratios.head(10)

,symbol,date,fiscalYear,period,grossProfitMargin,ebitMargin,ebitdaMargin,operatingProfitMargin,pretaxProfitMargin,continuousOperationsProfitMargin,netProfitMargin,bottomLineProfitMargin,receivablesTurnover,payablesTurnover,inventoryTurnover,fixedAssetTurnover,assetTurnover,currentRatio,quickRatio,solvencyRatio,cashRatio,priceToEarningsRatio,priceToEarningsGrowthRatio,forwardPriceToEarningsGrowthRatio,priceToBookRatio,priceToSalesRatio,priceToFreeCashFlowRatio,priceToOperatingCashFlowRatio,debtToAssetsRatio,debtToEquityRatio,debtToCapitalRatio,longTermDebtToCapitalRatio,financialLeverageRatio,workingCapitalTurnoverRatio,operatingCashFlowRatio,operatingCashFlowSalesRatio,freeCashFlowOperatingCashFlowRatio,debtServiceCoverageRatio,interestCoverageRatio,shortTermOperatingCashFlowCoverageRatio,operatingCashFlowCoverageRatio,capitalExpenditureCoverageRatio,dividendPaidAndCapexCoverageRatio,dividendPayoutRatio,dividendYield,dividendYieldPercentage,revenuePerShare,netIncomePerShare,interestDebtPerShare,cashPerShare,bookValuePerShare,tangibleBookValuePerShare,shareholdersEquityPerShare,operatingCashFlowPerShare,capexPerShare,freeCashFlowPerShare,netIncomePerEBT,ebtPerEbit,priceToFairValue,debtToMarketCap,effectiveTaxRate,enterpriseValueMultiple,dividendPerShare,marketCap,enterpriseValue,evToSales,evToOperatingCashFlow,evToFreeCashFlow,evToEBITDA,netDebtToEBITDA,incomeQuality,grahamNumber,grahamNetNet,taxBurden,interestBurden,workingCapital,investedCapital,returnOnAssets,operatingReturnOnAssets,returnOnTangibleAssets,returnOnEquity,returnOnInvestedCapital,returnOnCapitalEmployed,earningsYield,freeCashFlowYield,capexToOperatingCashFlow,capexToDepreciation,capexToRevenue,salesGeneralAndAdministrativeToRevenue,researchAndDevelopementToRevenue,stockBasedCompensationToRevenue,intangiblesToTotalAssets,averageReceivables,averagePayables,averageInventory,daysOfSalesOutstanding,daysOfPayablesOutstanding,daysOfInventoryOutstanding,operatingCycle,cashConversionCycle,freeCashFlowToEquity,freeCashFlowToFirm,tangibleAssetValue,netCurrentAssetValue,stockPrice,numberOfShares,marketCapitalization,minusCashAndCashEquivalents,addTotalDebt,reportedCurrency,cashAndCashEquivalents,shortTermInvestments,cashAndShortTermInvestments,netReceivables,accountsReceivables,otherReceivables,inventory,prepaids,otherCurrentAssets,totalCurrentAssets,propertyPlantEquipmentNet,goodwill,intangibleAssets,goodwillAndIntangibleAssets,longTermInvestments,taxAssets,otherNonCurrentAssets,totalNonCurrentAssets,otherAssets,totalAssets,totalPayables,accountPayables,otherPayables,accruedExpenses,shortTermDebt,capitalLeaseObligationsCurrent,taxPayables,deferredRevenue,otherCurrentLiabilities,totalCurrentLiabilities,longTermDebt,capitalLeaseObligationsNonCurrent,deferredRevenueNonCurrent,deferredTaxLiabilitiesNonCurrent,otherNonCurrentLiabilities,totalNonCurrentLiabilities,otherLiabilities,capitalLeaseObligations,totalLiabilities,treasuryStock,preferredStock,commonStock,retainedEarnings,additionalPaidInCapital,accumulatedOtherComprehensiveIncomeLoss,otherTotalStockholdersEquity,totalStockholdersEquity,totalEquity,minorityInterest,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt,acceptedDate,revenue,costOfRevenue,grossProfit,researchAndDevelopmentExpenses,generalAndAdministrativeExpenses,sellingAndMarketingExpenses,sellingGeneralAndAdministrativeExpenses,otherExpenses,operatingExpenses,costAndExpenses,netInterestIncome,interestIncome,interestExpense,depreciationAndAmortization,ebitda,ebit,nonOperatingIncomeExcludingInterest,operatingIncome,totalOtherIncomeExpensesNet,incomeBeforeTax,incomeTaxExpense,netIncomeFromContinuingOperations,netIncomeFromDiscontinuedOperations,otherAdjustmentsToNetIncome,netIncome,netIncomeDeductions,bottomLineNetIncome,eps,epsDiluted,weightedAverageShsOut,weightedAverageShsOutDil,deferredIncomeTax,stockBasedCompensation,changeInWorkingCapital,accountsPayables,otherWorkingCapital,otherNonCashItems,netCashProvidedByOperatingActivities,investmentsInPropertyPlantAndEquipment,acquisitionsNet,purchasesOfInvestments,salesMaturitiesOfInvestments,otherInvestingActivities,netCashProvidedByInvestingActivities,netDebtIssuance,longTermNetDebtIssuance,shortTermNetDebtIssuance,netStockIssuance,netCommonStockIssuance,commonStockIssuance,commonStockRepurchased,netPreferredStockIssuance,netDividendsPaid,commonDividendsPaid,preferredDividendsPaid,otherFinancingActivities,netCashProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow,incomeTaxesPaid,interestPaid,c_grossProfit_to_revenue,c_ebitda_to_revenue,c_ebit_to_revenue,c_operatingIncome_to_revenue,c_incomeBeforeTax_to_revenue,c_netIncome_to_revenue,c_bottomLineNetIncome_to_revenue,c_netIncomeFromContinuingOperations_to_revenue,c_costOfRevenue_to_revenue,c_operatingExpenses_to_revenue,c_costAndExpenses_to_revenue,c_researchAndDevelopmentExpenses_to_revenue,c_generalAndAdministrativeExpenses_to_revenue,c_sellingAndMarketingExpenses_to_revenue,c_sellingGeneralAndAdministrativeExpenses_to_revenue,c_depreciationAndAmortization_to_revenue,c_interestExpense_to_revenue,c_incomeTaxExpense_to_revenue,c_stockBasedCompensation_to_revenue,c_otherExpenses_to_revenue,c_nonOperatingIncomeExcludingInterest_to_revenue,c_totalOtherIncomeExpensesNet_to_revenue,c_revenue_to_totalAssets,c_grossProfit_to_totalAssets,c_ebitda_to_totalAssets,c_ebit_to_totalAssets,c_operatingIncome_to_totalAssets,c_netIncome_to_totalAssets,c_operatingCashFlow_to_totalAssets,c_freeCashFlow_to_totalAssets,c_netIncome_to_totalEquity,c_operatingIncome_to_totalEquity,c_totalDebt_to_totalEquity,c_totalLiabilities_to_totalEquity,c_netDebt_to_totalEquity,c_netIncome_to_investedCapital,c_operatingIncome_to_investedCapital,c_ebit_to_investedCapital,c_netIncome_to_tangibleAssetValue,c_operatingIncome_to_tangibleAssetValue,c_totalDebt_to_totalAssets,c_totalLiabilities_to_totalAssets,c_netDebt_to_totalAssets,c_longTermDebt_to_totalAssets,c_shortTermDebt_to_totalAssets,c_longTermDebt_to_totalDebt,c_shortTermDebt_to_totalDebt,c_totalDebt_to_capital,c_longTermDebt_to_capital,c_cashAndCashEquivalents_to_totalDebt,c_cashAndShortTermInvestments_to_totalDebt,c_cashAndCashEquivalents_to_totalAssets,c_cashAndShortTermInvestments_to_totalAssets,c_workingCapital_to_totalAssets,c_workingCapital_to_revenue,c_investedCapital_to_totalAssets,c_totalCurrentAssets_to_totalCurrentLiabilities,c_cashAndCashEquivalents_to_totalCurrentLiabilities,c_cashAndShortTermInvestments_to_totalCurrentLiabilities,c_netReceivables_to_totalCurrentLiabilities,c_inventory_to_totalCurrentAssets,c_netReceivables_to_totalCurrentAssets,c_otherCurrentAssets_to_totalCurrentAssets,c_prepaids_to_totalCurrentAssets,c_totalCurrentAssets_to_totalAssets,c_totalNonCurrentAssets_to_totalAssets,c_propertyPlantEquipmentNet_to_totalAssets,c_inventory_to_totalAssets,c_netReceivables_to_totalAssets,c_goodwill_to_totalAssets,c_intangibleAssets_to_totalAssets,c_goodwillAndIntangibleAssets_to_totalAssets,c_longTermInvestments_to_totalAssets,c_totalInvestments_to_totalAssets,c_totalCurrentLiabilities_to_totalLiabilities,c_totalNonCurrentLiabilities_to_totalLiabilities,c_accountPayables_to_totalLiabilities,c_totalPayables_to_totalLiabilities,c_shortTermDebt_to_totalLiabilities,c_longTermDebt_to_totalLiabilities,c_revenue_to_averageReceivables,c_costOfRevenue_to_averagePayables,c_costOfRevenue_to_averageInventory,c_revenue_to_propertyPlantEquipmentNet,c_revenue_to_workingCapital,c_operatingCashFlow_to_revenue,c_freeCashFlow_to_revenue,c_operatingCashFlow_to_totalDebt,c_freeCashFlow_to_totalDebt,c_operatingCashFlow_to_totalCurrentLiabilities,c_operatingCashFlow_to_netIncome,c_freeCashFlow_to_netIncome,c_freeCashFlow_to_operatingCashFlow,c_ebit_to_interestExpense,c_operatingIncome_to_interestExpense,c_operatingCashFlow_to_interestExpense,c_capitalExpenditure_to_operatingCashFlow,c_investmentsInPropertyPlantAndEquipment_to_operatingCashFlow,c_netDividendsPaid_to_operatingCashFlow,c_commonDividendsPaid_to_operatingCashFlow,c_dividendsPaid_plus_capex_to_operatingCashFlow,c_incomeTaxExpense_to_incomeBeforeTax,c_netIncome_to_incomeBeforeTax,c_incomeBeforeTax_to_ebit,c_operatingCashFlow_to_netIncome_quality,c_marketCap_to_revenue,c_marketCap_to_operatingCashFlow,c_marketCap_to_freeCashFlow,c_marketCap_to_netIncome,c_revenue_to_marketCap,c_operatingCashFlow_to_marketCap,c_freeCashFlow_to_marketCap,c_netIncome_to_marketCap,c_totalEquity_to_marketCap,c_totalDebt_to_marketCap,c_netDebt_to_marketCap,c_enterpriseValue_to_revenue,c_enterpriseValue_to_operatingCashFlow,c_enterpriseValue_to_freeCashFlow,c_enterpriseValue_to_ebitda,c_enterpriseValue_to_ebit,c_stockPrice_to_eps,c_stockPrice_to_bookValuePerShare,c_stockPrice_to_revenuePerShare,c_stockPrice_to_operatingCashFlowPerShare,c_stockPrice_to_freeCashFlowPerShare,c_dividendPerShare_to_stockPrice,c_netDividendsPaid_to_netIncome,c_commonDividendsPaid_to_netIncome,c_netDividendsPaid_to_freeCashFlow,c_commonDividendsPaid_to_freeCashFlow,c_netDividendsPaid_to_marketCap,c_commonDividendsPaid_to_marketCap,c_revenue_to_weightedAverageShsOut,c_netIncome_to_weightedAverageShsOut,c_operatingCashFlow_to_weightedAverageShsOut,c_freeCashFlow_to_weightedAverageShsOut,c_totalEquity_to_weightedAverageShsOut,c_cashAndCashEquivalents_to_weightedAverageShsOut
0,HMY,2025-06-30,2025,Q4,0.400571,0.304421,0.370099,0.281703,0.295388,0.180084,0.177581,0.177581,9.184158,3.276621,5.760000,0.761462,0.474240,1.719890,1.411124,0.308406,1.057556,5.979035,-0.348547,-0.348547,3.236253,4.247059,28.838103,12.526131,0.028760,0.046211,0.044170,0.037783,1.606779,4.394429,1.005974,0.339056,0.434360,158.728814,0.000000,211.220339,5.590848,1.767910,1.464567,0.223686,0.009353,0.935294,58.138341,10.324281,3.525789,20.722906,76.735333,76.725843,76.297180,19.712148,11.149970,8.562178,0.601179,1.048580,3.236253,0.012511,0.390347,10.676222,2.309399,1.561006e+11,1.452286e+11,3.951262,11.653719,26.829605,10.676222,-0.799235,1.909300,133.129840,-17.361622,0.601179,0.970328,8.918000e+09,5.719300e+10,0.084216,0.141449,0.084223,0.135317,0.096854,0.159011,0.041813,0.034676,0.565640,2.920050,0.191783,0.021249,0.0,0.009740,0.000077,3.952500e+09,6.208000e+09,3.673000e+09,9.799483,27.467320,15.625000,25.424483,-2.042837,1.628500e+10,1.078405e+09,4.850600e+10,-7.685000e+09,246.92,632198987.0,1.561006e+11,1.310100e+10,2.229000e+09,ZAR,1.310100e+10,0.0,1.310100e+10,4.002000e+09,4.002000e+09,0.0,3.825000e+09,0.000000e+00,3.780000e+08,2.130600e+10,4.826900e+10,0.0,6000000.0,6000000.0,1.970000e+08,0.0,7.725000e+09,5.619700e+10,0.0,7.750300e+10,6.724000e+09,6.724000e+09,0.000000e+00,0.000000e+00,59000000.0,0.0,0.0,0.0,5.605000e+09,1.238800e+10,1.894000e+09,276000000.0,0.0,0.000000e+00,1.443300e+10,1.660300e+10,0.000000e+00,276000000.0,2.899100e+10,0.0,0.0,3.293400e+10,1.458400e+10,0.0,7.170000e+08,0.0,4.823500e+10,4.851200e+10,277000000.0,7.750300e+10,1.970000e+08,2.229000e+09,-1.087200e+10,2025-08-28 10:30:09,3.675500e+10,2.203200e+10,1.472300e+10,0.0,781000000.0,385000000.0,1.166000e+09,3.203000e+09,4.369000e+09,2.640100e+10,487000000.0,487000000.0,0.0,2.414000e+09,1.360300e+10,1.118900e+10,-8.350000e+08,1.035400e+10,5.030000e+08,1.085700e+10,4.238000e+09,6.619000e+09,0.000000e+00,0.0,6.527000e+09,0.000000e+00,6.527000e+09,10.48,10.32,632198987.0,633000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400571,0.370099,0.304421,0.281703,0.295388,0.177581,0.177581,0.180084,0.599429,0.118868,0.718297,0.0,0.021249,0.010475,0.031724,0.065678,0.000000,0.115304,NaN,0.087145,-0.022718,0.013685,0.474240,0.189967,0.175516,0.144369,0.133595,0.084216,NaN,NaN,0.134544,0.213432,0.045947,0.597605,-0.224109,0.114122,0.181036,0.195636,0.134561,0.213458,0.028760,0.374063,-0.140278,0.024438,0.000761,0.849708,0.026469,0.038973,0.033116,5.877524,5.877524,0.169039,0.169039,0.115067,0.242634,0.737946,1.719890,1.057556,1.057556,0.323055,0.179527,0.187834,0.017741,0.000000,0.274905,0.725095,0.622802,0.049353,0.051637,0.000000,0.000077,0.000077,0.002542,0.002542,0.427305,0.572695,0.231934,0.231934,0.002035,0.065331,9.299178,3.548969,5.998366,0.761462,4.121440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.390347,0.601179,0.970328,NaN,4.247059,NaN,NaN,23.916141,0.235457,NaN,NaN,0.041813,0.310774,0.014279,-0.069647,3.951262,NaN,NaN,10.676222,12.979592,23.561069,3.217814,4.247111,12.526286,28.838458,0.009353,NaN,NaN,NaN,NaN,NaN,NaN,58.138341,10.324281,NaN,NaN,76.735333,20.722906
1,HMY,2024-12-31,2025,Q2,0.392558,0.275545,0.340917,0.269325,0.278641,0.213484,0.211545,0.211545,9.516013,3.963633,6.407555,0.844056,0.539088,1.839063,1.460786,0.450070,1.009454,3.083338,0.015435,0.015435,2.114589,2.609062,18.015088,9.514301,0.029421,0.044233,0.042359,0.042359,1.503426,8.256308,1.094220,0.274225,0.528130,119.093023,0.000000,118.430233,5.024667,2.119226,1.885064,0.075983,0.006161,0.616079,59.419928,12.570000,3.242890,15.032165,73.663368,73.644170,73.314601,16.294444,7.688866,8.605578,0.759204,1.034590,2.114589,0.021805,0.233839,7.071091,0.955109,9.690316e+10,8.953416e+10,2.410656,8.790786,16.645130,7.071091,-0.581978,1.296296,143.997229,-14.027861,0.759204,1.011237,7.810000e+09,5.182500e+10,0.114041,0.154658,0.114061,0.171453,0.128430,0.167869,0.081081,0.055509,0.471870,1.979407,0.129399,0.023317,0.0,0.009181,0.000174,3.076000e+09,5.660500e+09,3.562000e+09,9.457742,22.706440,14.045920,23.503662,0.797222,1.274800e+10,-1.160109e+09,4.603200e+10,-5.734000e+09,155.03,625059665.0,9.690316e+10,9.396000e+09,2.027000e+09,ZAR,9.396000e+09,0.0,9.396000e+09,3.903000e+09,3.903000e+09,0.0,3.521000e+09,0.000000e+00,2.980000e+08,1.711800e+10,4.400300e+10,0.0,12000000.0,12000000.0,1.400000e+08,165000000.0,7.458000e+09,5.177800e+10,0.0,6.889600e+10,5.692000e+09,5.692000e+09,0.000000e+00,0.000000e+00,86000000.0,0.0,0.0,0.0,3.530000e+09,9.308000e+09,2.027000e+09,0.0,0.0,3.169000e+09,8.348000e+09,1.354400e+10,0.000000e+00,0.0,2.285200e+10,0.0,0.0,3.293400e+10,9.498000e+09,0.0,3.394000e+09,0.0,4.582600e+10,4.604400e+10,218000000.0,6.889600e+10,1.400000e+08,2.027000e+09,-7.369000e+09,2024-12-31 00:00:00,3.714100e+10,2.256100e+10,1.458000e+10,0.0,866000000.0,530000000.0,1.396000e+09,3.181000e+09,4.577000e+09,2.713800e+10,319000000.0,319000000.0,0.0,2.428000e+09,1.266200e+10,1.023400e+10,-2.310000e+08,1.000300e+10,3.460000e+08,1.034900e+10,2.420000e+09,7.929000e+09,0.000000e+00,0.0,7.857000e+09,0.000000e+00,7.857000e+09,12.65,12.57,625059665.0,625000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.392558,0.340917,0.275545,0.269325,0.278641,0.211545,0.211545,0.213484,0.607442,0.123233,0.730675,0.0,0.023317,0.014270,0.037586,0.065372,0.000000,0.065157,NaN,0.085647,-0.006220,0.009316,0.539088,0.211623,0.183784,0.148543,0.145190,0.114041,NaN,NaN,0.170641,0.217249,0.044023,0.496308,-0.160043,0.151606,0.193015,0.197472,0.170686,0.217305,0.029421,0.331688,-0.106958,0.029421,0.001248,1.000000,0.042427,0.039112,0.039112,4.635422,4.635422,0.136379,0.136379,0.113359,0.210280,0.752221,1.839063,1.009454,1.009454,0.419317,0.205690,0.228006,0.017409,0.000000,0.248461,0.751539,0.638687,0.051106,0.056651,0.000000,0.000174,0.000174,0.002032,0.002032,0.407317,0.592683,0.249081,0.249081,0.003763,0.088701,12.074447,3.985690,6.333801,0.844056,4.755570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.233839,0.759204,1.011237,NaN,2.609062,NaN,NaN,12.333353,0.383280,NaN,NaN,0.081081,0.475155,0.020918,-0.076045,2.410656,NaN,NaN,7.071091,8.748696,12.255336,2.104574,2.609057,9.514286,18.015059,0.006161,NaN,NaN,NaN,NaN,NaN,NaN,59.419928,12.570000,NaN,NaN,73.663368,15.032165
2,HMY,2024-06-30,2024,Q4,0.259098,0.153010,0.227168,0.226329,0.142680,0.091498,0.089452,0.089452,13.257003,3.924320,6.131002,0.721075,0.493136,1.115131,0.765664,0.250013,0.455189,9.835938,-0.176089,-0.176089,2.573448,3.519362,25.437524,12.123604,0.037893,0.056188,0.053199,0.041942,1.482808,11.740500,0.839476,0.290290,0.476603,14.494475,19.116147,961.666667,3.777826,1.910596,1.450478,0.538808,0.013695,1.369487,47.128270,4.215700,4.179344,7.479825,64.727671,64.697638,64.451050,13.680871,7.160525,6.520346,0.626939,0.630409,2.573448,0.017097,0.358721,15.137722,2.271451,1.049298e+11,1.025278e+11,3.438799,11.846076,24.855221,15.137722,-0.354643,3.245219,78.188181,-17.847175,0.626939,0.932486,1.187000e+09,4.255400e+10,0.044112,0.112237,0.044126,0.065409,0.085828,0.134556,0.025417,0.039312,0.523397,2.048847,0.151937,0.020023,0.0,0.000000,0.000314,2.768000e+09,5.395000e+09,3.408000e+09,6.788865,22.933907,14.679493,21.468358,-1.465549,6.527000e+09,3.311514e+09,4.093000e+10,-8.014000e+09,165.86,632635150.0,1.049298e+11,4.693000e+09,2.291000e+09,ZAR,4.693000e+09,39000000.0,4.732000e+09,2.249000e+09,1.428000e+09,821000000.0,3.603000e+09,3.550000e+08,5.580000e+08,1.149700e+10,4.134800e+10,0.0,19000000.0,19000000.0,2.530000e+08,140000000.0,7.203000e+09,4.896300e+10,0.0,6.046000e+10,8.580000e+09,5.629000e+09,2.951000e+09,1.084000e+09,9000000.0,260000000.0,366000000.0,85000000.0,2.920000e+08,1.031000e+10,1.785000e+09,246000000.0,0.0,2.951000e+09,7.170000e+09,1.215200e+10,-2.951000e+09,506000000.0,1.951100e+10,0.0,0.0,3.293400e+10,2.238000e+09,0.0,6.081000e+09,-479000000.0,4.077400e+10,4.094900e+10,175000000.0,6.046000e+10,2.920000e+08,2.291000e+09,-2.402000e+09,2024-10-31 12:23:52,2.981500e+10,2.209000e+10,7.725000e+09,0.0,597000000.0,0.0,5.970000e+08,3.800000e+08,9.770000e+08,2.306700e+10,102000000.0,455000000.0,353000000.0,2.211000e+09,6.773000e+09,4.562000e+09,2.186000e+09,6.748000e+09,-2.494000e+09,4.254000e+09,1.526000e+09,2.728000e+09,0.000000e+00,0.0,2.667000e+09,0.000000e+00,2.667000e+09,4.22,4.22,632635150.0,632635150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.259098,0.227168,0.153010,0.226329,0.142680,0.089452,0.089452,0.091498,0.740902,0.032769,0.773671,0.0,0.020023,0.000000,0.020023,0.074157,0.011840,0.051182,NaN,0.012745,0.073319,-0.083649,0.493136,0.127770,0.112024,0.075455,0.111611,0.044112,NaN,NaN,0.065130,0.164790,0.055948,0.476471,-0.058658,0.062673,0.158575,0.107205,0.065160,0.164867,0.037893,0.322709,-0.039729,0.029524,0.000149,0.779136,0.003928,0.053837,0.041947,2.048450,2.065474,0.077622,0.078267,0.019633,0.039812,0.703837,1.115131,0.455189,0.458972,0.218138,0.313386,0.195616,0.048534,0.030878,0.190159,0.809841,0.683890,0.059593,0.037198,0.000000,0.000314,0.000314,0.004185,0.004830,0.528420,0.622828,0.288504,0.439752,0.000461,0.091487,10.771315,4.094532,6.481808,0.721075,25.117944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.923513,19.116147,NaN,NaN,NaN,NaN,NaN,NaN,0.358721,0.626939,0.932486,NaN,3.519362,NaN,NaN,39.343753,0.284142,NaN,NaN,0.025417,0.390251,0.021834,-0.022891,3.438799,NaN,NaN,15.137722,22.474307,39.303318,2.562428,3.519331,12.123497,25.437301,0.013695,NaN,NaN,NaN,NaN,NaN,NaN,47.128270,4.215700,NaN,NaN,64.727671,7.418178

In [18]:
df_ratios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651247 entries, 0 to 651246
Columns: 369 entries, symbol to c_cashAndCashEquivalents_to_weightedAverageShsOut
dtypes: datetime64[ns](1), float64(363), int64(1), object(4)
memory usage: 1.8+ GB

In [19]:
cols_finales = (
    original_ratio_cols +
    created_c_cols +
    ["symbol", "date", "acceptedDate"]
)

df_fundamentals = df_ratios[cols_finales]

In [20]:
df_fundamentals = df_ratios[cols_finales]

In [21]:
df_fundamentals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651247 entries, 0 to 651246
Columns: 213 entries, grossProfitMargin to acceptedDate
dtypes: datetime64[ns](1), float64(210), object(2)
memory usage: 1.0+ GB

In [22]:
df_fundamentals.head(10)

,grossProfitMargin,ebitMargin,ebitdaMargin,operatingProfitMargin,pretaxProfitMargin,continuousOperationsProfitMargin,netProfitMargin,bottomLineProfitMargin,receivablesTurnover,payablesTurnover,inventoryTurnover,fixedAssetTurnover,assetTurnover,currentRatio,quickRatio,solvencyRatio,cashRatio,priceToEarningsRatio,priceToEarningsGrowthRatio,forwardPriceToEarningsGrowthRatio,priceToBookRatio,priceToSalesRatio,priceToFreeCashFlowRatio,priceToOperatingCashFlowRatio,debtToAssetsRatio,debtToEquityRatio,debtToCapitalRatio,longTermDebtToCapitalRatio,financialLeverageRatio,workingCapitalTurnoverRatio,operatingCashFlowRatio,operatingCashFlowSalesRatio,freeCashFlowOperatingCashFlowRatio,debtServiceCoverageRatio,interestCoverageRatio,shortTermOperatingCashFlowCoverageRatio,operatingCashFlowCoverageRatio,capitalExpenditureCoverageRatio,dividendPaidAndCapexCoverageRatio,dividendPayoutRatio,dividendYield,dividendYieldPercentage,netIncomePerEBT,ebtPerEbit,priceToFairValue,debtToMarketCap,evToSales,evToOperatingCashFlow,evToFreeCashFlow,evToEBITDA,netDebtToEBITDA,incomeQuality,taxBurden,interestBurden,returnOnAssets,operatingReturnOnAssets,returnOnTangibleAssets,returnOnEquity,returnOnInvestedCapital,returnOnCapitalEmployed,earningsYield,freeCashFlowYield,capexToOperatingCashFlow,capexToDepreciation,capexToRevenue,salesGeneralAndAdministrativeToRevenue,researchAndDevelopementToRevenue,stockBasedCompensationToRevenue,intangiblesToTotalAssets,freeCashFlowToEquity,freeCashFlowToFirm,c_grossProfit_to_revenue,c_ebitda_to_revenue,c_ebit_to_revenue,c_operatingIncome_to_revenue,c_incomeBeforeTax_to_revenue,c_netIncome_to_revenue,c_bottomLineNetIncome_to_revenue,c_netIncomeFromContinuingOperations_to_revenue,c_costOfRevenue_to_revenue,c_operatingExpenses_to_revenue,c_costAndExpenses_to_revenue,c_researchAndDevelopmentExpenses_to_revenue,c_generalAndAdministrativeExpenses_to_revenue,c_sellingAndMarketingExpenses_to_revenue,c_sellingGeneralAndAdministrativeExpenses_to_revenue,c_depreciationAndAmortization_to_revenue,c_interestExpense_to_revenue,c_incomeTaxExpense_to_revenue,c_stockBasedCompensation_to_revenue,c_otherExpenses_to_revenue,c_nonOperatingIncomeExcludingInterest_to_revenue,c_totalOtherIncomeExpensesNet_to_revenue,c_revenue_to_totalAssets,c_grossProfit_to_totalAssets,c_ebitda_to_totalAssets,c_ebit_to_totalAssets,c_operatingIncome_to_totalAssets,c_netIncome_to_totalAssets,c_operatingCashFlow_to_totalAssets,c_freeCashFlow_to_totalAssets,c_netIncome_to_totalEquity,c_operatingIncome_to_totalEquity,c_totalDebt_to_totalEquity,c_totalLiabilities_to_totalEquity,c_netDebt_to_totalEquity,c_netIncome_to_investedCapital,c_operatingIncome_to_investedCapital,c_ebit_to_investedCapital,c_netIncome_to_tangibleAssetValue,c_operatingIncome_to_tangibleAssetValue,c_totalDebt_to_totalAssets,c_totalLiabilities_to_totalAssets,c_netDebt_to_totalAssets,c_longTermDebt_to_totalAssets,c_shortTermDebt_to_totalAssets,c_longTermDebt_to_totalDebt,c_shortTermDebt_to_totalDebt,c_totalDebt_to_capital,c_longTermDebt_to_capital,c_cashAndCashEquivalents_to_totalDebt,c_cashAndShortTermInvestments_to_totalDebt,c_cashAndCashEquivalents_to_totalAssets,c_cashAndShortTermInvestments_to_totalAssets,c_workingCapital_to_totalAssets,c_workingCapital_to_revenue,c_investedCapital_to_totalAssets,c_totalCurrentAssets_to_totalCurrentLiabilities,c_cashAndCashEquivalents_to_totalCurrentLiabilities,c_cashAndShortTermInvestments_to_totalCurrentLiabilities,c_netReceivables_to_totalCurrentLiabilities,c_inventory_to_totalCurrentAssets,c_netReceivables_to_totalCurrentAssets,c_otherCurrentAssets_to_totalCurrentAssets,c_prepaids_to_totalCurrentAssets,c_totalCurrentAssets_to_totalAssets,c_totalNonCurrentAssets_to_totalAssets,c_propertyPlantEquipmentNet_to_totalAssets,c_inventory_to_totalAssets,c_netReceivables_to_totalAssets,c_goodwill_to_totalAssets,c_intangibleAssets_to_totalAssets,c_goodwillAndIntangibleAssets_to_totalAssets,c_longTermInvestments_to_totalAssets,c_totalInvestments_to_totalAssets,c_totalCurrentLiabilities_to_totalLiabilities,c_totalNonCurrentLiabilities_to_totalLiabilities,c_accountPayables_to_totalLiabilities,c_totalPayables_to_totalLiabilities,c_shortTermDebt_to_totalLiabilities,c_longTermDebt_to_totalLiabilities,c_revenue_to_averageReceivables,c_costOfRevenue_to_averagePayables,c_costOfRevenue_to_averageInventory,c_revenue_to_propertyPlantEquipmentNet,c_revenue_to_workingCapital,c_operatingCashFlow_to_revenue,c_freeCashFlow_to_revenue,c_operatingCashFlow_to_totalDebt,c_freeCashFlow_to_totalDebt,c_operatingCashFlow_to_totalCurrentLiabilities,c_operatingCashFlow_to_netIncome,c_freeCashFlow_to_netIncome,c_freeCashFlow_to_operatingCashFlow,c_ebit_to_interestExpense,c_operatingIncome_to_interestExpense,c_operatingCashFlow_to_interestExpense,c_capitalExpenditure_to_operatingCashFlow,c_investmentsInPropertyPlantAndEquipment_to_operatingCashFlow,c_netDividendsPaid_to_operatingCashFlow,c_commonDividendsPaid_to_operatingCashFlow,c_dividendsPaid_plus_capex_to_operatingCashFlow,c_incomeTaxExpense_to_incomeBeforeTax,c_netIncome_to_incomeBeforeTax,c_incomeBeforeTax_to_ebit,c_operatingCashFlow_to_netIncome_quality,c_marketCap_to_revenue,c_marketCap_to_operatingCashFlow,c_marketCap_to_freeCashFlow,c_marketCap_to_netIncome,c_revenue_to_marketCap,c_operatingCashFlow_to_marketCap,c_freeCashFlow_to_marketCap,c_netIncome_to_marketCap,c_totalEquity_to_marketCap,c_totalDebt_to_marketCap,c_netDebt_to_marketCap,c_enterpriseValue_to_revenue,c_enterpriseValue_to_operatingCashFlow,c_enterpriseValue_to_freeCashFlow,c_enterpriseValue_to_ebitda,c_enterpriseValue_to_ebit,c_stockPrice_to_eps,c_stockPrice_to_bookValuePerShare,c_stockPrice_to_revenuePerShare,c_stockPrice_to_operatingCashFlowPerShare,c_stockPrice_to_freeCashFlowPerShare,c_dividendPerShare_to_stockPrice,c_netDividendsPaid_to_netIncome,c_commonDividendsPaid_to_netIncome,c_netDividendsPaid_to_freeCashFlow,c_commonDividendsPaid_to_freeCashFlow,c_netDividendsPaid_to_marketCap,c_commonDividendsPaid_to_marketCap,c_revenue_to_weightedAverageShsOut,c_netIncome_to_weightedAverageShsOut,c_operatingCashFlow_to_weightedAverageShsOut,c_freeCashFlow_to_weightedAverageShsOut,c_totalEquity_to_weightedAverageShsOut,c_cashAndCashEquivalents_to_weightedAverageShsOut,symbol,date,acceptedDate
0,0.400571,0.304421,0.370099,0.281703,0.295388,0.180084,0.177581,0.177581,9.184158,3.276621,5.760000,0.761462,0.474240,1.719890,1.411124,0.308406,1.057556,5.979035,-0.348547,-0.348547,3.236253,4.247059,28.838103,12.526131,0.028760,0.046211,0.044170,0.037783,1.606779,4.394429,1.005974,0.339056,0.434360,158.728814,0.000000,211.220339,5.590848,1.767910,1.464567,0.223686,0.009353,0.935294,0.601179,1.048580,3.236253,0.012511,3.951262,11.653719,26.829605,10.676222,-0.799235,1.909300,0.601179,0.970328,0.084216,0.141449,0.084223,0.135317,0.096854,0.159011,0.041813,0.034676,0.565640,2.920050,0.191783,0.021249,0.0,0.009740,0.000077,1.628500e+10,1.078405e+09,0.400571,0.370099,0.304421,0.281703,0.295388,0.177581,0.177581,0.180084,0.599429,0.118868,0.718297,0.0,0.021249,0.010475,0.031724,0.065678,0.000000,0.115304,NaN,0.087145,-0.022718,0.013685,0.474240,0.189967,0.175516,0.144369,0.133595,0.084216,NaN,NaN,0.134544,0.213432,0.045947,0.597605,-0.224109,0.114122,0.181036,0.195636,0.134561,0.213458,0.028760,0.374063,-0.140278,0.024438,0.000761,0.849708,0.026469,0.038973,0.033116,5.877524,5.877524,0.169039,0.169039,0.115067,0.242634,0.737946,1.719890,1.057556,1.057556,0.323055,0.179527,0.187834,0.017741,0.000000,0.274905,0.725095,0.622802,0.049353,0.051637,0.000000,0.000077,0.000077,0.002542,0.002542,0.427305,0.572695,0.231934,0.231934,0.002035,0.065331,9.299178,3.548969,5.998366,0.761462,4.121440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.390347,0.601179,0.970328,NaN,4.247059,NaN,NaN,23.916141,0.235457,NaN,NaN,0.041813,0.310774,0.014279,-0.069647,3.951262,NaN,NaN,10.676222,12.979592,23.561069,3.217814,4.247111,12.526286,28.838458,0.009353,NaN,NaN,NaN,NaN,NaN,NaN,58.138341,10.324281,NaN,NaN,76.735333,20.722906,HMY,2025-06-30,2025-08-28 10:30:09
1,0.392558,0.275545,0.340917,0.269325,0.278641,0.213484,0.211545,0.211545,9.516013,3.963633,6.407555,0.844056,0.539088,1.839063,1.460786,0.450070,1.009454,3.083338,0.015435,0.015435,2.114589,2.609062,18.015088,9.514301,0.029421,0.044233,0.042359,0.042359,1.503426,8.256308,1.094220,0.274225,0.528130,119.093023,0.000000,118.430233,5.024667,2.119226,1.885064,0.075983,0.006161,0.616079,0.759204,1.034590,2.114589,0.021805,2.410656,8.790786,16.645130,7.071091,-0.581978,1.296296,0.759204,1.011237,0.114041,0.154658,0.114061,0.171453,0.128430,0.167869,0.081081,0.055509,0.471870,1.979407,0.129399,0.023317,0.0,0.009181,0.000174,1.274800e+10,-1.160109e+09,0.392558,0.340917,0.275545,0.269325,0.278641,0.211545,0.211545,0.213484,0.607442,0.123233,0.730675,0.0,0.023317,0.014270,0.037586,0.065372,0.000000,0.065157,NaN,0.085647,-0.006220,0.009316,0.539088,0.211623,0.183784,0.148543,0.145190,0.114041,NaN,NaN,0.170641,0.217249,0.044023,0.496308,-0.160043,0.151606,0.193015,0.197472,0.170686,0.217305,0.029421,0.331688,-0.106958,0.029421,0.001248,1.000000,0.042427,0.039112,0.039112,4.635422,4.635422,0.136379,0.136379,0.113359,0.210280,0.752221,1.839063,1.009454,1.009454,0.419317,0.205690,0.228006,0.017409,0.000000,0.248461,0.751539,0.638687,0.051106,0.056651,0.000000,0.000174,0.000174,0.002032,0.002032,0.407317,0.592683,0.249081,0.249081,0.003763,0.088701,12.074447,3.985690,6.333801,0.844056,4.755570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.233839,0.759204,1.011237,NaN,2.609062,NaN,NaN,12.333353,0.383280,NaN,NaN,0.081081,0.475155,0.020918,-0.076045,2.410656,NaN,NaN,7.071091,8.748696,12.255336,2.104574,2.609057,9.514286,18.015059,0.006161,NaN,NaN,NaN,NaN,NaN,NaN,59.419928,12.570000,NaN,NaN,73.663368,15.032165,HMY,2024-12-31,2024-12-31 00:00:00
2,0.259098,0.153010,0.227168,0.226329,0.142680,0.091498,0.089452,0.089452,13.257003,3.924320,6.131002,0.721075,0.493136,1.115131,0.765664,0.250013,0.455189,9.835938,-0.176089,-0.176089,2.573448,3.519362,25.437524,12.123604,0.037893,0.056188,0.053199,0.041942,1.482808,11.740500,0.839476,0.290290,0.476603,14.494475,19.116147,961.666667,3.777826,1.910596,1.450478,0.538808,0.013695,1.369487,0.626939,0.630409,2.573448,0.017097,3.438799,11.846076,24.855221,15.137722,-0.354643,3.245219,0.626939,0.932486,0.044112,0.112237,0.044126,0.065409,0.085828,0.134556,0.025417,0.039312,0.523397,2.048847,0.151937,0.020023,0.0,0.000000,0.000314,6.527000e+09,3.311514e+09,0.259098,0.227168,0.153010,0.226329,0.142680,0.089452,0.089452,0.091498,0.740902,0.032769,0.773671,0.0,0.020023,0.000000,0.020023,0.074157,0.011840,0.051182,NaN,0.012745,0.073319,-0.083649,0.493136,0.127770,0.112024,0.075455,0.111611,0.044112,NaN,NaN,0.065130,0.164790,0.055948,0.476471,-0.058658,0.062673,0.158575,0.107205,0.065160,0.164867,0.037893,0.322709,-0.039729,0.029524,0.000149,0.779136,0.003928,0.053837,0.041947,2.048450,2.065474,0.077622,0.078267,0.019633,0.039812,0.703837,1.115131,0.455189,0.458972,0.218138,0.313386,0.195616,0.048534,0.030878,0.190159,0.809841,0.683890,0.059593,0.037198,0.000000,0.000314,0.000314,0.004185,0.004830,0.528420,0.622828,0.288504,0.439752,0.000461,0.091487,10.771315,4.094532,6.481808,0.721075,25.117944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.923513,19.116147,NaN,NaN,NaN,NaN,NaN,NaN,0.358721,0.626939,0.932486,NaN,3.519362,NaN,NaN,39.343753,0.284142,NaN,NaN,0.025417,0.390251,0.021834,-0.022891,3.438799,NaN,NaN,15.137722,22.474307,39.303318,2.562428,3.519331,12.123497,25.437301,0.013695,NaN,NaN,NaN,NaN,NaN,NaN,47.128270,4.215700,NaN,NaN,64.727671,7.418178,HMY,2024-06-30,2024-10-31 12:23:52
3,0.269864,0.231783,0.308896,0.156127,0.239545,0.190248,0.187555,0.187555,9.602677,4.516760,7.255213,0.742578,0.527950,1.615239,1.107335,0.421685,0.549636,2.937062,0.000000,0.000000,1.746030,2.203448,22.241646,9.942763,0.056234,0.084402,0.077833,0.077534,1.500916,11.069262,1.105754,0.221613,0.447034,17.929978,11.124153,499.642857,2.080607,1.808428,1.802505,0.002147,0.000183,0.018276,0.782965,1.534294,1.746030,0.048340,2.199804,9.926323,22.204869,7.121500,-0.011795,1.181588,0.782965,1.033488,0.099020,0.084221,0.099063,0.148620,0.073192,0.092181,0.085119,0.044961,0.552966,1.624528,0.122545,0.000604,0.0,0.000023,0.000435,3.242000e+09,2.295419e+09,0.269864,0.308896,0.231783,0.156127,0.239545,0.187555,0.187555,0.190248,0.738531,0.031555,0.843873,0.0,0.000604,0.021478,0.022082,0.077113,0.014035,0.049297,NaN,0.009473,-0.075656,0.083418,0.527950,0.142475,0.163082,0.122370,0.082427,0.099020,NaN,NaN,0.148093,0.123277,0.084103,0.495585,-0.002877,0.127520,0.106152,0.157591,0.148189,0.123357,0.056234,0.331365,-0.001924,0.056000,0.000234,0.995836,0.004164,0.072419,0.072118,1.034206,1.105889,0.058157,0.062188,0.065099,0.123305,0.776503,1.615239,0.549636,0.587733,0.519602,0.314445,0.321687,0.027598,-0.027598,0.170910,0.829090,0.710969,0.053742,0.054979,0.000411,0.000024,0.000435,0.110377,0.114408,0.319318,0.680682,0.260512,0.260512,0.000707,0.168997,11.492445,7.323594,7.196974,0.742578,8.109969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.514673,11.124153,NaN,NaN,NaN,NaN,NaN,NaN,0.205793,0.782965,1.033488,NaN,2.203448,NaN,NaN,11.748248,0.453834,NaN,NaN,0.085119,0.574769,0.048340,-0.001653,2.199804,NaN,NaN,7.121500,9.490791,11.753138,1.739858,2.203486,9.942936,22.242034,0.000183,NaN,NaN,NaN,NaN,NaN,NaN,50.991922,9.563813,NaN,NaN,64.579968,5.617124,HMY,2023-12-31,2023-12-29 19:00:00
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.263725,0.788263,0.000000,0.417504,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.099493,0.163852,0.140784,0.138591,1.646863,0.000000,1.002330,0.000000,0.419730,0.000000,0.000000,0.000000,1.208604,1.723335,1.659354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.410867,0.978885,0.000000,0.000000,2.308957,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.580270,2.398799,0.000000,0.000000,0.0,0.000000,0.000577,6.100000e+07,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.163274,0.641055,0.081078,NaN,NaN,NaN,NaN,NaN,0.099493,0.390636,0.049406,0.097694,0.000000,0.981914,0.000000,0.131370,0.128994,0.503424,0.503424,0.050087,0.050087,0.031639,NaN,0.757355,1.263725,0.417504,0.417504,0.321247,0.376239,0.254206,0.017400,0.021779,0.151607,0.848393,0.725140,0.057041,0.038539,0.000000,0.000577,0.000577,0.001939,0.001939,0.307111,0.692889,0.053891,0.069320,0.000000,0.250089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HMY,2023-06-30,None
5,0.131765,0.003986,0.083332,0.108366,0.102004,0.002386,0.080131,0.002358,9.841338,4.344016,7.261662,0.589550,0.430218,1.516481,0.971604,0.169806,0.435862,4.840083,0.000000,0.000000,1.123108,1.551357,-61.279951,11.616200,0.129440,0.217816,0.178858,0.178858,1.682754,8.964844,0.608618,0.133551,-0.189560,2.558838,6.021792,22.050360,0.443881,0.840647,0.839732,0.002160,0.000112,0.011157,0.785562,0.941295,1.123108,0.197845,1.756586,13.152904,-69.386664,21.079273,2.462773,1.666667,0.785562,25.590767,0.034474,0.049664,0.034500,0.058011,0.040369,0.051481,0.051652,-0.016319,1.189560,2.002197,0.158867,0.000742,0.0,0.000035,0.000750,-5.291000e+09,-1.835060e+09,0.131765,0.083332,0.003986,0.108366,0.102004,0.080131,0.002358,0.002386,0.868235,0.023399,0.891634,0.0,0.000742,0.024486,0.025229,0.079346,0.017996,0.021786,NaN,-0.001830,0.104380,-0.105339,0.430218,0.056688,0.035851,0.001715,0.046621,0.034474,NaN,NaN,0.057847,0.078230,0.217200,0.677991,0.148155,0.044240,0.059828,0.002201,0.057919,0.078328,0.129440,0.404049,0.088293,0.129440,0.002606,1.000000,0.020130,0.166109,0.166109,0.317886,0.317886,0.041147,0.041147,0.048758,0.113333,0.779248,1.516481,0.435862,0.435862,0.463066,0.359303,0.305356,0.047925,0.000000,0.143162,0.856838,0.729740,0.051439,0.043715,0.000000,0.000750,0.000750,0.001893,0.001893,0.233646,0.766354,0.212814,0.212814,0.006449,0.320358,18.847128,6.808816,7.165049,0.589550,8.823529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.221497,6.021792,NaN,NaN,NaN,NaN,NaN,NaN,0.213584,0.785562,25.590767,NaN,1.551357,NaN,NaN,19.360333,0.644597,NaN,NaN,0.051652,0.892914,0.193941,0.132290,1.756586,NaN,NaN,21.079273,440.690848,19.362416,1.119842,1.551237,11.615302,-61.275215,0.000112,NaN,NaN,NaN,NaN,NaN,NaN,37.196110,2.980551,NaN,NaN,51.525122,3.557536,HMY,2022-12-31,2022-12-30 19:00:00
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.506332,0.939899,0.000000,0.492060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.077914,0.121409,0.108265,0.095728,1.558241,0.000000,0.651859,0.000000,0.061363,0.000000,0.000000,129.720000,0.889224,1.065375,1.062714,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.369719,6.025126,0.000000,0.000000,-1.329643,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.938637,1.530417,0.000000,0.000000,0.0,0.000000,0.001025,-1.000000e+09,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.121094,0.554205,0.039811,NaN,NaN,NaN,NaN,NaN,0.077914,0.356584,0.025615,0.067937,0.000534,0.871950,0.006855,0.102909,0.089732,0.671237,0.671237,0.052299,0.052299,0.053816,NaN,0.757114,1.506332,0.492060,0.492060,0.020781,0.376034,0.013796,0.072858,0.210651,0.160101,0.839899,0.702273,0.060203,0.002209,0.000000,0.001025,0.001025,0.002670,0.002670,0.298065,0.701935,0.075849,0.085915,0.001498,0.190522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HMY,2022-06-30,None
7,0.217894,0.006431,0.184593,0.094028,0.074621,0.004028,0.063186,0.003979,11.599165,4.072246,7.664224,0.611097,0.436751,1.494965,1.063129,0.182056,0.569326,7.307968,0.043346,0.043346,1.242368,1.847051,79.343654,11.014564,0.070990,0.109329,0.098554,0.089102,1.540060,8.170808,0.709632,0.167692,0.138821,10.162900,0.000000,9.798228,1.031683,1.161199,1.103417,0.119683,0.004094,0.409426,0.846764,0.793605,1.242368,0.088001,1.875056,11.181570,80.546686,10.157788,0.151715,2.653929,0.846764,11.602517,0.027597,0.041288,0.027790,0.042500,0.038927,0.045793,0.034209,0.012603,0.861179,1.751381,0.144413,0.024145,0.0,0.002688,0.006975,-1.032854e+08,-9.964505e+08,0.217894,0.184593,0.006431,0.094028,0.074621,0.063186,0.003979,0.004028,0.782106,0.151747,0.933853,0.0,0.024145,0.004601,0.028746,0.082456,0.000000,0.010660,NaN,0.000000,-0.000511,-0.019407,0.436751,0.095166,0.080621,0.002809,0.041067,0.027597,NaN,NaN,0.042417,0.063121,0.109114,0.537032,0.018800,0.035712,0.053143,0.003635,0.042877,0.063805,0.070990,0.349395,0.012231,0.063516,0.007475,0.894707,0.105293,0.091866,0.082193,0.827703,0.827703,0.058759,0.058759,0.051084,0.116964,0.772759,1.494965,0.569326,0.569326,0.364833,0.288860,0.244041,0.086269,0.000000,0.154292,0.845708,0.714700,0.044569,0.037654,0.006538,0.000437,0.006975,0.002538,0.002538,0.295390,0.704610,0.240076,0.240076,0.021393,0.181787,21.856866,6.253647,7.163126,0.611097,8.549619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.142857,0.846764,11.602517,NaN,1.847051,NaN,NaN,29.231874,0.541404,NaN,NaN,0.034209,0.806500,0.088001,0.015162,1.875056,NaN,NaN,10.157788,291.545870,29.232143,1.239971,1.847119,11.014974,79.346610,0.004094,NaN,NaN,NaN,NaN,NaN,NaN,35.449792,2.239937,NaN,NaN,52.807679,4.769286,HMY,2021-12-31,2021-12-30 19:00:00

In [23]:
df_fundamentals.shape

(651247, 213)

In [24]:
profiles_nyse_nasdaq_filtered = pd.read_parquet("archivos/profiles_nyse_nasdaq_filtered.parquet")

In [25]:
profiles_nyse_nasdaq_filtered.head(5)

,symbol,exchange,industry,sector,country,ipoDate,isEtf,isActivelyTrading,isAdr,isFund
0,NERV,NASDAQ,Biotechnology,Healthcare,US,2014-07-01,False,True,False,False
1,BIO,NYSE,Medical - Devices,Healthcare,US,1980-02-27,False,True,False,False
2,CSCO,NASDAQ,Communication Equipment,Technology,US,1990-02-16,False,True,False,False
3,AKAM,NASDAQ,Software - Infrastructure,Technology,US,1999-10-29,False,True,False,False
4,LUV,NYSE,"Airlines, Airports & Air Services",Industrials,US,1980-01-02,False,True,False,False

In [26]:
cols_profiles = [
    "symbol",
    "exchange",
    "industry",
    "sector",
    "country",
    "ipoDate",
    "isEtf",
    "isActivelyTrading",
    "isAdr",
    "isFund"
]

df_fundamentals = df_fundamentals.merge(
    profiles_nyse_nasdaq_filtered[cols_profiles],
    on="symbol",
    how="left"
)

In [27]:
df_fundamentals.head(60)

,grossProfitMargin,ebitMargin,ebitdaMargin,operatingProfitMargin,pretaxProfitMargin,continuousOperationsProfitMargin,netProfitMargin,bottomLineProfitMargin,receivablesTurnover,payablesTurnover,inventoryTurnover,fixedAssetTurnover,assetTurnover,currentRatio,quickRatio,solvencyRatio,cashRatio,priceToEarningsRatio,priceToEarningsGrowthRatio,forwardPriceToEarningsGrowthRatio,priceToBookRatio,priceToSalesRatio,priceToFreeCashFlowRatio,priceToOperatingCashFlowRatio,debtToAssetsRatio,debtToEquityRatio,debtToCapitalRatio,longTermDebtToCapitalRatio,financialLeverageRatio,workingCapitalTurnoverRatio,operatingCashFlowRatio,operatingCashFlowSalesRatio,freeCashFlowOperatingCashFlowRatio,debtServiceCoverageRatio,interestCoverageRatio,shortTermOperatingCashFlowCoverageRatio,operatingCashFlowCoverageRatio,capitalExpenditureCoverageRatio,dividendPaidAndCapexCoverageRatio,dividendPayoutRatio,dividendYield,dividendYieldPercentage,netIncomePerEBT,ebtPerEbit,priceToFairValue,debtToMarketCap,evToSales,evToOperatingCashFlow,evToFreeCashFlow,evToEBITDA,netDebtToEBITDA,incomeQuality,taxBurden,interestBurden,returnOnAssets,operatingReturnOnAssets,returnOnTangibleAssets,returnOnEquity,returnOnInvestedCapital,returnOnCapitalEmployed,earningsYield,freeCashFlowYield,capexToOperatingCashFlow,capexToDepreciation,capexToRevenue,salesGeneralAndAdministrativeToRevenue,researchAndDevelopementToRevenue,stockBasedCompensationToRevenue,intangiblesToTotalAssets,freeCashFlowToEquity,freeCashFlowToFirm,c_grossProfit_to_revenue,c_ebitda_to_revenue,c_ebit_to_revenue,c_operatingIncome_to_revenue,c_incomeBeforeTax_to_revenue,c_netIncome_to_revenue,c_bottomLineNetIncome_to_revenue,c_netIncomeFromContinuingOperations_to_revenue,c_costOfRevenue_to_revenue,c_operatingExpenses_to_revenue,c_costAndExpenses_to_revenue,c_researchAndDevelopmentExpenses_to_revenue,c_generalAndAdministrativeExpenses_to_revenue,c_sellingAndMarketingExpenses_to_revenue,c_sellingGeneralAndAdministrativeExpenses_to_revenue,c_depreciationAndAmortization_to_revenue,c_interestExpense_to_revenue,c_incomeTaxExpense_to_revenue,c_stockBasedCompensation_to_revenue,c_otherExpenses_to_revenue,c_nonOperatingIncomeExcludingInterest_to_revenue,c_totalOtherIncomeExpensesNet_to_revenue,c_revenue_to_totalAssets,c_grossProfit_to_totalAssets,c_ebitda_to_totalAssets,c_ebit_to_totalAssets,c_operatingIncome_to_totalAssets,c_netIncome_to_totalAssets,c_operatingCashFlow_to_totalAssets,c_freeCashFlow_to_totalAssets,c_netIncome_to_totalEquity,c_operatingIncome_to_totalEquity,c_totalDebt_to_totalEquity,c_totalLiabilities_to_totalEquity,c_netDebt_to_totalEquity,c_netIncome_to_investedCapital,c_operatingIncome_to_investedCapital,c_ebit_to_investedCapital,c_netIncome_to_tangibleAssetValue,c_operatingIncome_to_tangibleAssetValue,c_totalDebt_to_totalAssets,c_totalLiabilities_to_totalAssets,c_netDebt_to_totalAssets,c_longTermDebt_to_totalAssets,c_shortTermDebt_to_totalAssets,c_longTermDebt_to_totalDebt,c_shortTermDebt_to_totalDebt,c_totalDebt_to_capital,c_longTermDebt_to_capital,c_cashAndCashEquivalents_to_totalDebt,c_cashAndShortTermInvestments_to_totalDebt,c_cashAndCashEquivalents_to_totalAssets,c_cashAndShortTermInvestments_to_totalAssets,c_workingCapital_to_totalAssets,c_workingCapital_to_revenue,c_investedCapital_to_totalAssets,c_totalCurrentAssets_to_totalCurrentLiabilities,c_cashAndCashEquivalents_to_totalCurrentLiabilities,c_cashAndShortTermInvestments_to_totalCurrentLiabilities,c_netReceivables_to_totalCurrentLiabilities,c_inventory_to_totalCurrentAssets,c_netReceivables_to_totalCurrentAssets,c_otherCurrentAssets_to_totalCurrentAssets,c_prepaids_to_totalCurrentAssets,c_totalCurrentAssets_to_totalAssets,c_totalNonCurrentAssets_to_totalAssets,c_propertyPlantEquipmentNet_to_totalAssets,c_inventory_to_totalAssets,c_netReceivables_to_totalAssets,c_goodwill_to_totalAssets,c_intangibleAssets_to_totalAssets,c_goodwillAndIntangibleAssets_to_totalAssets,c_longTermInvestments_to_totalAssets,c_totalInvestments_to_totalAssets,c_totalCurrentLiabilities_to_totalLiabilities,c_totalNonCurrentLiabilities_to_totalLiabilities,c_accountPayables_to_totalLiabilities,c_totalPayables_to_totalLiabilities,c_shortTermDebt_to_totalLiabilities,c_longTermDebt_to_totalLiabilities,c_revenue_to_averageReceivables,c_costOfRevenue_to_averagePayables,c_costOfRevenue_to_averageInventory,c_revenue_to_propertyPlantEquipmentNet,c_revenue_to_workingCapital,c_operatingCashFlow_to_revenue,c_freeCashFlow_to_revenue,c_operatingCashFlow_to_totalDebt,c_freeCashFlow_to_totalDebt,c_operatingCashFlow_to_totalCurrentLiabilities,c_operatingCashFlow_to_netIncome,c_freeCashFlow_to_netIncome,c_freeCashFlow_to_operatingCashFlow,c_ebit_to_interestExpense,c_operatingIncome_to_interestExpense,c_operatingCashFlow_to_interestExpense,c_capitalExpenditure_to_operatingCashFlow,c_investmentsInPropertyPlantAndEquipment_to_operatingCashFlow,c_netDividendsPaid_to_operatingCashFlow,c_commonDividendsPaid_to_operatingCashFlow,c_dividendsPaid_plus_capex_to_operatingCashFlow,c_incomeTaxExpense_to_incomeBeforeTax,c_netIncome_to_incomeBeforeTax,c_incomeBeforeTax_to_ebit,c_operatingCashFlow_to_netIncome_quality,c_marketCap_to_revenue,c_marketCap_to_operatingCashFlow,c_marketCap_to_freeCashFlow,c_marketCap_to_netIncome,c_revenue_to_marketCap,c_operatingCashFlow_to_marketCap,c_freeCashFlow_to_marketCap,c_netIncome_to_marketCap,c_totalEquity_to_marketCap,c_totalDebt_to_marketCap,c_netDebt_to_marketCap,c_enterpriseValue_to_revenue,c_enterpriseValue_to_operatingCashFlow,c_enterpriseValue_to_freeCashFlow,c_enterpriseValue_to_ebitda,c_enterpriseValue_to_ebit,c_stockPrice_to_eps,c_stockPrice_to_bookValuePerShare,c_stockPrice_to_revenuePerShare,c_stockPrice_to_operatingCashFlowPerShare,c_stockPrice_to_freeCashFlowPerShare,c_dividendPerShare_to_stockPrice,c_netDividendsPaid_to_netIncome,c_commonDividendsPaid_to_netIncome,c_netDividendsPaid_to_freeCashFlow,c_commonDividendsPaid_to_freeCashFlow,c_netDividendsPaid_to_marketCap,c_commonDividendsPaid_to_marketCap,c_revenue_to_weightedAverageShsOut,c_netIncome_to_weightedAverageShsOut,c_operatingCashFlow_to_weightedAverageShsOut,c_freeCashFlow_to_weightedAverageShsOut,c_totalEquity_to_weightedAverageShsOut,c_cashAndCashEquivalents_to_weightedAverageShsOut,symbol,date,acceptedDate,exchange,industry,sector,country,ipoDate,isEtf,isActivelyTrading,isAdr,isFund
0,0.400571,0.304421,0.370099,0.281703,0.295388,0.180084,0.177581,0.177581,9.184158,3.276621,5.760000,0.761462,0.474240,1.719890,1.411124,0.308406,1.057556,5.979035,-0.348547,-0.348547,3.236253,4.247059,28.838103,12.526131,0.028760,0.046211,0.044170,0.037783,1.606779,4.394429,1.005974,0.339056,0.434360,158.728814,0.000000,211.220339,5.590848,1.767910,1.464567,0.223686,0.009353,0.935294,0.601179,1.048580,3.236253,0.012511,3.951262,11.653719,26.829605,10.676222,-0.799235,1.909300,0.601179,0.970328,0.084216,0.141449,0.084223,0.135317,0.096854,0.159011,0.041813,0.034676,0.565640,2.920050,0.191783,0.021249,0.000000,0.009740,0.000077,1.628500e+10,1.078405e+09,0.400571,0.370099,0.304421,0.281703,0.295388,0.177581,0.177581,0.180084,0.599429,0.118868,0.718297,0.000000,0.021249,0.010475,0.031724,0.065678,0.000000,0.115304,NaN,0.087145,-0.022718,0.013685,0.474240,0.189967,0.175516,0.144369,0.133595,0.084216,NaN,NaN,0.134544,0.213432,0.045947,0.597605,-0.224109,0.114122,0.181036,0.195636,0.134561,0.213458,0.028760,0.374063,-0.140278,0.024438,0.000761,0.849708,0.026469,0.038973,0.033116,5.877524,5.877524,0.169039,0.169039,0.115067,0.242634,0.737946,1.719890,1.057556,1.057556,0.323055,0.179527,0.187834,0.017741,0.000000,0.274905,0.725095,0.622802,0.049353,0.051637,0.000000,0.000077,0.000077,0.002542,0.002542,0.427305,0.572695,0.231934,0.231934,0.002035,0.065331,9.299178,3.548969,5.998366,0.761462,4.121440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.390347,0.601179,0.970328,NaN,4.247059,NaN,NaN,23.916141,0.235457,NaN,NaN,0.041813,0.310774,0.014279,-0.069647,3.951262,NaN,NaN,10.676222,12.979592,23.561069,3.217814,4.247111,12.526286,28.838458,0.009353,NaN,NaN,NaN,NaN,NaN,NaN,58.138341,10.324281,NaN,NaN,76.735333,20.722906,HMY,2025-06-30,2025-08-28 10:30:09,NYSE,Gold,Basic Materials,ZA,1994-05-17,False,True,True,False
1,0.392558,0.275545,0.340917,0.269325,0.278641,0.213484,0.211545,0.211545,9.516013,3.963633,6.407555,0.844056,0.539088,1.839063,1.460786,0.450070,1.009454,3.083338,0.015435,0.015435,2.114589,2.609062,18.015088,9.514301,0.029421,0.044233,0.042359,0.042359,1.503426,8.256308,1.094220,0.274225,0.528130,119.093023,0.000000,118.430233,5.024667,2.119226,1.885064,0.075983,0.006161,0.616079,0.759204,1.034590,2.114589,0.021805,2.410656,8.790786,16.645130,7.071091,-0.581978,1.296296,0.759204,1.011237,0.114041,0.154658,0.114061,0.171453,0.128430,0.167869,0.081081,0.055509,0.471870,1.979407,0.129399,0.023317,0.000000,0.009181,0.000174,1.274800e+10,-1.160109e+09,0.392558,0.340917,0.275545,0.269325,0.278641,0.211545,0.211545,0.213484,0.607442,0.123233,0.730675,0.000000,0.023317,0.014270,0.037586,0.065372,0.000000,0.065157,NaN,0.085647,-0.006220,0.009316,0.539088,0.211623,0.183784,0.148543,0.145190,0.114041,NaN,NaN,0.170641,0.217249,0.044023,0.496308,-0.160043,0.151606,0.193015,0.197472,0.170686,0.217305,0.029421,0.331688,-0.106958,0.029421,0.001248,1.000000,0.042427,0.039112,0.039112,4.635422,4.635422,0.136379,0.136379,0.113359,0.210280,0.752221,1.839063,1.009454,1.009454,0.419317,0.205690,0.228006,0.017409,0.000000,0.248461,0.751539,0.638687,0.051106,0.056651,0.000000,0.000174,0.000174,0.002032,0.002032,0.407317,0.592683,0.249081,0.249081,0.003763,0.088701,12.074447,3.985690,6.333801,0.844056,4.755570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.233839,0.759204,1.011237,NaN,2.609062,NaN,NaN,12.333353,0.383280,NaN,NaN,0.081081,0.475155,0.020918,-0.076045,2.410656,NaN,NaN,7.071091,8.748696,12.255336,2.104574,2.609057,9.514286,18.015059,0.006161,NaN,NaN,NaN,NaN,NaN,NaN,59.419928,12.570000,NaN,NaN,73.663368,15.032165,HMY,2024-12-31,2024-12-31 00:00:00,NYSE,Gold,Basic Materials,ZA,1994-05-17,False,True,True,False
2,0.259098,0.153010,0.227168,0.226329,0.142680,0.091498,0.089452,0.089452,13.257003,3.924320,6.131002,0.721075,0.493136,1.115131,0.765664,0.250013,0.455189,9.835938,-0.176089,-0.176089,2.573448,3.519362,25.437524,12.123604,0.037893,0.056188,0.053199,0.041942,1.482808,11.740500,0.839476,0.290290,0.476603,14.494475,19.116147,961.666667,3.777826,1.910596,1.450478,0.538808,0.013695,1.369487,0.626939,0.630409,2.573448,0.017097,3.438799,11.846076,24.855221,15.137722,-0.354643,3.245219,0.626939,0.932486,0.044112,0.112237,0.044126,0.065409,0.085828,0.134556,0.025417,0.039312,0.523397,2.048847,0.151937,0.020023,0.000000,0.000000,0.000314,6.527000e+09,3.311514e+09,0.259098,0.227168,0.153010,0.226329,0.142680,0.089452,0.089452,0.091498,0.740902,0.032769,0.773671,0.000000,0.020023,0.000000,0.020023,0.074157,0.011840,0.051182,NaN,0.012745,0.073319,-0.083649,0.493136,0.127770,0.112024,0.075455,0.111611,0.044112,NaN,NaN,0.065130,0.164790,0.055948,0.476471,-0.058658,0.062673,0.158575,0.107205,0.065160,0.164867,0.037893,0.322709,-0.039729,0.029524,0.000149,0.779136,0.003928,0.053837,0.041947,2.048450,2.065474,0.077622,0.078267,0.019633,0.039812,0.703837,1.115131,0.455189,0.458972,0.218138,0.313386,0.195616,0.048534,0.030878,0.190159,0.809841,0.683890,0.059593,0.037198,0.000000,0.000314,0.000314,0.004185,0.004830,0.528420,0.622828,0.288504,0.439752,0.000461,0.091487,10.771315,4.094532,6.481808,0.721075,25.117944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.923513,19.116147,NaN,NaN,NaN,NaN,NaN,NaN,0.358721,0.626939,0.932486,NaN,3.519362,NaN,NaN,39.343753,0.284142,NaN,NaN,0.025417,0.390251,0.021834,-0.022891,3.438799,NaN,NaN,15.137722,22.474307,39.303318,2.562428,3.519331,12.123497,25.437301,0.013695,NaN,NaN,NaN,NaN,NaN,NaN,47.128270,4.215700,NaN,NaN,64.727671,7.418178,HMY,2024-06-30,2024-10-31 12:23:52,NYSE,Gold,Basic Materials,ZA,1994-05-17,False,True,True,False
3,0.269864,0.231783,0.308896,0.156127,0.239545,0.190248,0.187555,0.187555,9.602677,4.516760,7.255213,0.742578,0.527950,1.615239,1.107335,0.421685,0.549636,2.937062,0.000000,0.000000,1.746030,2.203448,22.241646,9.942763,0.056234,0.084402,0.077833,0.077534,1.500916,11.069262,1.105754,0.221613,0.447034,17.929978,11.124153,499.642857,2.080607,1.808428,1.802505,0.002147,0.000183,0.018276,0.782965,1.534294,1.746030,0.048340,2.199804,9.926323,22.204869,7.121500,-0.011795,1.181588,0.782965,1.033488,0.099020,0.084221,0.099063,0.148620,0.073192,0.092181,0.085119,0.044961,0.552966,1.624528,0.122545,0.000604,0.000000,0.000023,0.000435,3.242000e+09,2.295419e+09,0.269864,0.308896,0.231783,0.156127,0.239545,0.187555,0.187555,0.190248,0.738531,0.031555,0.843873,0.000000,0.000604,0.021478,0.022082,0.077113,0.014035,0.049297,NaN,0.009473,-0.075656,0.083418,0.527950,0.142475,0.163082,0.122370,0.082427,0.099020,NaN,NaN,0.148093,0.123277,0.084103,0.495585,-0.002877,0.127520,0.106152,0.157591,0.148189,0.123357,0.056234,0.331365,-0.001924,0.056000,0.000234,0.995836,0.004164,0.072419,0.072118,1.034206,1.105889,0.058157,0.062188,0.065099,0.123305,0.776503,1.615239,0.549636,0.587733,0.519602,0.314445,0.321687,0.027598,-0.027598,0.170910,0.829090,0.710969,0.053742,0.054979,0.000411,0.000024,0.000435,0.110377,0.114408,0.319318,0.680682,0.260512,0.260512,0.000707,0.168997,11.492445,7.323594,7.196974,0.742578,8.109969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.514673,11.124153,NaN,NaN,NaN,NaN,NaN,NaN,0.205793,0.782965,1.033488,NaN,2.203448,NaN,NaN,11.748248,0.453834,NaN,NaN,0.085119,0.574769,0.048340,-0.001653,2.199804,NaN,NaN,7.121500,9.490791,11.753138,1.739858,2.203486,9.942936,22.242034,0.000183,NaN,NaN,NaN,NaN,NaN,NaN,50.991922,9.563813,NaN,NaN,64.579968,5.617124,HMY,2023-12-31,2023-12-29 19:00:00,NYSE,Gold,Basic Materials,ZA,1994-05-17,False,True,True,False
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.263725,0.788263,0.000000,0.417504,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.099493,0.163852,0.140784,0.138591,1.646863,0.000000,1.002330,0.000000,0.419730,0.000000,0.000000,0.000000,1.208604,1.723335,1.659354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.410867,0.978885,0.000000,0.000000,2.308957,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.580270,2.398799,0.000000,0.000000,0.000000,0.000000,0.000577,6.100000e+07,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.163274,0.641055,0.081078,NaN,NaN,NaN,NaN,NaN,0.099493,0.390636,0.049406,0.097694,0.000000,0.981914,0.000000,0.131370,0.128994,0.503424,0.503424,0.050087,0.050087,0.031639,NaN,0.757355,1.263725,0.417504,0.417504,0.321247,0.376239,0.254206,0.017400,0.021779,0.151607,0.848393,0.725140,0.057041,0.038539,0.000000,0.000577,0.000577,0.001939,0.001939,0.307111,0.692889,0.053891,0.069320,0.000000,0.250089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HMY,2023-06-30,None,NYSE,Gold,Basic Materials,ZA,1994-05-17,False,True,True,False
5,0.131765,0.003986,0.083332,0.108366,0.102004,0.002386,0.080131,0.002358,9.841338,4.344016,7.261662,0.589550,0.430218,1.516481,0.971604,0.169806,0.435862,4.840083,0.000000,0.000000,1.123108,1.551357,-61.279951,11.616200,0.129440,0.217816,0.178858,0.178858,1.682754,8.964844,0.608618,0.133551,-0.189560,2.558838,6.021792,22.050360,0.443881,0.840647,0.839732,0.002160,0.000112,0.011157,0.785562,0.941295,1.123108,0.197845,1.756586,13.152904,-69.386664,21.079273,2.462773,1.666667,0.785562,25.590767,0.034474,0.049664,0.034500,0.058011,0.040369,0.051481,0.051652,-0.016319,1.189560,2.002197,0.158867,0.000742,0.000000,0.000035,0.000750,-5.291000e+09,-1.835060e+09,0.131765,0.083332,0.003986,0.108366,0.102004,0.080131,0.002358,0.002386,0.868235,0.023399,0.891634,0.000000,0.000742,0.024486,0.025229,0.079346,0.017996,0.021786,NaN,-0.001830,0.104380,-0.105339,0.430218,0.056688,0.035851,0.001715,0.046621,0.034474,NaN,NaN,0.057847,0.078230,0.217200,0.677991,0.148155,0.044240,0.059828,0.002201,0.057919,0.078328,0.129440,0.404049,0.088293,0.129440,0.002606,1.000000,0.020130,0.166109,0.166109,0.317886,0.317886,0.041147,0.041147,0.048758,0.113333,0.779248,1.516481,0.435862,0.435862,0.463066,0.359303,0.305356,0.047925,0.000000,0.143162,0.856838,0.729740,0.051439,0.043715,0.000000,0.000750,0.000750,0.001893,0.001893,0.233646,0.766354,0.212814,0.212814,0.006449,0.320358,18.847128,6.808816,7.165049,0.589550,8.823529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.221497,6.021792,NaN,NaN,NaN,NaN,NaN,NaN,0.213584,0.785562,25.590767,NaN,1.551357,NaN,NaN,19.360333,0.644597,NaN,NaN,0.051652,0.892914,0.193941,0.132290,1.756586,NaN,NaN,21.079273,440.690848,19.362416,1.119842,1.551237,11.615302,-61.275215,0.000112,NaN,NaN,NaN,NaN,NaN,NaN,37.196110,2.980551,NaN,NaN,51.525122,3.557536,HMY,2022-12-31,2022-12-30 19:00:00,NYSE,Gold,Basic Materials,ZA,1994-05-17,False,True,True,False
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.506332,0.939899,0.000000,0.492060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.077914,0.121409,0.108265,0.095728,1.558241,0.000000,0.651859,0.000000,0.061363,0.000000,0.000000,129.720000,0.889224,1.065375,1.062714,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.369719,6.025126,0.000000,0.000000,-1.329643,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.938637,1.530417,0.000000,0.000000,0.000000,0.000000,0.001025,-1.000000e+09,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.121094,0.554205,0.039811,NaN,NaN,NaN,NaN,NaN,0.077914,0.356584,0.025615,0.067937,0.000534,0.871950,0.006855,0.102909,0.089732,0.671237,0.671237,0.052299,0.052299,0.053816,NaN,0.757114,1.506332,0.492060,0.492060,0.020781,0.376034,0.013796,0.072858,0.210651,0.160101,0.839899,0.702273,0.060203,0.002209,0.000000,0.001025,0.001025,0.002670,0.002670,0.298065,0.701935,0.075849,0.085915,0.001498,0.190522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HMY,2022-06-30,None,NYSE,Gold,Basic Materials,ZA,1994-05-17,False,True,True,False

In [28]:
df_fundamentals["acceptedDate"] = pd.to_datetime(df_fundamentals["acceptedDate"])

In [29]:
revisar_nulos(df_fundamentals)

,column,dtype,NaN,None,Null_string,Empty_string,Zero
0,grossProfitMargin,float64,0,0,0,0,77509
1,ebitMargin,float64,0,0,0,0,111790
2,ebitdaMargin,float64,0,0,0,0,85158
3,operatingProfitMargin,float64,0,0,0,0,74563
4,pretaxProfitMargin,float64,0,0,0,0,104519
5,continuousOperationsProfitMargin,float64,0,0,0,0,77515
6,netProfitMargin,float64,0,0,0,0,75259
7,bottomLineProfitMargin,float64,0,0,0,0,75904
8,receivablesTurnover,float64,0,0,0,0,154449
9,payablesTurnover,float64,0,0,0,0,231383
10,inventoryTurnover,float64,0,0,0,0,351401
11,fixedAssetTurnover,float64,0,0,0,0,160478
12,assetTurnover,float64,0,0,0,0,101300
13,currentRatio,float64,0,0,0,0,67196
14,quickRatio,float64,0,0,0,0,67232
15,solvencyRatio,float64,0,0,0,0,51830
16,cashRatio,float64,0,0,0,0,74639
17,priceToEarningsRatio,float64,0,0,0,0,29970
18,priceToEarningsGrowthRatio,float64,0,0,0,0,72945
19,forwardPriceToEarningsGrowthRatio,float64,0,0,0,0,72945
20,priceToBookRatio,float64,0,0,0,0,59362
21,priceToSalesRatio,float64,0,0,0,0,83002
22,priceToFreeCashFlowRatio,float64,0,0,0,0,75104
23,priceToOperatingCashFlowRatio,float64,0,0,0,0,75000
24,debtToAssetsRatio,float64,0,0,0,0,133910
25,debtToEquityRatio,float64,0,0,0,0,133741
26,debtToCapitalRatio,float64,0,0,0,0,133301
27,longTermDebtToCapitalRatio,float64,0,0,0,0,207304
28,financialLeverageRatio,float64,0,0,0,0,39936
29,workingCapitalTurnoverRatio,float64,0,0,0,0,121596
30,operatingCashFlowRatio,float64,0,0,0,0,96099
31,operatingCashFlowSalesRatio,float64,0,0,0,0,115810
32,freeCashFlowOperatingCashFlowRatio,float64,0,0,0,0,61985
33,debtServiceCoverageRatio,float64,0,0,0,0,162436
34,interestCoverageRatio,float64,0,0,0,0,256398
35,shortTermOperatingCashFlowCoverageRatio,float64,0,0,0,0,293011
36,operatingCashFlowCoverageRatio,float64,0,0,0,0,156334
37,capitalExpenditureCoverageRatio,float64,0,0,0,0,167248
38,dividendPaidAndCapexCoverageRatio,float64,0,0,0,0,118877
39,dividendPayoutRatio,float64,0,0,0,0,349411
40,dividendYield,float64,0,0,0,0,353342
41,dividendYieldPercentage,float64,0,0,0,0,353342
42,netIncomePerEBT,float64,0,0,0,0,51380
43,ebtPerEbit,float64,0,0,0,0,53478
44,priceToFairValue,float64,0,0,0,0,59362
45,debtToMarketCap,float64,0,0,0,0,166793
46,evToSales,float64,306,0,0,0,107182
47,evToOperatingCashFlow,float64,306,0,0,0,79172
48,evToFreeCashFlow,float64,306,0,0,0,79283
49,evToEBITDA,float64,306,0,0,0,70754
50,netDebtToEBITDA,float64,306,0,0,0,67181
51,incomeQuality,float64,306,0,0,0,65952
52,taxBurden,float64,306,0,0,0,51366
53,interestBurden,float64,306,0,0,0,93434
54,returnOnAssets,float64,306,0,0,0,51497
55,operatingReturnOnAssets,float64,306,0,0,0,71846
56,returnOnTangibleAssets,float64,306,0,0,0,51413
57,returnOnEquity,float64,306,0,0,0,49255
58,returnOnInvestedCapital,float64,306,0,0,0,72549
59,returnOnCapitalEmployed,float64,306,0,0,0,52690
60,earningsYield,float64,306,0,0,0,29943
61,freeCashFlowYield,float64,306,0,0,0,75082
62,capexToOperatingCashFlow,float64,306,0,0,0,167226
63,capexToDepreciation,float64,306,0,0,0,192369
64,capexToRevenue,float64,306,0,0,0,186989
65,salesGeneralAndAdministrativeToRevenue,float64,306,0,0,0,291312
66,researchAndDevelopementToRevenue,float64,306,0,0,0,496506
67,stockBasedCompensationToRevenue,float64,306,0,0,0,377138
68,intangiblesToTotalAssets,float64,306,0,0,0,260094
69,freeCashFlowToEquity,float64,306,0,0,0,59930
70,freeCashFlowToFirm,float64,306,0,0,0,92358
71,c_grossProfit_to_revenue,float64,72825,0,0,0,6749
72,c_ebitda_to_revenue,float64,72825,0,0,0,14557
73,c_ebit_to_revenue,float64,72827,0,0,0,41068
74,c_operatingIncome_to_revenue,float64,72825,0,0,0,3896
75,c_incomeBeforeTax_to_revenue,float64,72826,0,0,0,33766
76,c_netIncome_to_revenue,float64,72825,0,0,0,4561
77,c_bottomLineNetIncome_to_revenue,float64,72931,0,0,0,5045
78,c_netIncomeFromContinuingOperations_to_revenue,float64,74229,0,0,0,5348
79,c_costOfRevenue_to_revenue,float64,72825,0,0,0,89358
80,c_operatingExpenses_to_revenue,float64,72826,0,0,0,16412
81,c_costAndExpenses_to_revenue,float64,72825,0,0,0,15447
82,c_researchAndDevelopmentExpenses_to_revenue,float64,72835,0,0,0,424542
83,c_generalAndAdministrativeExpenses_to_revenue,float64,72834,0,0,0,219887
84,c_sellingAndMarketingExpenses_to_revenue,float64,72835,0,0,0,407257
85,c_sellingGeneralAndAdministrativeExpenses_to_r...,float64,72826,0,0,0,54578
86,c_depreciationAndAmortization_to_revenue,float64,72825,0,0,0,52510
87,c_interestExpense_to_revenue,float64,73267,0,0,0,200434
88,c_incomeTaxExpense_to_revenue,float64,72826,0,0,0,89560
89,c_stockBasedCompensation_to_revenue,float64,651241,0,0,0,5
90,c_otherExpenses_to_revenue,float64,72825,0,0,0,216966
91,c_nonOperatingIncomeExcludingInterest_to_revenue,float64,72829,0,0,0,296170
92,c_totalOtherIncomeExpensesNet_to_revenue,float64,72826,0,0,0,103551
93,c_revenue_to_totalAssets,float64,51285,0,0,0,52039
94,c_grossProfit_to_totalAssets,float64,51282,0,0,0,44521
95,c_ebitda_to_totalAssets,float64,51282,0,0,0,16745
96,c_ebit_to_totalAssets,float64,51285,0,0,0,44363
97,c_operatingIncome_to_totalAssets,float64,51282,0,0,0,4505
98,c_netIncome_to_totalAssets,float64,51282,0,0,0,2502
99,c_operatingCashFlow_to_totalAssets,float64,651238,0,0,0,0
100,c_freeCashFlow_to_totalAssets,float64,651238,0,0,0,0
101,c_netIncome_to_totalEquity,float64,55911,0,0,0,2411
102,c_operatingIncome_to_totalEquity,float64,55911,0,0,0,4413
103,c_totalDebt_to_totalEquity,float64,45282,0,0,0,94992
104,c_totalLiabilities_to_totalEquity,float64,45282,0,0,0,3024
105,c_netDebt_to_totalEquity,float64,45282,0,0,0,5887
106,c_netIncome_to_investedCapital,float64,51307,0,0,0,2509
107,c_operatingIncome_to_investedCapital,float64,51307,0,0,0,4293
108,c_ebit_to_investedCapital,float64,51310,0,0,0,44237
109,c_netIncome_to_tangibleAssetValue,float64,50670,0,0,0,2516
110,c_operatingIncome_to_tangibleAssetValue,float64,50670,0,0,0,4522
111,c_totalDebt_to_totalAssets,float64,40391,0,0,0,94617
112,c_totalLiabilities_to_totalAssets,float64,40391,0,0,0,1614
113,c_netDebt_to_totalAssets,float64,40391,0,0,0,5647
114,c_longTermDebt_to_totalAssets,float64,40391,0,0,0,168363
115,c_shortTermDebt_to_totalAssets,float64,40392,0,0,0,237045
116,c_longTermDebt_to_totalDebt,float64,134364,0,0,0,82135
117,c_shortTermDebt_to_totalDebt,float64,134365,0,0,0,143824
118,c_totalDebt_to_capital,float64,40435,0,0,0,96032
119,c_longTermDebt_to_capital,float64,40435,0,0,0,170004
120,c_cashAndCashEquivalents_to_totalDebt,float64,134364,0,0,0,11813
121,c_cashAndShortTermInvestments_to_totalDebt,float64,134364,0,0,0,10083
122,c_cashAndCashEquivalents_to_totalAssets,float64,40391,0,0,0,16584
123,c_cashAndShortTermInvestments_to_totalAssets,float64,40391,0,0,0,14639
124,c_workingCapital_to_totalAssets,float64,40668,0,0,0,8198
125,c_workingCapital_to_revenue,float64,73106,0,0,0,36441
126,c_investedCapital_to_totalAssets,float64,40668,0,0,0,2574
127,c_totalCurrentAssets_to_totalCurrentLiabilities,float64,63227,0,0,0,5148
128,c_cashAndCashEquivalents_to_totalCurrentLiabil...,float64,63227,0,0,0,12648
129,c_cashAndShortTermInvestments_to_totalCurrentL...,float64,63227,0,0,0,11104
130,c_netReceivables_to_totalCurrentLiabilities,float64,63227,0,0,0,86714
131,c_inventory_to_totalCurrentAssets,float64,50685,0,0,0,285589
132,c_netReceivables_to_totalCurrentAssets,float64,50685,0,0,0,92455
133,c_otherCurrentAssets_to_totalCurrentAssets,float64,50685,0,0,0,193123
134,c_prepaids_to_totalCurrentAssets,float64,50686,0,0,0,378600
135,c_totalCurrentAssets_to_totalAssets,float64,40391,0,0,0,12439
136,c_totalNonCurrentAssets_to_totalAssets,float64,40391,0,0,0,17847
137,c_propertyPlantEquipmentNet_to_totalAssets,float64,40391,0,0,0,94963
138,c_inventory_to_totalAssets,float64,40391,0,0,0,295902
139,c_netReceivables_to_totalAssets,float64,40391,0,0,0,96161
140,c_goodwill_to_totalAssets,float64,40392,0,0,0,357700
141,c_intangibleAssets_to_totalAssets,float64,40392,0,0,0,267891
142,c_goodwillAndIntangibleAssets_to_totalAssets,float64,40392,0,0,0,220783
143,c_longTermInvestments_to_totalAssets,float64,40392,0,0,0,309329
144,c_totalInvestments_to_totalAssets,float64,40394,0,0,0,241479
145,c_totalCurrentLiabilities_to_totalLiabilities,float64,40766,0,0,0,22537
146,c_totalNonCurrentLiabilities_to_totalLiabilities,float64,40766,0,0,0,52112
147,c_accountPayables_to_totalLiabilities,float64,40766,0,0,0,117595
148,c_totalPayables_to_totalLiabilities,float64,40769,0,0,0,105590
149,c_shortTermDebt_to_totalLiabilities,float64,40767,0,0,0,236203
150,c_longTermDebt_to_totalLiabilities,float64,40766,0,0,0,167645
151,c_revenue_to_averageReceivables,float64,147009,0,0,0,13527
152,c_costOfRevenue_to_averagePayables,float64,165349,0,0,0,67318
153,c_costOfRevenue_to_averageInventory,float64,337238,0,0,0,11885
154,c_revenue_to_propertyPlantEquipmentNet,float64,139909,0,0,0,22408
155,c_revenue_to_workingCapital,float64,56885,0,0,0,52662
156,c_operatingCashFlow_to_revenue,float64,651241,0,0,0,0
157,c_freeCashFlow_to_revenue,float64,651241,0,0,0,0
158,c_operatingCashFlow_to_totalDebt,float64,651239,0,0,0,0
159,c_freeCashFlow_to_totalDebt,float64,651239,0,0,0,0
160,c_operatingCashFlow_to_totalCurrentLiabilities,float64,651241,0,0,0,0
161,c_operatingCashFlow_to_netIncome,float64,651239,0,0,0,0
162,c_freeCashFlow_to_netIncome,float64,651239,0,0,0,0
163,c_freeCashFlow_to_operatingCashFlow,float64,651238,0,0,0,0
164,c_ebit_to_interestExpense,float64,255301,0,0,0,12297
165,c_operatingIncome_to_interestExpense,float64,255301,0,0,0,2711
166,c_operatingCashFlow_to_interestExpense,float64,651243,0,0,0,0
167,c_capitalExpenditure_to_operatingCashFlow,float64,651238,0,0,0,7
168,c_investmentsInPropertyPlantAndEquipment_to_op...,float64,651238,0,0,0,8
169,c_netDividendsPaid_to_operatingCashFlow,float64,651238,0,0,0,6
170,c_commonDividendsPaid_to_operatingCashFlow,float64,651238,0,0,0,6
171,c_dividendsPaid_plus_capex_to_operatingCashFlow,float64,651238,0,0,0,5
172,c_incomeTaxExpense_to_incomeBeforeTax,float64,53070,0,0,0,104309
173,c_netIncome_to_incomeBeforeTax,float64,53066,0,0,0,677
174,c_incomeBeforeTax_to_ebit,float64,65963,0,0,0,29755
175,c_operatingCashFlow_to_netIncome_quality,float64,651239,0,0,0,0
176,c_marketCap_to_revenue,float64,73106,0,0,0,12252
177,c_marketCap_to_operatingCashFlow,float64,651238,0,0,0,0
178,c_marketCap_to_freeCashFlow,float64,651238,0,0,0,0
179,c_marketCap_to_netIncome,float64,19581,0,0,0,13006
180,c_revenue_to_marketCap,float64,26314,0,0,0,59044
181,c_operatingCashFlow_to_marketCap,float64,651238,0,0,0,0
182,c_freeCashFlow_to_marketCap,float64,651238,0,0,0,0
183,c_netIncome_to_marketCap,float64,26311,0,0,0,6276
184,c_totalEquity_to_marketCap,float64,59939,0,0,0,7554
185,c_totalDebt_to_marketCap,float64,59938,0,0,0,84396
186,c_netDebt_to_marketCap,float64,59938,0,0,0,4567
187,c_enterpriseValue_to_revenue,float64,73106,0,0,0,36382
188,c_enterpriseValue_to_operatingCashFlow,float64,651238,0,0,0,0
189,c_enterpriseValue_to_freeCashFlow,float64,651238,0,0,0,0
190,c_enterpriseValue_to_ebitda,float64,34196,0,0,0,39174
191,c_enterpriseValue_to_ebit,float64,66232,0,0,0,29768
192,c_stockPrice_to_eps,float64,20865,0,0,0,11
193,c_stockPrice_to_bookValuePerShare,float64,61057,0,0,0,10
194,c_stockPrice_to_revenuePerShare,float64,82992,0,0,0,10
195,c_stockPrice_to_operatingCashFlowPerShare,float64,74991,0,0,0,9
196,c_stockPrice_to_freeCashFlowPerShare,float64,75095,0,0,0,9
197,c_dividendPerShare_to_stockPrice,float64,25,0,0,0,353317
198,c_netDividendsPaid_to_netIncome,float64,651239,0,0,0,6
199,c_commonDividendsPaid_to_netIncome,float64,651239,0,0,0,6
200,c_netDividendsPaid_to_freeCashFlow,float64,651238,0,0,0,6
201,c_commonDividendsPaid_to_freeCashFlow,float64,651238,0,0,0,6
202,c_netDividendsPaid_to_marketCap,float64,651238,0,0,0,6
203,c_commonDividendsPaid_to_marketCap,float64,651238,0,0,0,6
204,c_revenue_to_weightedAverageShsOut,float64,26026,0,0,0,59042
205,c_netIncome_to_weightedAverageShsOut,float64,26023,0,0,0,6275
206,c_operatingCashFlow_to_weightedAverageShsOut,float64,651238,0,0,0,0
207,c_freeCashFlow_to_weightedAverageShsOut,float64,651238,0,0,0,0
208,c_totalEquity_to_weightedAverageShsOut,float64,60729,0,0,0,7547
209,c_cashAndCashEquivalents_to_weightedAverageShsOut,float64,60729,0,0,0,14973
210,symbol,object,0,0,0,0,0
211,date,datetime64[ns],0,0,0,0,0
212,acceptedDate,datetime64[ns],12890,0,0,0,0
213,exchange,object,54592,0,0,0,0
214,industry,object,54592,0,0,0,0
215,sector,object,54592,0,0,0,0
216,country,object,54592,0,0,0,0
217,ipoDate,object,54592,0,0,4774,0
218,isEtf,object,54592,0,0,0,596433
219,isActivelyTrading,object,54592,0,0,0,139757
220,isAdr,object,54592,0,0,0,566291
221,isFund,object,54592,0,0,0,565696

In [30]:
df_fundamentals.shape

(651247, 222)

In [31]:
df_fundamentals = df_fundamentals.dropna(subset=["acceptedDate"])

In [32]:
df_fundamentals.shape

(638357, 222)

In [33]:
lstm_macro_features = pd.read_parquet("archivos/datos_economicos/proyecciones_economicas.parquet")

In [34]:
lstm_macro_features.head(10)

,iteracion,date_t0,rate_3m_t0,rate_2y_t0,rate_10y_t0,rate_30y_t0,industrial_production_t0,cfnai_t0,cpi_t0,core_cpi_t0,core_pce_t0,unemployment_t0,vix_t0,nfci_t0,baa_10y_t0,fed_funds_t0,house_price_index_t0,consumer_sentiment_t0,spread_10y_2y_t0,spread_10y_3m_t0,retail_sales_mom_t0,pce_mom_t0,payrolls_mom_t0,jobless_claims_mom_t0,m2_mom_t0,housing_starts_mom_t0,date_pred_t1,rate_3m_pred_t1,rate_2y_pred_t1,rate_10y_pred_t1,rate_30y_pred_t1,industrial_production_pred_t1,cfnai_pred_t1,cpi_pred_t1,core_cpi_pred_t1,core_pce_pred_t1,unemployment_pred_t1,vix_pred_t1,nfci_pred_t1,baa_10y_pred_t1,fed_funds_pred_t1,house_price_index_pred_t1,consumer_sentiment_pred_t1,spread_10y_2y_pred_t1,spread_10y_3m_pred_t1,retail_sales_mom_pred_t1,pce_mom_pred_t1,payrolls_mom_pred_t1,jobless_claims_mom_pred_t1,m2_mom_pred_t1,housing_starts_mom_pred_t1,date_pred_t2,rate_3m_pred_t2,rate_2y_pred_t2,rate_10y_pred_t2,rate_30y_pred_t2,industrial_production_pred_t2,cfnai_pred_t2,cpi_pred_t2,core_cpi_pred_t2,core_pce_pred_t2,unemployment_pred_t2,vix_pred_t2,nfci_pred_t2,baa_10y_pred_t2,fed_funds_pred_t2,house_price_index_pred_t2,consumer_sentiment_pred_t2,spread_10y_2y_pred_t2,spread_10y_3m_pred_t2,retail_sales_mom_pred_t2,pce_mom_pred_t2,payrolls_mom_pred_t2,jobless_claims_mom_pred_t2,m2_mom_pred_t2,housing_starts_mom_pred_t2,date_pred_t3,rate_3m_pred_t3,rate_2y_pred_t3,rate_10y_pred_t3,rate_30y_pred_t3,industrial_production_pred_t3,cfnai_pred_t3,cpi_pred_t3,core_cpi_pred_t3,core_pce_pred_t3,unemployment_pred_t3,vix_pred_t3,nfci_pred_t3,baa_10y_pred_t3,fed_funds_pred_t3,house_price_index_pred_t3,consumer_sentiment_pred_t3,spread_10y_2y_pred_t3,spread_10y_3m_pred_t3,retail_sales_mom_pred_t3,pce_mom_pred_t3,payrolls_mom_pred_t3,jobless_claims_mom_pred_t3,m2_mom_pred_t3,housing_starts_mom_pred_t3
0,1,1998-12-01,4.49,4.44,4.67,5.06,87.1185,0.25,164.4,175.4,73.076,4.4,24.97,-0.12,2.51,4.68,92.711,100.5,0.23,0.18,0.010724,0.009160,0.002932,0.006494,0.006672,0.079518,1999-01-01,4.650709,4.669050,4.761017,5.157753,86.766296,0.312743,163.302078,173.944824,72.552544,4.487325,34.322845,-0.274680,2.169026,5.250732,92.038033,100.610725,0.102249,0.180297,0.008526,0.006281,0.001884,-0.049615,0.008393,0.016403,1999-02-01,4.311602,4.343659,4.589108,5.021726,86.715134,0.123835,163.130219,174.134750,72.669189,4.495389,35.463223,-0.098906,2.483685,5.052017,92.166588,100.008339,0.286515,0.161535,0.008014,0.005006,0.001918,-0.020516,0.009049,0.012349,1999-03-01,4.366085,4.180119,4.468563,4.983758,87.013748,0.117505,162.925613,174.532059,72.958839,4.453832,31.103977,-0.055631,2.611041,4.780321,92.343262,100.554893,0.266795,0.209778,0.010938,0.005899,0.002186,0.000409,0.008126,0.039098
1,2,1999-01-01,4.48,4.54,4.65,5.09,87.4949,0.11,164.7,175.6,73.180,4.3,24.42,-0.21,2.58,4.63,93.207,103.9,0.11,0.17,0.000537,0.000560,0.000815,0.083871,0.006262,-0.024554,1999-02-01,4.539908,4.423872,4.637754,5.106643,86.880196,0.157875,163.211761,174.571274,72.827003,4.417794,33.290516,-0.222716,2.361879,5.167549,92.274048,101.729477,0.223416,0.102189,0.005774,0.004977,0.001816,-0.014268,0.008585,-0.007826,1999-03-01,4.453645,4.269349,4.549913,4.965466,87.692108,0.140329,163.806351,175.009033,72.842102,4.410286,32.004406,-0.080200,2.538677,4.948218,92.856735,100.082878,0.239328,0.083912,0.010226,0.006173,0.002068,-0.005207,0.008236,0.030514,1999-04-01,4.402354,4.197593,4.431099,4.910830,87.252762,0.129443,163.969833,175.451111,73.062592,4.399521,29.100441,-0.059438,2.603334,4.745779,93.451454,100.883400,0.225501,0.106188,0.008841,0.004566,0.001807,0.025827,0.007575,0.018919
2,3,1999-02-01,4.53,4.65,4.75,5.19,88.0270,0.53,164.7,175.6,73.155,4.4,27.67,-0.27,2.53,4.76,93.671,108.1,0.10,0.22,0.012806,0.004165,0.003273,-0.092262,0.005178,-0.044622,1999-03-01,4.547754,4.475512,4.887919,5.222099,83.950844,0.157255,161.693558,173.105560,72.248802,4.571322,28.840027,-0.197691,2.336543,4.954075,91.013031,99.883476,0.375214,0.184907,0.009541,0.006308,0.002043,-0.006435,0.007265,0.022816,1999-04-01,4.459205,4.627991,4.768421,5.312794,84.955521,0.178634,161.728836,173.611984,72.661148,4.541125,26.875158,-0.187052,2.415766,4.851914,91.526405,100.822205,0.311347,0.437442,0.008796,0.004466,0.002055,0.007907,0.006805,0.021475,1999-05-01,4.392742,4.549537,4.921632,5.326464,85.820831,0.229945,162.836273,173.546249,72.568825,4.599530,25.962475,-0.220440,2.448461,4.747489,91.779663,100.962410,0.237209,0.437492,0.007854,0.004292,0.002154,0.001008,0.006144,-0.006634
3,4,1999-03-01,4.71,5.20,5.40,5.67,88.2267,-0.08,164.8,175.7,73.177,4.2,28.37,-0.35,2.21,4.81,94.217,105.7,0.20,0.69,0.005511,0.005542,0.000913,-0.013115,0.001536,0.023952,1999-04-01,4.497494,4.656716,5.023150,5.364893,84.915169,0.235793,162.624329,172.538025,72.469009,4.660567,27.853819,-0.253953,2.335558,4.849386,91.030128,101.863930,0.381737,0.395797,0.006569,0.005264,0.002010,0.004860,0.006976,0.017700,1999-05-01,4.437101,4.599280,4.917485,5.275022,85.050850,0.224108,162.115005,173.257294,72.569244,4.656897,27.399767,-0.234870,2.394459,4.718532,91.527306,100.006813,0.328426,0.488302,0.009175,0.004527,0.002107,-0.008849,0.007107,0.009536,1999-06-01,4.501339,4.667932,4.931874,5.403261,85.046013,0.140956,162.490875,173.255432,72.569031,4.524243,27.723644,-0.255957,2.442192,4.760604,91.344040,102.032227,0.392565,0.564464,0.008139,0.004504,0.001947,0.000460,0.005333,-0.002887
4,5,1999-04-01,4.44,5.01,5.27,5.67,88.4295,0.00,165.9,176.3,73.365,4.3,22.06,-0.40,2.32,4.74,94.786,104.6,0.26,0.83,0.007933,0.010843,0.002815,-0.009967,0.006497,-0.091813,1999-05-01,4.601812,4.624525,4.893676,5.359653,85.881470,0.296441,163.268845,173.855499,72.342697,4.611393,28.412798,-0.282059,2.271957,4.954602,91.602013,102.949005,0.260284,0.401356,0.007821,0.005140,0.002126,-0.016305,0.006810,-0.008688,1999-06-01,4.514317,4.687757,4.841167,5.404416,85.833565,0.229949,163.184525,173.772049,72.529427,4.504437,28.437902,-0.283570,2.349463,4.961543,91.151474,102.635841,0.297709,0.361683,0.008494,0.005228,0.001955,-0.005874,0.005711,0.010843,1999-07-01,4.577456,4.658329,5.123849,5.415531,85.522728,0.160238,163.444397,173.808014,72.783112,4.468940,26.354599,-0.276484,2.348063,4.878546,91.863686,102.866112,0.298198,0.524226,0.007967,0.005901,0.001978,-0.002472,0.005842,-0.008902
5,6,1999-05-01,4.55,5.08,5.36,5.68,88.9886,0.56,166.0,176.5,73.435,4.2,25.07,-0.43,2.22,4.74,95.345,106.8,0.28,0.81,0.007051,0.005258,0.001695,-0.006711,0.005536,0.037347,1999-06-01,4.558164,4.870742,5.084829,5.496082,85.018616,0.183227,162.189224,173.388489,72.402550,4.567470,26.991695,-0.327506,2.234580,4.767649,91.053154,102.751564,0.310978,0.537873,0.006411,0.004912,0.001957,-0.003775,0.005913,0.012561,1999-07-01,4.631545,4.884727,5.109970,5.549382,85.074898,0.137777,162.776184,173.512985,72.546440,4.546033,25.685226,-0.313845,2.273586,4.864557,91.636253,102.607300,0.323048,0.582162,0.007645,0.004879,0.002082,-0.001061,0.005665,0.000478,1999-08-01,4.571271,4.940492,5.234138,5.565250,86.018837,0.255786,162.802017,173.951584,72.465012,4.523728,25.670578,-0.359822,2.235206,4.807332,91.900627,104.296722,0.361522,0.658299,0.005760,0.005299,0.002072,-0.007499,0.005159,-0.000957
6,7,1999-06-01,4.77,5.54,5.78,5.94,88.9188,-0.08,166.0,176.6,73.474,4.3,26.62,-0.40,2.12,4.76,95.975,107.3,0.24,1.01,0.003873,0.004525,0.002104,0.023649,0.004882,-0.032278,1999-07-01,4.668368,4.983998,5.101302,5.437783,87.822670,0.231632,164.447205,175.780869,73.211716,4.347521,28.538113,-0.315650,2.206438,5.004874,92.835678,104.870514,0.178234,0.394450,0.005680,0.005879,0.002178,-0.015214,0.006307,-0.000695,1999-08-01,4.692521,4.936676,5.063765,5.460372,88.028648,0.203633,165.039322,176.178528,73.387825,4.227097,28.528072,-0.269549,2.232096,4.902520,92.764793,106.153671,0.120270,0.416423,0.006283,0.005413,0.002050,-0.010022,0.006199,0.005200,1999-09-01,4.640961,5.012201,5.077514,5.439497,88.270004,0.244908,165.441650,176.245102,73.479904,4.268983,28.173624,-0.289471,2.256561,4.882752,93.409180,105.561249,0.183076,0.492272,0.006468,0.005827,0.002183,-0.000523,0.005922,-0.003025
7,8,1999-07-01,4.68,5.58,5.85,6.02,89.4333,0.18,166.7,177.1,73.606,4.3,19.69,-0.33,2.13,4.99,96.591,106.0,0.27,1.17,0.007757,0.004361,0.002618,-0.039604,0.006078,0.070558,1999-08-01,4.666333,4.862982,5.015725,5.431580,87.262093,0.226213,164.242523,175.352478,73.021790,4.359934,28.348412,-0.278054,2.242311,5.084532,92.686165,104.713081,0.176424,0.399888,0.006783,0.005536,0.002024,-0.009015,0.006594,0.000800,1999-09-01,4.598229,4.853188,5.047749,5.409646,87.371994,0.172855,164.304321,175.173569,73.125893,4.337072,28.403757,-0.283437,2.281080,5.001924,93.029633,104.279030,0.200627,0.434974,0.006780,0.005582,0.001982,-0.008002,0.006351,0.000812,1999-10-01,4.582137,4.852293,5.071276,5.395645,87.670593,0.214278,164.516739,175.580078,73.062965,4.366404,27.008055,-0.279229,2.343060,4.926268,93.630653,104.556526,0.211302,0.502407,0.007357,0.005512,0.002107,-0.007693,0.006618,0.003171
8,9,1999-08-01,4.75,5.63,5.92,6.11,89.7924,0.34,167.1,177.3,73.642,4.2,24.64,-0.21,2.19,5.07,97.218,104.5,0.29,1.17,0.010272,0.007046,0.001159,0.030928,0.003814,-0.012582,1999-09-01,4.771297,5.087634,5.418662,5.681295,86.811974,0.140881,163.548965,174.580399,72.775520,4.370546,25.078516,-0.368386,2.089203,4.929540,92.220978,104.958832,0.216897,0.712104,0.004922,0.005363,0.002137,0.007486,0.005624,-0.006518,1999-10-01,4.830436,5.193201,5.459966,5.801144,86.907204,0.163487,164.113739,174.561264,72.822845,4.386990,24.451658,-0.372984,2.034621,4.962785,92.523468,106.108223,0.188444,0.669416,0.006061,0.005813,0.002020,0.003452,0.005078,-0.001236,1999-11-01,4.859680,5.308102,5.538219,5.835736,86.908562,0.220317,164.062653,174.199051,72.959831,4.383671,24.591623,-0.394864,2.109330,5.059995,93.656837,106.228752,0.180002,0.826812,0.008257,0.006030,0.002030,-0.005730,0.005189,0.000209
9,10,1999-09-01,4.97,5.74,5.99,6.08,89.4299,-0.19,167.8,177.8,73.837,4.2,22.93,-0.15,2.23,5.22,97.862,107.2,0.25,1.02,0.004668,0.008623,0.001536,-0.033333,0.003536,-0.007888,1999-10-01,4.829230,5.370418,5.684987,5.874730,89.281563,0.244746,165.596558,175.551590,73.085739,4.262193,26.476913,-0.358341,2.130630,5.119467,92.616463,106.423286,0.155533,0.913821,0.004482,0.005485,0.002021,-0.004643,0.005553,-0.012159,1999-11-01,4.786964,5.345716,5.674096,5.879716,89.019463,0.156310,166.539764,176.196701,73.443871,4.236701,26.718798,-0.323814,2.145948,5.076209,93.768806,105.853088,0.217624,0.852606,0.005318,0.005472,0.001920,0.004392,0.005901,-0.007514,1999-12-01,4.804514,5.398248,5.620445,5.828408,89.022614,0.218796,166.221848,177.032883,73.794548,4.239909,27.009336,-0.281794,2.103211,5.033583,95.144257,106.299454,0.174610,0.905676,0.007547,0.005754,0.001970,-0.008443,0.005506,0.004645

In [35]:
lstm_macro_features["date_t0"] = pd.to_datetime(lstm_macro_features["date_t0"])

In [36]:
lstm_macro_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327 entries, 0 to 326
Columns: 101 entries, iteracion to housing_starts_mom_pred_t3
dtypes: datetime64[ns](4), float32(72), float64(24), int64(1)
memory usage: 166.2 KB

In [37]:
lstm_macro_features.columns

Index(['iteracion', 'date_t0', 'rate_3m_t0', 'rate_2y_t0', 'rate_10y_t0',
       'rate_30y_t0', 'industrial_production_t0', 'cfnai_t0', 'cpi_t0',
       'core_cpi_t0',
       ...
       'house_price_index_pred_t3', 'consumer_sentiment_pred_t3',
       'spread_10y_2y_pred_t3', 'spread_10y_3m_pred_t3',
       'retail_sales_mom_pred_t3', 'pce_mom_pred_t3', 'payrolls_mom_pred_t3',
       'jobless_claims_mom_pred_t3', 'm2_mom_pred_t3',
       'housing_starts_mom_pred_t3'],
      dtype='object', length=101)

In [38]:
"""

print(df_fundamentals["acceptedDate"].dtype)
print(lstm_macro_features["date_t0"].dtype)

print(df_fundamentals["acceptedDate"].head(10))
print(lstm_macro_features["date_t0"].head(10))

print(df_fundamentals["acceptedDate"].min(), df_fundamentals["acceptedDate"].max())
print(lstm_macro_features["date_t0"].min(), lstm_macro_features["date_t0"].max())

"""

'\n\nprint(df_fundamentals["acceptedDate"].dtype)\nprint(lstm_macro_features["date_t0"].dtype)\n\nprint(df_fundamentals["acceptedDate"].head(10))\nprint(lstm_macro_features["date_t0"].head(10))\n\nprint(df_fundamentals["acceptedDate"].min(), df_fundamentals["acceptedDate"].max())\nprint(lstm_macro_features["date_t0"].min(), lstm_macro_features["date_t0"].max())\n\n'

In [39]:
import pandas as pd

fund = df_fundamentals.copy()
macro = lstm_macro_features.copy()

fund["acceptedDate"] = pd.to_datetime(fund["acceptedDate"], errors="coerce")
macro["date_t0"] = pd.to_datetime(macro["date_t0"], errors="coerce")

# si no querés trabajar con horas
fund["acceptedDate"] = fund["acceptedDate"].dt.normalize()
macro["date_t0"] = macro["date_t0"].dt.normalize()

fund = fund.sort_values("acceptedDate")
macro = macro.sort_values("date_t0")

df_merged = pd.merge_asof(
    fund,
    macro,
    left_on="acceptedDate",
    right_on="date_t0",
    direction="backward"
)

In [40]:
df_merged = df_merged.rename(columns={
    "date": "date_fundamentals"
})

In [41]:
df_merged.tail(10)

,grossProfitMargin,ebitMargin,ebitdaMargin,operatingProfitMargin,pretaxProfitMargin,continuousOperationsProfitMargin,netProfitMargin,bottomLineProfitMargin,receivablesTurnover,payablesTurnover,inventoryTurnover,fixedAssetTurnover,assetTurnover,currentRatio,quickRatio,solvencyRatio,cashRatio,priceToEarningsRatio,priceToEarningsGrowthRatio,forwardPriceToEarningsGrowthRatio,priceToBookRatio,priceToSalesRatio,priceToFreeCashFlowRatio,priceToOperatingCashFlowRatio,debtToAssetsRatio,debtToEquityRatio,debtToCapitalRatio,longTermDebtToCapitalRatio,financialLeverageRatio,workingCapitalTurnoverRatio,operatingCashFlowRatio,operatingCashFlowSalesRatio,freeCashFlowOperatingCashFlowRatio,debtServiceCoverageRatio,interestCoverageRatio,shortTermOperatingCashFlowCoverageRatio,operatingCashFlowCoverageRatio,capitalExpenditureCoverageRatio,dividendPaidAndCapexCoverageRatio,dividendPayoutRatio,dividendYield,dividendYieldPercentage,netIncomePerEBT,ebtPerEbit,priceToFairValue,debtToMarketCap,evToSales,evToOperatingCashFlow,evToFreeCashFlow,evToEBITDA,netDebtToEBITDA,incomeQuality,taxBurden,interestBurden,returnOnAssets,operatingReturnOnAssets,returnOnTangibleAssets,returnOnEquity,returnOnInvestedCapital,returnOnCapitalEmployed,earningsYield,freeCashFlowYield,capexToOperatingCashFlow,capexToDepreciation,capexToRevenue,salesGeneralAndAdministrativeToRevenue,researchAndDevelopementToRevenue,stockBasedCompensationToRevenue,intangiblesToTotalAssets,freeCashFlowToEquity,freeCashFlowToFirm,c_grossProfit_to_revenue,c_ebitda_to_revenue,c_ebit_to_revenue,c_operatingIncome_to_revenue,c_incomeBeforeTax_to_revenue,c_netIncome_to_revenue,c_bottomLineNetIncome_to_revenue,c_netIncomeFromContinuingOperations_to_revenue,c_costOfRevenue_to_revenue,c_operatingExpenses_to_revenue,c_costAndExpenses_to_revenue,c_researchAndDevelopmentExpenses_to_revenue,c_generalAndAdministrativeExpenses_to_revenue,c_sellingAndMarketingExpenses_to_revenue,c_sellingGeneralAndAdministrativeExpenses_to_revenue,c_depreciationAndAmortization_to_revenue,c_interestExpense_to_revenue,c_incomeTaxExpense_to_revenue,c_stockBasedCompensation_to_revenue,c_otherExpenses_to_revenue,c_nonOperatingIncomeExcludingInterest_to_revenue,c_totalOtherIncomeExpensesNet_to_revenue,c_revenue_to_totalAssets,c_grossProfit_to_totalAssets,c_ebitda_to_totalAssets,c_ebit_to_totalAssets,c_operatingIncome_to_totalAssets,c_netIncome_to_totalAssets,c_operatingCashFlow_to_totalAssets,c_freeCashFlow_to_totalAssets,c_netIncome_to_totalEquity,c_operatingIncome_to_totalEquity,c_totalDebt_to_totalEquity,c_totalLiabilities_to_totalEquity,c_netDebt_to_totalEquity,c_netIncome_to_investedCapital,c_operatingIncome_to_investedCapital,c_ebit_to_investedCapital,c_netIncome_to_tangibleAssetValue,c_operatingIncome_to_tangibleAssetValue,c_totalDebt_to_totalAssets,c_totalLiabilities_to_totalAssets,c_netDebt_to_totalAssets,c_longTermDebt_to_totalAssets,c_shortTermDebt_to_totalAssets,c_longTermDebt_to_totalDebt,c_shortTermDebt_to_totalDebt,c_totalDebt_to_capital,c_longTermDebt_to_capital,c_cashAndCashEquivalents_to_totalDebt,c_cashAndShortTermInvestments_to_totalDebt,c_cashAndCashEquivalents_to_totalAssets,c_cashAndShortTermInvestments_to_totalAssets,c_workingCapital_to_totalAssets,c_workingCapital_to_revenue,c_investedCapital_to_totalAssets,c_totalCurrentAssets_to_totalCurrentLiabilities,c_cashAndCashEquivalents_to_totalCurrentLiabilities,c_cashAndShortTermInvestments_to_totalCurrentLiabilities,c_netReceivables_to_totalCurrentLiabilities,c_inventory_to_totalCurrentAssets,c_netReceivables_to_totalCurrentAssets,c_otherCurrentAssets_to_totalCurrentAssets,c_prepaids_to_totalCurrentAssets,c_totalCurrentAssets_to_totalAssets,c_totalNonCurrentAssets_to_totalAssets,c_propertyPlantEquipmentNet_to_totalAssets,c_inventory_to_totalAssets,c_netReceivables_to_totalAssets,c_goodwill_to_totalAssets,c_intangibleAssets_to_totalAssets,c_goodwillAndIntangibleAssets_to_totalAssets,c_longTermInvestments_to_totalAssets,c_totalInvestments_to_totalAssets,c_totalCurrentLiabilities_to_totalLiabilities,c_totalNonCurrentLiabilities_to_totalLiabilities,c_accountPayables_to_totalLiabilities,c_totalPayables_to_totalLiabilities,c_shortTermDebt_to_totalLiabilities,c_longTermDebt_to_totalLiabilities,c_revenue_to_averageReceivables,c_costOfRevenue_to_averagePayables,c_costOfRevenue_to_averageInventory,c_revenue_to_propertyPlantEquipmentNet,c_revenue_to_workingCapital,c_operatingCashFlow_to_revenue,c_freeCashFlow_to_revenue,c_operatingCashFlow_to_totalDebt,c_freeCashFlow_to_totalDebt,c_operatingCashFlow_to_totalCurrentLiabilities,c_operatingCashFlow_to_netIncome,c_freeCashFlow_to_netIncome,c_freeCashFlow_to_operatingCashFlow,c_ebit_to_interestExpense,c_operatingIncome_to_interestExpense,c_operatingCashFlow_to_interestExpense,c_capitalExpenditure_to_operatingCashFlow,c_investmentsInPropertyPlantAndEquipment_to_operatingCashFlow,c_netDividendsPaid_to_operatingCashFlow,c_commonDividendsPaid_to_operatingCashFlow,c_dividendsPaid_plus_capex_to_operatingCashFlow,c_incomeTaxExpense_to_incomeBeforeTax,c_netIncome_to_incomeBeforeTax,c_incomeBeforeTax_to_ebit,c_operatingCashFlow_to_netIncome_quality,c_marketCap_to_revenue,c_marketCap_to_operatingCashFlow,c_marketCap_to_freeCashFlow,c_marketCap_to_netIncome,c_revenue_to_marketCap,c_operatingCashFlow_to_marketCap,c_freeCashFlow_to_marketCap,c_netIncome_to_marketCap,c_totalEquity_to_marketCap,c_totalDebt_to_marketCap,c_netDebt_to_marketCap,c_enterpriseValue_to_revenue,c_enterpriseValue_to_operatingCashFlow,c_enterpriseValue_to_freeCashFlow,c_enterpriseValue_to_ebitda,c_enterpriseValue_to_ebit,c_stockPrice_to_eps,c_stockPrice_to_bookValuePerShare,c_stockPrice_to_revenuePerShare,c_stockPrice_to_operatingCashFlowPerShare,c_stockPrice_to_freeCashFlowPerShare,c_dividendPerShare_to_stockPrice,c_netDividendsPaid_to_netIncome,c_commonDividendsPaid_to_netIncome,c_netDividendsPaid_to_freeCashFlow,c_commonDividendsPaid_to_freeCashFlow,c_netDividendsPaid_to_marketCap,c_commonDividendsPaid_to_marketCap,c_revenue_to_weightedAverageShsOut,c_netIncome_to_weightedAverageShsOut,c_operatingCashFlow_to_weightedAverageShsOut,c_freeCashFlow_to_weightedAverageShsOut,c_totalEquity_to_weightedAverageShsOut,c_cashAndCashEquivalents_to_weightedAverageShsOut,symbol,date_fundamentals,acceptedDate,exchange,industry,sector,country,ipoDate,isEtf,isActivelyTrading,isAdr,isFund,iteracion,date_t0,rate_3m_t0,rate_2y_t0,rate_10y_t0,rate_30y_t0,industrial_production_t0,cfnai_t0,cpi_t0,core_cpi_t0,core_pce_t0,unemployment_t0,vix_t0,nfci_t0,baa_10y_t0,fed_funds_t0,house_price_index_t0,consumer_sentiment_t0,spread_10y_2y_t0,spread_10y_3m_t0,retail_sales_mom_t0,pce_mom_t0,payrolls_mom_t0,jobless_claims_mom_t0,m2_mom_t0,housing_starts_mom_t0,date_pred_t1,rate_3m_pred_t1,rate_2y_pred_t1,rate_10y_pred_t1,rate_30y_pred_t1,industrial_production_pred_t1,cfnai_pred_t1,cpi_pred_t1,core_cpi_pred_t1,core_pce_pred_t1,unemployment_pred_t1,vix_pred_t1,nfci_pred_t1,baa_10y_pred_t1,fed_funds_pred_t1,house_price_index_pred_t1,consumer_sentiment_pred_t1,spread_10y_2y_pred_t1,spread_10y_3m_pred_t1,retail_sales_mom_pred_t1,pce_mom_pred_t1,payrolls_mom_pred_t1,jobless_claims_mom_pred_t1,m2_mom_pred_t1,housing_starts_mom_pred_t1,date_pred_t2,rate_3m_pred_t2,rate_2y_pred_t2,rate_10y_pred_t2,rate_30y_pred_t2,industrial_production_pred_t2,cfnai_pred_t2,cpi_pred_t2,core_cpi_pred_t2,core_pce_pred_t2,unemployment_pred_t2,vix_pred_t2,nfci_pred_t2,baa_10y_pred_t2,fed_funds_pred_t2,house_price_index_pred_t2,consumer_sentiment_pred_t2,spread_10y_2y_pred_t2,spread_10y_3m_pred_t2,retail_sales_mom_pred_t2,pce_mom_pred_t2,payrolls_mom_pred_t2,jobless_claims_mom_pred_t2,m2_mom_pred_t2,housing_starts_mom_pred_t2,date_pred_t3,rate_3m_pred_t3,rate_2y_pred_t3,rate_10y_pred_t3,rate_30y_pred_t3,industrial_production_pred_t3,cfnai_pred_t3,cpi_pred_t3,core_cpi_pred_t3,core_pce_pred_t3,unemployment_pred_t3,vix_pred_t3,nfci_pred_t3,baa_10y_pred_t3,fed_funds_pred_t3,house_price_index_pred_t3,consumer_sentiment_pred_t3,spread_10y_2y_pred_t3,spread_10y_3m_pred_t3,retail_sales_mom_pred_t3,pce_mom_pred_t3,payrolls_mom_pred_t3,jobless_claims_mom_pred_t3,m2_mom_pred_t3,housing_starts_mom_pred_t3
638347,0.329439,0.044036,0.084606,0.086917,-0.006163,-0.004365,-0.004365,-0.004365,2.089324,1.279206,0.724712,1.525460,0.175286,1.993239,1.073861,0.006555,0.274015,-100.035000,0.911521,0.911521,9.628280,1.746663,10.953913,9.100174,0.789472,24.827318,0.961281,0.960111,31.447983,0.936910,0.190713,0.191937,0.830769,1.053208,1.731458,6.028226,0.042616,5.909091,3.076132,-6.852941,0.017126,1.712636,0.708333,-0.070901,9.628280,2.518089,5.974805,31.128936,37.470016,70.618756,49.974203,-43.970588,0.708333,-0.139942,-0.000765,0.015044,-0.001416,-0.024062,0.013015,0.018499,-0.002499,0.091292,0.169231,0.800633,0.032482,0.000000,0.010014,0.011170,0.459740,-3.169100e+09,1.360958e+08,0.329439,0.127744,0.000000,0.127744,-0.006163,-0.004365,0.000000,0.000000,0.670561,0.201695,0.872256,0.010014,0.000000,0.063166,0.191681,0.000000,0.050199,-0.001797,NaN,0.000000,0.000000,-0.133907,0.175286,0.057746,0.022392,0.000000,0.022392,-0.000765,NaN,NaN,-0.024062,0.704176,24.234961,30.447983,22.714791,-0.001020,0.029861,0.000000,0.001788,-0.052324,0.770636,0.968201,0.722297,0.765370,0.005266,0.993167,0.006833,1.027700,1.020678,0.062726,0.062726,0.048339,0.048339,0.175218,0.999615,0.749865,1.993239,0.274015,0.274015,0.000000,0.461248,0.000000,0.401280,0.000000,0.351629,0.648371,0.114907,0.162188,0.000000,0.236587,0.223152,0.459740,0.000000,0.000000,0.182205,0.817795,0.094903,0.094903,0.005439,0.790507,1.707178,1.288834,0.695519,1.525460,1.000385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.544757,NaN,NaN,NaN,NaN,NaN,NaN,0.291667,0.708333,NaN,NaN,1.746663,NaN,NaN,-400.140000,0.572520,NaN,NaN,-0.002499,0.103861,2.517060,2.359174,5.974805,NaN,NaN,46.771618,NaN,-397.800000,9.628280,1.746663,9.100174,10.953913,0.017126,NaN,NaN,NaN,NaN,NaN,NaN,11.387427,-0.049708,NaN,NaN,2.065789,3.140351,ENR-PA,2025-12-31,2026-02-05,NYSE,Electrical Equipment & Parts,Industrials,US,2019-01-16,False,False,False,False,327.0,2026-02-01,3.67,3.52,4.26,4.87,102.344,0.03,327.46,333.512,128.901,4.4,17.44,-0.56,1.62,3.64,332.098,56.6,0.74,0.59,0.007174,0.006485,-0.000984,0.133005,0.008828,-0.030043,2026-03-01,3.752332,3.412838,3.765364,4.130352,101.046028,-0.04757,322.004974,327.622894,125.780365,4.086506,19.727106,-0.50208,1.614429,3.693112,339.878754,58.183315,0.350892,0.021149,0.004135,0.005728,0.001019,-0.020021,0.002653,0.011689,2026-04-01,3.706919,3.441358,3.804044,4.174387,101.201828,-0.061567,322.995972,328.772827,126.189911,4.066164,20.239012,-0.478878,1.621612,3.645522,341.213623,57.692722,0.356942,0.069821,0.00427,0.005767,0.000908,0.008727,0.00266,-0.004749,2026-05-01,3.722919,3.476256,3.859735,4.241346,101.412086,-0.040511,324.196594,329.490082,126.621384,3.947323,19.818506,-0.485549,1.618988,3.630307,341.977966,57.083374,0.379677,0.133335,0.003928,0.005999,0.00128,-0.105735,0.002574,0.000266
638348,0.198677,0.020881,0.020881,0.020881,0.001034,-0.005582,0.012818,0.010957,1.832891,1.434493,1.561015,1.303422,0.130062,1.199466,0.850436,0.016954,0.218583,178.803742,-2.046746,-2.046746,3.212354,9.167527,50.275882,43.774263,0.340656,0.917777,0.478563,0.460507,2.694147,3.852648,0.142395,0.209427,0.870681,0.146809,50.500000,2.164530,0.079959,7.732824,3.165625,3.048387,0.004262,0.426220,12.400000,0.049505,3.212354,0.276276,11.465232,54.745635,62.876789,549.082455,110.039604,16.338710,12.400000,0.049505,0.001667,0.002684,0.004036,0.004491,-0.017856,0.003358,0.001398,0.019890,0.129319,0.398176,0.027083,0.000000,0.033078,0.003928,0.586905,-9.814000e+09,-6.744000e+08,0.198677,0.020881,0.020881,0.020881,0.001034,0.012818,0.010957,-0.005582,0.801323,0.177796,0.979119,0.033078,0.000000,0.000000,0.154435,0.000000,0.000413,0.006616,NaN,-0.009717,0.000000,-0.019847,0.130062,0.025840,0.002716,0.002716,0.002716,0.001667,NaN,NaN,0.004388,0.007149,0.867143,1.632361,0.757078,0.002300,0.003747,0.003747,-0.008053,-0.013119,0.329417,0.620113,0.287604,0.316832,0.012584,0.961799,0.038201,0.454465,0.437104,0.126928,0.126928,0.041812,0.041812,0.038155,0.293364,0.724845,1.199466,0.218583,0.218583,0.370959,0.290988,0.309270,0.217508,0.000000,0.229443,0.770557,0.099785,0.066765,0.070960,0.416806,0.170099,0.586905,0.035520,0.035520,0.308473,0.691527,0.117162,0.117162,0.020293,0.510927,1.677184,1.369369,1.412794,1.303422,3.408739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.5,50.500000,NaN,NaN,NaN,NaN,NaN,NaN,6.400000,12.400000,0.049505,NaN,9.167527,NaN,NaN,715.214968,0.109081,NaN,NaN,0.001398,0.318605,0.276276,0.241209,11.465232,NaN,NaN,549.082455,549.082455,1761.333333,3.138684,9.167527,43.774263,50.275882,0.004262,NaN,NaN,NaN,NaN,NaN,NaN,5.763823,0.073880,NaN,NaN,16.835081,1.852955,CARR,2025-12-31,2026-02-05,NYSE,Construction,Industrials,US,2020-03-19,False,True,False,False,327.0,2026-02-01,3.67,3.52,4.26,4.87,102.344,0.03,327.46,333.512,128.901,4.4,17.44,-0.56,1.62,3.64,332.098,56.6,0.74,0.59,0.007174,0.006485,-0.000984,0.133005,0.008828,-0.030043,2026-03-01,3.752332,3.412838,3.765364,4.130352,101.046028,-0.04757,322.004974,327.622894,125.780365,4.086506,19.727106,-0.50208,1.614429,3.693112,339.878754,58.183315,0.350892,0.021149,0.004135,0.005728,0.001019,-0.020021,0.002653,0.011689,2026-04-01,3.706919,3.441358,3.804044,4.174387,101.201828,-0.061567,322.995972,328.772827,126.189911,4.066164,20.239012,-0.478878,1.621612,3.645522,341.213623,57.692722,0.356942,0.069821,0.00427,0.005767,0.000908,0.008727,0.00266,-0.004749,2026-05-01,3.722919,3.476256,3.859735,4.241346,101.412086,-0.040511,324.196594,329.490082,126.621384,3.947323,19.818506,-0.485549,1.618988,3.630307,341.977966,57.083374,0.379677,0.133335,0.003928,0.005999,0.00128,-0.105735,0.002574,0.000266
638349,0.397314,0.221620,0.292894,0.228553,0.193458,0.146014,0.146014,0.146014,1.615115,1.963303,0.355982,0.970359,0.089778,1.859842,0.669257,0.053337,0.163924,53.355698,4.223993,4.223993,4.410995,31.162687,145.153342,117.810780,0.215011,0.338996,0.253172,0.187285,1.576646,0.667727,0.186015,0.264515,0.811630,0.357301,8.115385,0.401513,0.110448,5.308696,5.308696,0.000000,0.000000,0.000000,0.754759,0.846445,4.410995,0.073384,33.324515,125.983589,155.222969,113.776599,7.380917,1.811573,0.754759,0.872923,0.013109,0.020581,0.038339,0.020668,0.016626,0.023522,0.004686,0.006889,0.188370,0.699088,0.049827,0.000000,0.000000,0.020147,0.658083,-8.988000e+08,3.409119e+08,0.442808,0.223137,0.000000,0.223137,0.193458,0.146014,0.000000,0.000000,0.557192,0.219671,0.776863,0.000000,0.000000,0.000000,0.168761,0.000000,0.028163,0.047444,NaN,0.050910,0.000000,-0.029679,0.089778,0.039754,0.020033,0.000000,0.020033,0.013109,NaN,NaN,0.020668,0.031584,0.106804,0.576646,0.073809,0.015236,0.023284,0.000000,-0.550204,-0.840816,0.067742,0.365742,0.046814,0.009705,0.058036,0.143267,0.856733,0.078735,0.011280,0.308929,0.308929,0.020927,0.020927,0.109771,1.222704,0.860374,1.859842,0.163924,0.163924,0.435405,0.640154,0.234109,0.037598,0.000000,0.237436,0.762564,0.092520,0.151995,0.055586,0.386592,0.271491,0.658083,0.000000,0.000000,0.349056,0.650944,0.075352,0.075352,0.158681,0.026535,1.633982,1.799860,0.331828,0.970359,0.817860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.923077,NaN,NaN,NaN,NaN,NaN,NaN,0.245241,0.754759,NaN,NaN,31.162687,NaN,NaN,213.422792,0.032090,NaN,NaN,0.004686,0.226706,0.024213,0.016733,33.324515,NaN,NaN,149.345594,NaN,213.238318,4.410995,31.162687,117.810780,145.153342,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,14.643474,2.138150,NaN,NaN,103.452846,3.413427,RBCP,2025-12-27,2026-02-05,NYSE,Manufacturing - Tools & Accessories,Industrials,US,2021-09-22,False,False,False,False,327.0,2026-02-01,3.67,3.52,4.26,4.87,102.344,0.03,327.46,333.512,128.901,4.4,17.44,-0.56,1.62,3.64,332.098,56.6,0.74,0.59,0.007174,0.006485,-0.000984,0.133005,0.008828,-0.030043,2026-03-01,3.752332,3.412838,3.765364,4.130352,101.046028,-0.04757,322.004974,327.622894,125.780365,4.086506,19.727106,-0.50208,1.614429,3.693112,339.878754,58.183315,0.350892,0.021149,0.004135,0.005728,0.001019,-0.020021,0.002653,0.011689,2026-04-01,3.706919,3.441358,3.804044,4.174387,101.201828,-0.061567,322.995972,328.772827,126.189911,4.066164,20.239012,-0.478878,1.621612,3.645522,341.213623,57.692722,0.356942,0.069821,0.00427,0.005767,0.000908,0.008727,0.00266,-0.004749,2026-05-01,3.722919,3.476256,3.859735,4.241346,101.412086,-0.040511,324.196594,329.490082,126.621384,3.947323,19.818506,-0.485549,1.618988,3.630307,341.977966,57.083374,0.379677,0.133335,0.003928,0.005999,0.00128,-0.105735,0.002574,0.000266
638350,0.202899,0.038647,0.078173,0.071146,0.028986,-0.035573,-0.034256,-0.034256,1.338624,2.184116,1.008894,0.892241,0.201665,2.418953,1.671239,0.002415,0.645054,-18.235000,0.062683,0.062683,0.899924,2.498603,12.053644,9.929005,0.253388,0.452547,0.311554,0.258938,1.785985,0.658854,0.238155,0.251647,0.823735,0.202614,7.363636,4.374046,0.200280,5.673267,4.476562,-0.346154,0.004746,0.474573,-1.181818,0.407407,0.899924,0.411297,3.073483,12.213473,14.826949,39.763182,7.437500,-7.074074,-1.181818,0.750000,-0.006908,0.000619,-0.008429,-0.012338,-0.000953,0.000788,-0.013710,0.082962,0.176265,1.122222,0.044357,0.000000,0.000000,0.000000,0.180409,-3.160000e+08,-3.700000e+07,0.202899,0.040404,0.000000,-0.027668,0.028986,-0.034256,0.000000,0.000000,0.797101,0.131752,0.928854,0.000000,0.000000,0.000000,0.131752,0.000000,-0.001318,0.064559,NaN,0.000000,0.000000,0.056653,0.201665,0.040918,0.008148,0.000000,-0.005580,-0.006908,NaN,NaN,-0.012338,-0.009965,0.370136,0.785985,0.124644,-0.009746,-0.007872,0.000000,-0.018203,-0.014702,0.207245,0.440085,0.069790,0.195643,0.011602,0.944017,0.055983,0.292390,0.276021,0.663248,0.663248,0.137455,0.137455,0.302365,1.499341,0.708795,2.418953,0.645054,0.645054,0.706983,0.309107,0.292268,0.131959,0.000000,0.515455,0.484545,0.226021,0.159330,0.150651,0.180409,0.000000,0.180409,0.000000,0.000000,0.484202,0.515798,0.167237,0.167237,0.026363,0.444556,1.097878,2.228361,0.985075,0.892241,0.666960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-21.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.227273,-1.181818,NaN,NaN,2.498603,NaN,NaN,-72.940000,0.400224,NaN,NaN,-0.013710,1.111205,0.411297,0.138505,3.073483,NaN,NaN,76.068696,NaN,-74.428571,0.899924,2.498603,9.929005,12.053644,0.004746,NaN,NaN,NaN,NaN,NaN,NaN,6.255495,-0.214286,NaN,NaN,17.368132,4.263736,NOV,2025-12-31,2026-02-05,NYSE,Oil & Gas Equipment & Services,Energy,US,1996-10-29,False,True,False,False,327.0,2026-02-01,3.67,3.52,4.26,4.87,102.344,0.03,327.46,333.512,128.901,4.4,17.44,-0.56,1.62,3.64,332.098,56.6,0.74,0.59,0.007174,0.006485,-0.000984,0.133005,0.008828,-0.030043,2026-03-01,3.752332,3.412838,3.765364,4.130352,101.046028,-0.04757,322.004974,327.622894,125.780365,4.086506,19.727106,-0.50208,1.614429,3.693112,339.878754,58.183315,0.350892,0.021149,0.004135,0.005728,0.001019,-0.020021,0.002653,0.011689,2026-04-01,3.706919,3.441358,3.804044,4.174387,101.201828,-0.061567,322.995972,328.772827,126.189911,4.066164,20.239012,-0.478878,1.621612,3.645522,341.213623,57.692722,0.356942,0.069821,0.00427,0.005767,0.000908,0.008727,0.00266,-0.004749,2026-05-01,3.722919,3.476256,3.859735,4.241346,101.412086,-0.040511,324.196594,329.490082,126.621384,3.947323,19.818506,-0.485549,1.618988,3.630307,341.977966,57.083374,0.379677,0.133335,0.003928,0.005999,0.00128,-0.105735,0.002574,0.000266

In [42]:
revisar_nulos(df_merged)

,column,dtype,NaN,None,Null_string,Empty_string,Zero
0,grossProfitMargin,float64,0,0,0,0,66662
1,ebitMargin,float64,0,0,0,0,100775
2,ebitdaMargin,float64,0,0,0,0,74364
3,operatingProfitMargin,float64,0,0,0,0,63800
4,pretaxProfitMargin,float64,0,0,0,0,93709
5,continuousOperationsProfitMargin,float64,0,0,0,0,66548
6,netProfitMargin,float64,0,0,0,0,64521
7,bottomLineProfitMargin,float64,0,0,0,0,64968
8,receivablesTurnover,float64,0,0,0,0,143427
9,payablesTurnover,float64,0,0,0,0,220048
10,inventoryTurnover,float64,0,0,0,0,339907
11,fixedAssetTurnover,float64,0,0,0,0,149399
12,assetTurnover,float64,0,0,0,0,90430
13,currentRatio,float64,0,0,0,0,65113
14,quickRatio,float64,0,0,0,0,65145
15,solvencyRatio,float64,0,0,0,0,41220
16,cashRatio,float64,0,0,0,0,71547
17,priceToEarningsRatio,float64,0,0,0,0,19446
18,priceToEarningsGrowthRatio,float64,0,0,0,0,62199
19,forwardPriceToEarningsGrowthRatio,float64,0,0,0,0,62199
20,priceToBookRatio,float64,0,0,0,0,48698
21,priceToSalesRatio,float64,0,0,0,0,72183
22,priceToFreeCashFlowRatio,float64,0,0,0,0,64173
23,priceToOperatingCashFlowRatio,float64,0,0,0,0,64060
24,debtToAssetsRatio,float64,0,0,0,0,126886
25,debtToEquityRatio,float64,0,0,0,0,126717
26,debtToCapitalRatio,float64,0,0,0,0,126285
27,longTermDebtToCapitalRatio,float64,0,0,0,0,200183
28,financialLeverageRatio,float64,0,0,0,0,39076
29,workingCapitalTurnoverRatio,float64,0,0,0,0,110670
30,operatingCashFlowRatio,float64,0,0,0,0,88152
31,operatingCashFlowSalesRatio,float64,0,0,0,0,104731
32,freeCashFlowOperatingCashFlowRatio,float64,0,0,0,0,54689
33,debtServiceCoverageRatio,float64,0,0,0,0,151397
34,interestCoverageRatio,float64,0,0,0,0,245105
35,shortTermOperatingCashFlowCoverageRatio,float64,0,0,0,0,281702
36,operatingCashFlowCoverageRatio,float64,0,0,0,0,145644
37,capitalExpenditureCoverageRatio,float64,0,0,0,0,157750
38,dividendPaidAndCapexCoverageRatio,float64,0,0,0,0,110796
39,dividendPayoutRatio,float64,0,0,0,0,337756
40,dividendYield,float64,0,0,0,0,341670
41,dividendYieldPercentage,float64,0,0,0,0,341670
42,netIncomePerEBT,float64,0,0,0,0,40880
43,ebtPerEbit,float64,0,0,0,0,42936
44,priceToFairValue,float64,0,0,0,0,48698
45,debtToMarketCap,float64,0,0,0,0,155727
46,evToSales,float64,287,0,0,0,96317
47,evToOperatingCashFlow,float64,287,0,0,0,71252
48,evToFreeCashFlow,float64,287,0,0,0,71416
49,evToEBITDA,float64,287,0,0,0,60088
50,netDebtToEBITDA,float64,287,0,0,0,56501
51,incomeQuality,float64,287,0,0,0,58289
52,taxBurden,float64,287,0,0,0,40866
53,interestBurden,float64,287,0,0,0,82591
54,returnOnAssets,float64,287,0,0,0,40894
55,operatingReturnOnAssets,float64,287,0,0,0,61090
56,returnOnTangibleAssets,float64,287,0,0,0,40808
57,returnOnEquity,float64,287,0,0,0,38668
58,returnOnInvestedCapital,float64,287,0,0,0,61853
59,returnOnCapitalEmployed,float64,287,0,0,0,42064
60,earningsYield,float64,287,0,0,0,19418
61,freeCashFlowYield,float64,287,0,0,0,64161
62,capexToOperatingCashFlow,float64,287,0,0,0,157737
63,capexToDepreciation,float64,287,0,0,0,182644
64,capexToRevenue,float64,287,0,0,0,175707
65,salesGeneralAndAdministrativeToRevenue,float64,287,0,0,0,279541
66,researchAndDevelopementToRevenue,float64,287,0,0,0,484180
67,stockBasedCompensationToRevenue,float64,287,0,0,0,365095
68,intangiblesToTotalAssets,float64,287,0,0,0,251754
69,freeCashFlowToEquity,float64,287,0,0,0,53372
70,freeCashFlowToFirm,float64,287,0,0,0,81352
71,c_grossProfit_to_revenue,float64,59949,0,0,0,6749
72,c_ebitda_to_revenue,float64,59949,0,0,0,14547
73,c_ebit_to_revenue,float64,59951,0,0,0,41067
74,c_operatingIncome_to_revenue,float64,59949,0,0,0,3896
75,c_incomeBeforeTax_to_revenue,float64,59950,0,0,0,33766
76,c_netIncome_to_revenue,float64,59949,0,0,0,4561
77,c_bottomLineNetIncome_to_revenue,float64,60055,0,0,0,5045
78,c_netIncomeFromContinuingOperations_to_revenue,float64,61353,0,0,0,5345
79,c_costOfRevenue_to_revenue,float64,59949,0,0,0,89346
80,c_operatingExpenses_to_revenue,float64,59950,0,0,0,16412
81,c_costAndExpenses_to_revenue,float64,59949,0,0,0,15447
82,c_researchAndDevelopmentExpenses_to_revenue,float64,59959,0,0,0,424528
83,c_generalAndAdministrativeExpenses_to_revenue,float64,59958,0,0,0,219887
84,c_sellingAndMarketingExpenses_to_revenue,float64,59959,0,0,0,407250
85,c_sellingGeneralAndAdministrativeExpenses_to_r...,float64,59950,0,0,0,54578
86,c_depreciationAndAmortization_to_revenue,float64,59949,0,0,0,52510
87,c_interestExpense_to_revenue,float64,60391,0,0,0,200426
88,c_incomeTaxExpense_to_revenue,float64,59950,0,0,0,89548
89,c_stockBasedCompensation_to_revenue,float64,638351,0,0,0,5
90,c_otherExpenses_to_revenue,float64,59949,0,0,0,216953
91,c_nonOperatingIncomeExcludingInterest_to_revenue,float64,59953,0,0,0,296158
92,c_totalOtherIncomeExpensesNet_to_revenue,float64,59950,0,0,0,103551
93,c_revenue_to_totalAssets,float64,38409,0,0,0,52039
94,c_grossProfit_to_totalAssets,float64,38406,0,0,0,44521
95,c_ebitda_to_totalAssets,float64,38406,0,0,0,16735
96,c_ebit_to_totalAssets,float64,38409,0,0,0,44362
97,c_operatingIncome_to_totalAssets,float64,38406,0,0,0,4505
98,c_netIncome_to_totalAssets,float64,38406,0,0,0,2502
99,c_operatingCashFlow_to_totalAssets,float64,638348,0,0,0,0
100,c_freeCashFlow_to_totalAssets,float64,638348,0,0,0,0
101,c_netIncome_to_totalEquity,float64,43035,0,0,0,2411
102,c_operatingIncome_to_totalEquity,float64,43035,0,0,0,4413
103,c_totalDebt_to_totalEquity,float64,43035,0,0,0,89033
104,c_totalLiabilities_to_totalEquity,float64,43035,0,0,0,2874
105,c_netDebt_to_totalEquity,float64,43035,0,0,0,4828
106,c_netIncome_to_investedCapital,float64,38431,0,0,0,2509
107,c_operatingIncome_to_investedCapital,float64,38431,0,0,0,4293
108,c_ebit_to_investedCapital,float64,38434,0,0,0,44236
109,c_netIncome_to_tangibleAssetValue,float64,37794,0,0,0,2516
110,c_operatingIncome_to_tangibleAssetValue,float64,37794,0,0,0,4522
111,c_totalDebt_to_totalAssets,float64,38406,0,0,0,88537
112,c_totalLiabilities_to_totalAssets,float64,38406,0,0,0,1428
113,c_netDebt_to_totalAssets,float64,38406,0,0,0,4565
114,c_longTermDebt_to_totalAssets,float64,38406,0,0,0,162254
115,c_shortTermDebt_to_totalAssets,float64,38407,0,0,0,229394
116,c_longTermDebt_to_totalDebt,float64,126306,0,0,0,80243
117,c_shortTermDebt_to_totalDebt,float64,126307,0,0,0,142228
118,c_totalDebt_to_capital,float64,38452,0,0,0,89925
119,c_longTermDebt_to_capital,float64,38452,0,0,0,163866
120,c_cashAndCashEquivalents_to_totalDebt,float64,126306,0,0,0,11086
121,c_cashAndShortTermInvestments_to_totalDebt,float64,126306,0,0,0,9368
122,c_cashAndCashEquivalents_to_totalAssets,float64,38406,0,0,0,14801
123,c_cashAndShortTermInvestments_to_totalAssets,float64,38406,0,0,0,12882
124,c_workingCapital_to_totalAssets,float64,38683,0,0,0,8068
125,c_workingCapital_to_revenue,float64,60230,0,0,0,36441
126,c_investedCapital_to_totalAssets,float64,38683,0,0,0,2494
127,c_totalCurrentAssets_to_totalCurrentLiabilities,float64,60677,0,0,0,4462
128,c_cashAndCashEquivalents_to_totalCurrentLiabil...,float64,60677,0,0,0,10961
129,c_cashAndShortTermInvestments_to_totalCurrentL...,float64,60677,0,0,0,9429
130,c_netReceivables_to_totalCurrentLiabilities,float64,60677,0,0,0,83943
131,c_inventory_to_totalCurrentAssets,float64,47964,0,0,0,278503
132,c_netReceivables_to_totalCurrentAssets,float64,47964,0,0,0,89985
133,c_otherCurrentAssets_to_totalCurrentAssets,float64,47964,0,0,0,189104
134,c_prepaids_to_totalCurrentAssets,float64,47965,0,0,0,370261
135,c_totalCurrentAssets_to_totalAssets,float64,38406,0,0,0,11642
136,c_totalNonCurrentAssets_to_totalAssets,float64,38406,0,0,0,17259
137,c_propertyPlantEquipmentNet_to_totalAssets,float64,38406,0,0,0,88793
138,c_inventory_to_totalAssets,float64,38406,0,0,0,288079
139,c_netReceivables_to_totalAssets,float64,38406,0,0,0,93041
140,c_goodwill_to_totalAssets,float64,38407,0,0,0,348952
141,c_intangibleAssets_to_totalAssets,float64,38407,0,0,0,260319
142,c_goodwillAndIntangibleAssets_to_totalAssets,float64,38407,0,0,0,213510
143,c_longTermInvestments_to_totalAssets,float64,38407,0,0,0,304243
144,c_totalInvestments_to_totalAssets,float64,38406,0,0,0,237006
145,c_totalCurrentLiabilities_to_totalLiabilities,float64,38630,0,0,0,22122
146,c_totalNonCurrentLiabilities_to_totalLiabilities,float64,38630,0,0,0,47890
147,c_accountPayables_to_totalLiabilities,float64,38630,0,0,0,114135
148,c_totalPayables_to_totalLiabilities,float64,38630,0,0,0,102255
149,c_shortTermDebt_to_totalLiabilities,float64,38631,0,0,0,228709
150,c_longTermDebt_to_totalLiabilities,float64,38630,0,0,0,161691
151,c_revenue_to_averageReceivables,float64,134130,0,0,0,13527
152,c_costOfRevenue_to_averagePayables,float64,152468,0,0,0,67311
153,c_costOfRevenue_to_averageInventory,float64,324353,0,0,0,11882
154,c_revenue_to_propertyPlantEquipmentNet,float64,127021,0,0,0,22408
155,c_revenue_to_workingCapital,float64,44009,0,0,0,52662
156,c_operatingCashFlow_to_revenue,float64,638351,0,0,0,0
157,c_freeCashFlow_to_revenue,float64,638351,0,0,0,0
158,c_operatingCashFlow_to_totalDebt,float64,638349,0,0,0,0
159,c_freeCashFlow_to_totalDebt,float64,638349,0,0,0,0
160,c_operatingCashFlow_to_totalCurrentLiabilities,float64,638351,0,0,0,0
161,c_operatingCashFlow_to_netIncome,float64,638349,0,0,0,0
162,c_freeCashFlow_to_netIncome,float64,638349,0,0,0,0
163,c_freeCashFlow_to_operatingCashFlow,float64,638348,0,0,0,0
164,c_ebit_to_interestExpense,float64,242417,0,0,0,12296
165,c_operatingIncome_to_interestExpense,float64,242417,0,0,0,2711
166,c_operatingCashFlow_to_interestExpense,float64,638353,0,0,0,0
167,c_capitalExpenditure_to_operatingCashFlow,float64,638348,0,0,0,7
168,c_investmentsInPropertyPlantAndEquipment_to_op...,float64,638348,0,0,0,8
169,c_netDividendsPaid_to_operatingCashFlow,float64,638348,0,0,0,6
170,c_commonDividendsPaid_to_operatingCashFlow,float64,638348,0,0,0,6
171,c_dividendsPaid_plus_capex_to_operatingCashFlow,float64,638348,0,0,0,5
172,c_incomeTaxExpense_to_incomeBeforeTax,float64,40194,0,0,0,104297
173,c_netIncome_to_incomeBeforeTax,float64,40190,0,0,0,677
174,c_incomeBeforeTax_to_ebit,float64,53086,0,0,0,29755
175,c_operatingCashFlow_to_netIncome_quality,float64,638349,0,0,0,0
176,c_marketCap_to_revenue,float64,60230,0,0,0,12252
177,c_marketCap_to_operatingCashFlow,float64,638348,0,0,0,0
178,c_marketCap_to_freeCashFlow,float64,638348,0,0,0,0
179,c_marketCap_to_netIncome,float64,6705,0,0,0,13006
180,c_revenue_to_marketCap,float64,13438,0,0,0,59044
181,c_operatingCashFlow_to_marketCap,float64,638348,0,0,0,0
182,c_freeCashFlow_to_marketCap,float64,638348,0,0,0,0
183,c_netIncome_to_marketCap,float64,13435,0,0,0,6276
184,c_totalEquity_to_marketCap,float64,48140,0,0,0,7550
185,c_totalDebt_to_marketCap,float64,48139,0,0,0,84182
186,c_netDebt_to_marketCap,float64,48139,0,0,0,4539
187,c_enterpriseValue_to_revenue,float64,60230,0,0,0,36382
188,c_enterpriseValue_to_operatingCashFlow,float64,638348,0,0,0,0
189,c_enterpriseValue_to_freeCashFlow,float64,638348,0,0,0,0
190,c_enterpriseValue_to_ebitda,float64,21310,0,0,0,39174
191,c_enterpriseValue_to_ebit,float64,53355,0,0,0,29768
192,c_stockPrice_to_eps,float64,7989,0,0,0,11
193,c_stockPrice_to_bookValuePerShare,float64,50389,0,0,0,10
194,c_stockPrice_to_revenuePerShare,float64,72173,0,0,0,10
195,c_stockPrice_to_operatingCashFlowPerShare,float64,64051,0,0,0,9
196,c_stockPrice_to_freeCashFlowPerShare,float64,64164,0,0,0,9
197,c_dividendPerShare_to_stockPrice,float64,24,0,0,0,341646
198,c_netDividendsPaid_to_netIncome,float64,638349,0,0,0,6
199,c_commonDividendsPaid_to_netIncome,float64,638349,0,0,0,6
200,c_netDividendsPaid_to_freeCashFlow,float64,638348,0,0,0,6
201,c_commonDividendsPaid_to_freeCashFlow,float64,638348,0,0,0,6
202,c_netDividendsPaid_to_marketCap,float64,638348,0,0,0,6
203,c_commonDividendsPaid_to_marketCap,float64,638348,0,0,0,6
204,c_revenue_to_weightedAverageShsOut,float64,13150,0,0,0,59042
205,c_netIncome_to_weightedAverageShsOut,float64,13147,0,0,0,6275
206,c_operatingCashFlow_to_weightedAverageShsOut,float64,638348,0,0,0,0
207,c_freeCashFlow_to_weightedAverageShsOut,float64,638348,0,0,0,0
208,c_totalEquity_to_weightedAverageShsOut,float64,47853,0,0,0,7547
209,c_cashAndCashEquivalents_to_weightedAverageShsOut,float64,47853,0,0,0,14973
210,symbol,object,0,0,0,0,0
211,date_fundamentals,datetime64[ns],0,0,0,0,0
212,acceptedDate,datetime64[ns],0,0,0,0,0
213,exchange,object,51640,0,0,0,0
214,industry,object,51640,0,0,0,0
215,sector,object,51640,0,0,0,0
216,country,object,51640,0,0,0,0
217,ipoDate,object,51640,0,0,4679,0
218,isEtf,object,51640,0,0,0,586509
219,isActivelyTrading,object,51640,0,0,0,137464
220,isAdr,object,51640,0,0,0,557166
221,isFund,object,51640,0,0,0,560353
222,iteracion,float64,75038,0,0,0,0
223,date_t0,datetime64[ns],75038,0,0,0,0
224,rate_3m_t0,float64,75038,0,0,0,1118
225,rate_2y_t0,float64,75038,0,0,0,0
226,rate_10y_t0,float64,75038,0,0,0,0
227,rate_30y_t0,float64,75038,0,0,0,0
228,industrial_production_t0,float64,75038,0,0,0,0
229,cfnai_t0,float64,75038,0,0,0,10490
230,cpi_t0,float64,75038,0,0,0,0
231,core_cpi_t0,float64,75038,0,0,0,0
232,core_pce_t0,float64,75038,0,0,0,0
233,unemployment_t0,float64,75038,0,0,0,0
234,vix_t0,float64,75038,0,0,0,0
235,nfci_t0,float64,75038,0,0,0,2475
236,baa_10y_t0,float64,75038,0,0,0,0
237,fed_funds_t0,float64,75038,0,0,0,0
238,house_price_index_t0,float64,75038,0,0,0,0
239,consumer_sentiment_t0,float64,75038,0,0,0,0
240,spread_10y_2y_t0,float64,75038,0,0,0,3150
241,spread_10y_3m_t0,float64,75038,0,0,0,940
242,retail_sales_mom_t0,float64,75038,0,0,0,0
243,pce_mom_t0,float64,75038,0,0,0,0
244,payrolls_mom_t0,float64,75038,0,0,0,2497
245,jobless_claims_mom_t0,float64,75038,0,0,0,18022
246,m2_mom_t0,float64,75038,0,0,0,0
247,housing_starts_mom_t0,float64,75038,0,0,0,4048
248,date_pred_t1,datetime64[ns],75038,0,0,0,0
249,rate_3m_pred_t1,float32,75038,0,0,0,0
250,rate_2y_pred_t1,float32,75038,0,0,0,0
251,rate_10y_pred_t1,float32,75038,0,0,0,0
252,rate_30y_pred_t1,float32,75038,0,0,0,0
253,industrial_production_pred_t1,float32,75038,0,0,0,0
254,cfnai_pred_t1,float32,75038,0,0,0,0
255,cpi_pred_t1,float32,75038,0,0,0,0
256,core_cpi_pred_t1,float32,75038,0,0,0,0
257,core_pce_pred_t1,float32,75038,0,0,0,0
258,unemployment_pred_t1,float32,75038,0,0,0,0
259,vix_pred_t1,float32,75038,0,0,0,0
260,nfci_pred_t1,float32,75038,0,0,0,0
261,baa_10y_pred_t1,float32,75038,0,0,0,0
262,fed_funds_pred_t1,float32,75038,0,0,0,0
263,house_price_index_pred_t1,float32,75038,0,0,0,0
264,consumer_sentiment_pred_t1,float32,75038,0,0,0,0
265,spread_10y_2y_pred_t1,float32,75038,0,0,0,0
266,spread_10y_3m_pred_t1,float32,75038,0,0,0,0
267,retail_sales_mom_pred_t1,float32,75038,0,0,0,0
268,pce_mom_pred_t1,float32,75038,0,0,0,0
269,payrolls_mom_pred_t1,float32,75038,0,0,0,0
270,jobless_claims_mom_pred_t1,float32,75038,0,0,0,0
271,m2_mom_pred_t1,float32,75038,0,0,0,0
272,housing_starts_mom_pred_t1,float32,75038,0,0,0,0
273,date_pred_t2,datetime64[ns],75038,0,0,0,0
274,rate_3m_pred_t2,float32,75038,0,0,0,0
275,rate_2y_pred_t2,float32,75038,0,0,0,0
276,rate_10y_pred_t2,float32,75038,0,0,0,0
277,rate_30y_pred_t2,float32,75038,0,0,0,0
278,industrial_production_pred_t2,float32,75038,0,0,0,0
279,cfnai_pred_t2,float32,75038,0,0,0,0
280,cpi_pred_t2,float32,75038,0,0,0,0
281,core_cpi_pred_t2,float32,75038,0,0,0,0
282,core_pce_pred_t2,float32,75038,0,0,0,0
283,unemployment_pred_t2,float32,75038,0,0,0,0
284,vix_pred_t2,float32,75038,0,0,0,0
285,nfci_pred_t2,float32,75038,0,0,0,0
286,baa_10y_pred_t2,float32,75038,0,0,0,0
287,fed_funds_pred_t2,float32,75038,0,0,0,0
288,house_price_index_pred_t2,float32,75038,0,0,0,0
289,consumer_sentiment_pred_t2,float32,75038,0,0,0,0
290,spread_10y_2y_pred_t2,float32,75038,0,0,0,0
291,spread_10y_3m_pred_t2,float32,75038,0,0,0,0
292,retail_sales_mom_pred_t2,float32,75038,0,0,0,0
293,pce_mom_pred_t2,float32,75038,0,0,0,0
294,payrolls_mom_pred_t2,float32,75038,0,0,0,0
295,jobless_claims_mom_pred_t2,float32,75038,0,0,0,0
296,m2_mom_pred_t2,float32,75038,0,0,0,0
297,housing_starts_mom_pred_t2,float32,75038,0,0,0,0
298,date_pred_t3,datetime64[ns],75038,0,0,0,0
299,rate_3m_pred_t3,float32,75038,0,0,0,0
300,rate_2y_pred_t3,float32,75038,0,0,0,0
301,rate_10y_pred_t3,float32,75038,0,0,0,0
302,rate_30y_pred_t3,float32,75038,0,0,0,0
303,industrial_production_pred_t3,float32,75038,0,0,0,0
304,cfnai_pred_t3,float32,75038,0,0,0,0
305,cpi_pred_t3,float32,75038,0,0,0,0
306,core_cpi_pred_t3,float32,75038,0,0,0,0
307,core_pce_pred_t3,float32,75038,0,0,0,0
308,unemployment_pred_t3,float32,75038,0,0,0,0
309,vix_pred_t3,float32,75038,0,0,0,0
310,nfci_pred_t3,float32,75038,0,0,0,0
311,baa_10y_pred_t3,float32,75038,0,0,0,0
312,fed_funds_pred_t3,float32,75038,0,0,0,0
313,house_price_index_pred_t3,float32,75038,0,0,0,0
314,consumer_sentiment_pred_t3,float32,75038,0,0,0,0
315,spread_10y_2y_pred_t3,float32,75038,0,0,0,0
316,spread_10y_3m_pred_t3,float32,75038,0,0,0,0
317,retail_sales_mom_pred_t3,float32,75038,0,0,0,0
318,pce_mom_pred_t3,float32,75038,0,0,0,0
319,payrolls_mom_pred_t3,float32,75038,0,0,0,0
320,jobless_claims_mom_pred_t3,float32,75038,0,0,0,0
321,m2_mom_pred_t3,float32,75038,0,0,0,0
322,housing_starts_mom_pred_t3,float32,75038,0,0,0,0

In [43]:
target_return = pd.read_parquet("archivos/target_return.parquet")
target_return.tail(10)

       symbol        acceptedDate  target_return
469019   ZYXI 2023-04-27 16:52:15      -0.147727
469020   ZYXI 2023-07-27 17:04:43      -0.277048
469021   ZYXI 2023-10-26 17:01:27       0.510791
469022   ZYXI 2024-03-12 17:24:50      -0.135540
469023   ZYXI 2024-04-30 17:00:59      -0.134240
469024   ZYXI 2024-07-25 17:00:55      -0.038074
469025   ZYXI 2024-10-24 17:16:33      -0.232456
469026   ZYXI 2025-03-11 16:45:24      -0.346041
469027   ZYXI 2025-04-29 17:00:23       0.343373
469028   ZYXI 2025-07-31 17:15:53      -0.551508

In [44]:
revisar_nulos(target_return)

          column           dtype  NaN  None  Null_string  Empty_string  Zero
0         symbol          object    0     0            0             0     0
1   acceptedDate  datetime64[ns]    0     0            0             0     0
2  target_return         float64    0     0            0             0  4400

In [45]:
df_merged["acceptedDate"] = pd.to_datetime(df_merged["acceptedDate"], errors="coerce").dt.normalize()
target_return["acceptedDate"] = pd.to_datetime(target_return["acceptedDate"], errors="coerce").dt.normalize()

In [46]:
df_final = df_merged.merge(
    target_return,
    on=["symbol", "acceptedDate"],
    how="left"
)

In [47]:
df_final.tail(30)

,grossProfitMargin,ebitMargin,ebitdaMargin,operatingProfitMargin,pretaxProfitMargin,continuousOperationsProfitMargin,netProfitMargin,bottomLineProfitMargin,receivablesTurnover,payablesTurnover,inventoryTurnover,fixedAssetTurnover,assetTurnover,currentRatio,quickRatio,solvencyRatio,cashRatio,priceToEarningsRatio,priceToEarningsGrowthRatio,forwardPriceToEarningsGrowthRatio,priceToBookRatio,priceToSalesRatio,priceToFreeCashFlowRatio,priceToOperatingCashFlowRatio,debtToAssetsRatio,debtToEquityRatio,debtToCapitalRatio,longTermDebtToCapitalRatio,financialLeverageRatio,workingCapitalTurnoverRatio,operatingCashFlowRatio,operatingCashFlowSalesRatio,freeCashFlowOperatingCashFlowRatio,debtServiceCoverageRatio,interestCoverageRatio,shortTermOperatingCashFlowCoverageRatio,operatingCashFlowCoverageRatio,capitalExpenditureCoverageRatio,dividendPaidAndCapexCoverageRatio,dividendPayoutRatio,dividendYield,dividendYieldPercentage,netIncomePerEBT,ebtPerEbit,priceToFairValue,debtToMarketCap,evToSales,evToOperatingCashFlow,evToFreeCashFlow,evToEBITDA,netDebtToEBITDA,incomeQuality,taxBurden,interestBurden,returnOnAssets,operatingReturnOnAssets,returnOnTangibleAssets,returnOnEquity,returnOnInvestedCapital,returnOnCapitalEmployed,earningsYield,freeCashFlowYield,capexToOperatingCashFlow,capexToDepreciation,capexToRevenue,salesGeneralAndAdministrativeToRevenue,researchAndDevelopementToRevenue,stockBasedCompensationToRevenue,intangiblesToTotalAssets,freeCashFlowToEquity,freeCashFlowToFirm,c_grossProfit_to_revenue,c_ebitda_to_revenue,c_ebit_to_revenue,c_operatingIncome_to_revenue,c_incomeBeforeTax_to_revenue,c_netIncome_to_revenue,c_bottomLineNetIncome_to_revenue,c_netIncomeFromContinuingOperations_to_revenue,c_costOfRevenue_to_revenue,c_operatingExpenses_to_revenue,c_costAndExpenses_to_revenue,c_researchAndDevelopmentExpenses_to_revenue,c_generalAndAdministrativeExpenses_to_revenue,c_sellingAndMarketingExpenses_to_revenue,c_sellingGeneralAndAdministrativeExpenses_to_revenue,c_depreciationAndAmortization_to_revenue,c_interestExpense_to_revenue,c_incomeTaxExpense_to_revenue,c_stockBasedCompensation_to_revenue,c_otherExpenses_to_revenue,c_nonOperatingIncomeExcludingInterest_to_revenue,c_totalOtherIncomeExpensesNet_to_revenue,c_revenue_to_totalAssets,c_grossProfit_to_totalAssets,c_ebitda_to_totalAssets,c_ebit_to_totalAssets,c_operatingIncome_to_totalAssets,c_netIncome_to_totalAssets,c_operatingCashFlow_to_totalAssets,c_freeCashFlow_to_totalAssets,c_netIncome_to_totalEquity,c_operatingIncome_to_totalEquity,c_totalDebt_to_totalEquity,c_totalLiabilities_to_totalEquity,c_netDebt_to_totalEquity,c_netIncome_to_investedCapital,c_operatingIncome_to_investedCapital,c_ebit_to_investedCapital,c_netIncome_to_tangibleAssetValue,c_operatingIncome_to_tangibleAssetValue,c_totalDebt_to_totalAssets,c_totalLiabilities_to_totalAssets,c_netDebt_to_totalAssets,c_longTermDebt_to_totalAssets,c_shortTermDebt_to_totalAssets,c_longTermDebt_to_totalDebt,c_shortTermDebt_to_totalDebt,c_totalDebt_to_capital,c_longTermDebt_to_capital,c_cashAndCashEquivalents_to_totalDebt,c_cashAndShortTermInvestments_to_totalDebt,c_cashAndCashEquivalents_to_totalAssets,c_cashAndShortTermInvestments_to_totalAssets,c_workingCapital_to_totalAssets,c_workingCapital_to_revenue,c_investedCapital_to_totalAssets,c_totalCurrentAssets_to_totalCurrentLiabilities,c_cashAndCashEquivalents_to_totalCurrentLiabilities,c_cashAndShortTermInvestments_to_totalCurrentLiabilities,c_netReceivables_to_totalCurrentLiabilities,c_inventory_to_totalCurrentAssets,c_netReceivables_to_totalCurrentAssets,c_otherCurrentAssets_to_totalCurrentAssets,c_prepaids_to_totalCurrentAssets,c_totalCurrentAssets_to_totalAssets,c_totalNonCurrentAssets_to_totalAssets,c_propertyPlantEquipmentNet_to_totalAssets,c_inventory_to_totalAssets,c_netReceivables_to_totalAssets,c_goodwill_to_totalAssets,c_intangibleAssets_to_totalAssets,c_goodwillAndIntangibleAssets_to_totalAssets,c_longTermInvestments_to_totalAssets,c_totalInvestments_to_totalAssets,c_totalCurrentLiabilities_to_totalLiabilities,c_totalNonCurrentLiabilities_to_totalLiabilities,c_accountPayables_to_totalLiabilities,c_totalPayables_to_totalLiabilities,c_shortTermDebt_to_totalLiabilities,c_longTermDebt_to_totalLiabilities,c_revenue_to_averageReceivables,c_costOfRevenue_to_averagePayables,c_costOfRevenue_to_averageInventory,c_revenue_to_propertyPlantEquipmentNet,c_revenue_to_workingCapital,c_operatingCashFlow_to_revenue,c_freeCashFlow_to_revenue,c_operatingCashFlow_to_totalDebt,c_freeCashFlow_to_totalDebt,c_operatingCashFlow_to_totalCurrentLiabilities,c_operatingCashFlow_to_netIncome,c_freeCashFlow_to_netIncome,c_freeCashFlow_to_operatingCashFlow,c_ebit_to_interestExpense,c_operatingIncome_to_interestExpense,c_operatingCashFlow_to_interestExpense,c_capitalExpenditure_to_operatingCashFlow,c_investmentsInPropertyPlantAndEquipment_to_operatingCashFlow,c_netDividendsPaid_to_operatingCashFlow,c_commonDividendsPaid_to_operatingCashFlow,c_dividendsPaid_plus_capex_to_operatingCashFlow,c_incomeTaxExpense_to_incomeBeforeTax,c_netIncome_to_incomeBeforeTax,c_incomeBeforeTax_to_ebit,c_operatingCashFlow_to_netIncome_quality,c_marketCap_to_revenue,c_marketCap_to_operatingCashFlow,c_marketCap_to_freeCashFlow,c_marketCap_to_netIncome,c_revenue_to_marketCap,c_operatingCashFlow_to_marketCap,c_freeCashFlow_to_marketCap,c_netIncome_to_marketCap,c_totalEquity_to_marketCap,c_totalDebt_to_marketCap,c_netDebt_to_marketCap,c_enterpriseValue_to_revenue,c_enterpriseValue_to_operatingCashFlow,c_enterpriseValue_to_freeCashFlow,c_enterpriseValue_to_ebitda,c_enterpriseValue_to_ebit,c_stockPrice_to_eps,c_stockPrice_to_bookValuePerShare,c_stockPrice_to_revenuePerShare,c_stockPrice_to_operatingCashFlowPerShare,c_stockPrice_to_freeCashFlowPerShare,c_dividendPerShare_to_stockPrice,c_netDividendsPaid_to_netIncome,c_commonDividendsPaid_to_netIncome,c_netDividendsPaid_to_freeCashFlow,c_commonDividendsPaid_to_freeCashFlow,c_netDividendsPaid_to_marketCap,c_commonDividendsPaid_to_marketCap,c_revenue_to_weightedAverageShsOut,c_netIncome_to_weightedAverageShsOut,c_operatingCashFlow_to_weightedAverageShsOut,c_freeCashFlow_to_weightedAverageShsOut,c_totalEquity_to_weightedAverageShsOut,c_cashAndCashEquivalents_to_weightedAverageShsOut,symbol,date_fundamentals,acceptedDate,exchange,industry,sector,country,ipoDate,isEtf,isActivelyTrading,isAdr,isFund,iteracion,date_t0,rate_3m_t0,rate_2y_t0,rate_10y_t0,rate_30y_t0,industrial_production_t0,cfnai_t0,cpi_t0,core_cpi_t0,core_pce_t0,unemployment_t0,vix_t0,nfci_t0,baa_10y_t0,fed_funds_t0,house_price_index_t0,consumer_sentiment_t0,spread_10y_2y_t0,spread_10y_3m_t0,retail_sales_mom_t0,pce_mom_t0,payrolls_mom_t0,jobless_claims_mom_t0,m2_mom_t0,housing_starts_mom_t0,date_pred_t1,rate_3m_pred_t1,rate_2y_pred_t1,rate_10y_pred_t1,rate_30y_pred_t1,industrial_production_pred_t1,cfnai_pred_t1,cpi_pred_t1,core_cpi_pred_t1,core_pce_pred_t1,unemployment_pred_t1,vix_pred_t1,nfci_pred_t1,baa_10y_pred_t1,fed_funds_pred_t1,house_price_index_pred_t1,consumer_sentiment_pred_t1,spread_10y_2y_pred_t1,spread_10y_3m_pred_t1,retail_sales_mom_pred_t1,pce_mom_pred_t1,payrolls_mom_pred_t1,jobless_claims_mom_pred_t1,m2_mom_pred_t1,housing_starts_mom_pred_t1,date_pred_t2,rate_3m_pred_t2,rate_2y_pred_t2,rate_10y_pred_t2,rate_30y_pred_t2,industrial_production_pred_t2,cfnai_pred_t2,cpi_pred_t2,core_cpi_pred_t2,core_pce_pred_t2,unemployment_pred_t2,vix_pred_t2,nfci_pred_t2,baa_10y_pred_t2,fed_funds_pred_t2,house_price_index_pred_t2,consumer_sentiment_pred_t2,spread_10y_2y_pred_t2,spread_10y_3m_pred_t2,retail_sales_mom_pred_t2,pce_mom_pred_t2,payrolls_mom_pred_t2,jobless_claims_mom_pred_t2,m2_mom_pred_t2,housing_starts_mom_pred_t2,date_pred_t3,rate_3m_pred_t3,rate_2y_pred_t3,rate_10y_pred_t3,rate_30y_pred_t3,industrial_production_pred_t3,cfnai_pred_t3,cpi_pred_t3,core_cpi_pred_t3,core_pce_pred_t3,unemployment_pred_t3,vix_pred_t3,nfci_pred_t3,baa_10y_pred_t3,fed_funds_pred_t3,house_price_index_pred_t3,consumer_sentiment_pred_t3,spread_10y_2y_pred_t3,spread_10y_3m_pred_t3,retail_sales_mom_pred_t3,pce_mom_pred_t3,payrolls_mom_pred_t3,jobless_claims_mom_pred_t3,m2_mom_pred_t3,housing_starts_mom_pred_t3,target_return
688113,0.435514,-0.036206,-0.002452,-0.033284,-0.036508,-0.044670,-0.044670,-0.044670,1.279997,1.326624,0.620780,3.123911,0.244588,2.746087,1.791702,-0.006870,0.809504,-43.336462,7.735559,7.735559,3.097916,7.743332,110.522522,105.853985,0.208238,0.340616,0.254074,0.183416,1.635708,0.600077,0.076777,0.073151,0.957759,-0.197130,-110.111111,1.366374,0.085921,23.673913,23.673913,0.000000,0.000000,0.000000,1.223551,1.096872,3.097916,0.079419,7.823436,106.949027,111.665858,-3190.890137,-32.671233,-1.637594,1.223551,1.008349,-0.010926,-0.008214,-0.015097,-0.017871,-0.010436,-0.010614,-0.005769,0.009048,0.042241,0.091542,0.003090,0.000000,0.155169,0.053066,0.276281,-2.990000e+05,-2.379890e+05,0.435514,-0.036072,0.000000,-0.036072,-0.036508,-0.044670,0.047054,0.000000,0.564486,0.471586,1.036072,0.155169,0.000000,0.000000,0.293545,-0.050673,-0.001310,0.008161,NaN,0.022872,0.006146,-0.000437,0.244588,0.106522,-0.008823,0.000000,-0.008823,-0.010926,NaN,NaN,-0.017871,-0.014431,0.000000,0.635708,-0.308569,-0.014348,-0.011586,0.000000,-0.032607,-0.026331,0.000000,0.388644,-0.188645,0.000000,0.000000,NaN,NaN,0.000000,0.000000,NaN,NaN,0.188645,0.188645,0.406905,1.663633,0.761482,2.746087,0.809504,0.809504,0.819973,0.347544,0.298597,0.059075,0.000000,0.639944,0.360056,0.078296,0.222408,0.191085,0.255391,0.020890,0.276281,0.000000,0.000000,0.599620,0.400380,0.267787,0.267787,0.000000,0.000000,1.304790,1.507152,0.624459,3.123911,0.601094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-27.538462,NaN,NaN,NaN,NaN,NaN,NaN,-0.223551,1.223551,NaN,NaN,7.743332,NaN,NaN,-173.345850,0.129143,NaN,NaN,-0.005769,0.322798,0.000000,-0.099605,7.823436,NaN,NaN,-216.885456,NaN,-195.333333,3.097916,7.743332,105.853985,110.522522,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.756780,-0.033805,NaN,NaN,1.891594,0.583687,LTRX,2025-12-31,2026-02-05,NASDAQ,Communication Equipment,Technology,US,2000-08-04,False,True,False,False,327.0,2026-02-01,3.67,3.52,4.26,4.87,102.344,0.03,327.46,333.512,128.901,4.4,17.44,-0.56,1.62,3.64,332.098,56.6,0.74,0.59,0.007174,0.006485,-0.000984,0.133005,0.008828,-0.030043,2026-03-01,3.752332,3.412838,3.765364,4.130352,101.046028,-0.04757,322.004974,327.622894,125.780365,4.086506,19.727106,-0.50208,1.614429,3.693112,339.878754,58.183315,0.350892,0.021149,0.004135,0.005728,0.001019,-0.020021,0.002653,0.011689,2026-04-01,3.706919,3.441358,3.804044,4.174387,101.201828,-0.061567,322.995972,328.772827,126.189911,4.066164,20.239012,-0.478878,1.621612,3.645522,341.213623,57.692722,0.356942,0.069821,0.00427,0.005767,0.000908,0.008727,0.00266,-0.004749,2026-05-01,3.722919,3.476256,3.859735,4.241346,101.412086,-0.040511,324.196594,329.490082,126.621384,3.947323,19.818506,-0.485549,1.618988,3.630307,341.977966,57.083374,0.379677,0.133335,0.003928,0.005999,0.00128,-0.105735,0.002574,0.000266,NaN
688114,0.329439,0.044036,0.084606,0.086917,-0.006163,-0.004365,-0.004365,-0.004365,2.089324,1.279206,0.724712,1.525460,0.175286,1.993239,1.073861,0.006555,0.274015,-100.035000,0.911521,0.911521,9.628280,1.746663,10.953913,9.100174,0.789472,24.827318,0.961281,0.960111,31.447983,0.936910,0.190713,0.191937,0.830769,1.053208,1.731458,6.028226,0.042616,5.909091,3.076132,-6.852941,0.017126,1.712636,0.708333,-0.070901,9.628280,2.518089,5.974805,31.128936,37.470016,70.618756,49.974203,-43.970588,0.708333,-0.139942,-0.000765,0.015044,-0.001416,-0.024062,0.013015,0.018499,-0.002499,0.091292,0.169231,0.800633,0.032482,0.000000,0.010014,0.011170,0.459740,-3.169100e+09,1.360958e+08,0.329439,0.127744,0.000000,0.127744,-0.006163,-0.004365,0.000000,0.000000,0.670561,0.201695,0.872256,0.010014,0.000000,0.063166,0.191681,0.000000,0.050199,-0.001797,NaN,0.000000,0.000000,0.000000,0.175286,0.057746,0.022392,0.000000,0.022392,-0.000765,NaN,NaN,-0.024062,0.704176,24.234961,30.447983,22.714791,-0.001020,0.029861,0.000000,0.001788,-0.052324,0.770636,0.968201,0.722297,0.765370,0.005266,0.993167,0.006833,1.027700,1.020678,0.062726,0.062726,0.048339,0.048339,0.175218,0.999615,0.749865,1.993239,0.274015,0.274015,0.000000,0.461248,0.000000,0.401280,0.000000,0.351629,0.648371,0.114907,0.162188,0.000000,0.236587,0.223152,0.459740,0.000000,0.000000,0.182205,0.817795,0.094903,0.094903,0.005439,0.790507,1.707178,1.288834,0.695519,1.525460,1.000385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.544757,NaN,NaN,NaN,NaN,NaN,NaN,0.291667,0.708333,NaN,NaN,1.746663,NaN,NaN,-400.140000,0.572520,NaN,NaN,-0.002499,0.103861,2.517060,2.359174,5.974805,NaN,NaN,46.771618,NaN,-397.800000,9.628280,1.746663,9.100174,10.953913,0.017126,NaN,NaN,NaN,NaN,NaN,NaN,11.387427,-0.049708,NaN,NaN,2.065789,3.140351,ENR,2025-12-31,2026-02-05,NYSE,Electrical Equipment & Parts,Industrials,US,2015-06-12,False,True,False,False,327.0,2026-02-01,3.67,3.52,4.26,4.87,102.344,0.03,327.46,333.512,128.901,4.4,17.44,-0.56,1.62,3.64,332.098,56.6,0.74,0.59,0.007174,0.006485,-0.000984,0.133005,0.008828,-0.030043,2026-03-01,3.752332,3.412838,3.765364,4.130352,101.046028,-0.04757,322.004974,327.622894,125.780365,4.086506,19.727106,-0.50208,1.614429,3.693112,339.878754,58.183315,0.350892,0.021149,0.004135,0.005728,0.001019,-0.020021,0.002653,0.011689,2026-04-01,3.706919,3.441358,3.804044,4.174387,101.201828,-0.061567,322.995972,328.772827,126.189911,4.066164,20.239012,-0.478878,1.621612,3.645522,341.213623,57.692722,0.356942,0.069821,0.00427,0.005767,0.000908,0.008727,0.00266,-0.004749,2026-05-01,3.722919,3.476256,3.859735,4.241346,101.412086,-0.040511,324.196594,329.490082,126.621384,3.947323,19.818506,-0.485549,1.618988,3.630307,341.977966,57.083374,0.379677,0.133335,0.003928,0.005999,0.00128,-0.105735,0.002574,0.000266,NaN
688115,0.397314,0.221620,0.292894,0.228553,0.193458,0.146014,0.146014,0.146014,1.615115,1.963303,0.355982,0.970359,0.089778,1.859842,0.669257,0.053337,0.163924,53.355698,4.223993,4.223993,4.410995,31.162687,145.153342,117.810780,0.215011,0.338996,0.253172,0.187285,1.576646,0.667727,0.186015,0.264515,0.811630,0.357301,8.115385,0.401513,0.110448,5.308696,5.308696,0.000000,0.000000,0.000000,0.754759,0.846445,4.410995,0.073384,33.324515,125.983589,155.222969,113.776599,7.380917,1.811573,0.754759,0.872923,0.013109,0.020581,0.038339,0.020668,0.016626,0.023522,0.004686,0.006889,0.188370,0.699088,0.049827,0.000000,0.000000,0.020147,0.658083,-8.988000e+08,3.409119e+08,0.442808,0.223137,0.000000,0.223137,0.193458,0.146014,0.000000,0.000000,0.557192,0.219671,0.776863,0.000000,0.000000,0.000000,0.168761,0.000000,0.028163,0.047444,NaN,0.050910,0.000000,-0.029679,0.089778,0.039754,0.020033,0.000000,0.020033,0.013109,NaN,NaN,0.020668,0.031584,0.106804,0.576646,0.073809,0.015236,0.023284,0.000000,-0.550204,-0.840816,0.067742,0.365742,0.046814,0.009705,0.058036,0.143267,0.856733,0.078735,0.011280,0.308929,0.308929,0.020927,0.020927,0.109771,1.222704,0.860374,1.859842,0.163924,0.163924,0.435405,0.640154,0.234109,0.037598,0.000000,0.237436,0.762564,0.092520,0.151995,0.055586,0.386592,0.271491,0.658083,0.000000,0.000000,0.349056,0.650944,0.075352,0.075352,0.158681,0.026535,1.633982,1.799860,0.331828,0.970359,0.817860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.923077,NaN,NaN,NaN,NaN,NaN,NaN,0.245241,0.754759,NaN,NaN,31.162687,NaN,NaN,213.422792,0.032090,NaN,NaN,0.004686,0.226706,0.024213,0.016733,33.324515,NaN,NaN,149.345594,NaN,213.238318,4.410995,31.162687,117.810780,145.153342,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,14.643474,2.138150,NaN,NaN,103.452846,3.413427,ROLLP,2025-12-27,2026-02-05,NASDAQ,Manufacturing - Tools & Accessories,Industrials,US,2021-09-22,False,False,False,False,327.0,2026-02-01,3.67,3.52,4.26,4.87,102.344,0.03,327.46,333.512,128.901,4.4,17.44,-0.56,1.62,3.64,332.098,56.6,0.74,0.59,0.007174,0.006485,-0.000984,0.133005,0.008828,-0.030043,2026-03-01,3.752332,3.412838,3.765364,4.130352,101.046028,-0.04757,322.004974,327.622894,125.780365,4.086506,19.727106,-0.50208,1.614429,3.693112,339.878754,58.183315,0.350892,0.021149,0.004135,0.005728,0.001019,-0.020021,0.002653,0.011689,2026-04-01,3.706919,3.441358,3.804044,4.174387,101.201828,-0.061567,322.995972,328.772827,126.189911,4.066164,20.239012,-0.478878,1.621612,3.645522,341.213623,57.692722,0.356942,0.069821,0.00427,0.005767,0.000908,0.008727,0.00266,-0.004749,2026-05-01,3.722919,3.476256,3.859735,4.241346,101.412086,-0.040511,324.196594,329.490082,126.621384,3.947323,19.818506,-0.485549,1.618988,3.630307,341.977966,57.083374,0.379677,0.133335,0.003928,0.005999,0.00128,-0.105735,0.002574,0.000266,NaN
688116,0.497184,0.071032,0.140194,0.071032,0.073409,0.058082,0.058082,0.058082,2.292054,3.704060,0.000000,0.448391,0.264813,1.141335,1.141335,0.056422,0.429472,27.791263,-0.944903,-0.944903,4.244942,6.456658,-74.429173,462.358658,0.550547,1.366843,0.577496,0.443851,2.482699,9.249429,0.014156,0.013965,-6.212062,8.535288,14.006250,1.061983,0.006717,0.138657,0.138657,0.000000,0.000000,0.000000,0.791204,1.033467,4.244942,0.190044,8.111980,580.895623,-93.510915,57.862540,11.807371,0.240430,0.791204,1.033467,0.015381,0.018899,0.016351,0.038186,0.024604,0.025462,0.008996,-0.013436,7.212062,1.456200,0.100714,0.000000,0.000000,0.011569,0.059335,-1.936730e+08,-1.836618e+06,0.000000,0.071032,0.000000,0.071032,0.073409,0.058082,0.000000,0.000000,0.000000,0.928968,0.000000,0.000000,0.000000,0.000000,0.428850,0.000000,-0.004397,-0.015328,NaN,0.500118,0.000000,0.002377,0.264813,0.000000,0.018810,0.000000,0.018810,0.015381,NaN,NaN,0.038186,0.046700,0.798079,1.482699,0.519531,0.022393,0.027386,0.000000,0.044783,0.054768,0.321456,0.597213,0.209260,0.321456,0.000000,1.000000,0.000000,0.468019,0.468019,0.349024,0.607318,0.112196,0.195226,0.036923,0.139429,0.686844,1.141335,0.429472,0.747302,0.442256,0.000000,0.387490,-0.042251,0.000000,0.298164,0.701836,0.590586,0.000000,0.115535,0.034125,0.025210,0.059335,0.000000,0.083030,0.437434,0.562566,0.000000,0.000000,0.000000,0.538261,2.323011,0.000000,NaN,0.448391,7.172123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,16.155510,NaN,NaN,NaN,NaN,NaN,NaN,-0.208796,0.791204,NaN,NaN,6.456658,NaN,NaN,111.165050,0.154879,NaN,NaN,0.008996,0.235574,0.188007,0.122388,8.111980,NaN,NaN,114.201702,NaN,108.875000,4.244942,6.456658,462.358658,-74.429173,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.046986,0.235056,NaN,NaN,6.155562,1.714623,UTI,2025-12-31,2026-02-05,NYSE,Education & Training Services,Consumer Defensive,US,2003-12-18,False,True,False,False,327.0,2026-02-01,3.67,3.52,4.26,4.87,102.344,0.03,327.46,333.512,128.901,4.4,17.44,-0.56,1.62,3.64,332.098,56.6,0.74,0.59,0.007174,0.006485,-0.000984,0.133005,0.008828,-0.030043,2026-03-01,3.752332,3.412838,3.765364,4.130352,101.046028,-0.04757,322.004974,327.622894,125.780365,4.086506,19.727106,-0.50208,1.614429,3.693112,339.878754,58.183315,0.350892,0.021149,0.004135,0.005728,0.001019,-0.020021,0.002653,0.011689,2026-04-01,3.706919,3.441358,3.804044,4.174387,101.201828,-0.061567,322.995972,328.772827,126.189911,4.066164,20.239012,-0.478878,1.621612,3.645522,341.213623,57.692722,0.356942,0.069821,0.00427,0.005767,0.000908,0.008727,0.00266,-0.004749,2026-05-01,3.722919,3.476256,3.859735,4.241346,101.412086,-0.040511,324.196594,329.490082,126.621384,3.947323,19.818506,-0.485549,1.618988,3.630307,341.977966,57.083374,0.379677,0.133335,0.003928,0.005999,0.00128,-0.105735,0.002574,0.000266,NaN

In [48]:
df_final.head(30)

,grossProfitMargin,ebitMargin,ebitdaMargin,operatingProfitMargin,pretaxProfitMargin,continuousOperationsProfitMargin,netProfitMargin,bottomLineProfitMargin,receivablesTurnover,payablesTurnover,inventoryTurnover,fixedAssetTurnover,assetTurnover,currentRatio,quickRatio,solvencyRatio,cashRatio,priceToEarningsRatio,priceToEarningsGrowthRatio,forwardPriceToEarningsGrowthRatio,priceToBookRatio,priceToSalesRatio,priceToFreeCashFlowRatio,priceToOperatingCashFlowRatio,debtToAssetsRatio,debtToEquityRatio,debtToCapitalRatio,longTermDebtToCapitalRatio,financialLeverageRatio,workingCapitalTurnoverRatio,operatingCashFlowRatio,operatingCashFlowSalesRatio,freeCashFlowOperatingCashFlowRatio,debtServiceCoverageRatio,interestCoverageRatio,shortTermOperatingCashFlowCoverageRatio,operatingCashFlowCoverageRatio,capitalExpenditureCoverageRatio,dividendPaidAndCapexCoverageRatio,dividendPayoutRatio,dividendYield,dividendYieldPercentage,netIncomePerEBT,ebtPerEbit,priceToFairValue,debtToMarketCap,evToSales,evToOperatingCashFlow,evToFreeCashFlow,evToEBITDA,netDebtToEBITDA,incomeQuality,taxBurden,interestBurden,returnOnAssets,operatingReturnOnAssets,returnOnTangibleAssets,returnOnEquity,returnOnInvestedCapital,returnOnCapitalEmployed,earningsYield,freeCashFlowYield,capexToOperatingCashFlow,capexToDepreciation,capexToRevenue,salesGeneralAndAdministrativeToRevenue,researchAndDevelopementToRevenue,stockBasedCompensationToRevenue,intangiblesToTotalAssets,freeCashFlowToEquity,freeCashFlowToFirm,c_grossProfit_to_revenue,c_ebitda_to_revenue,c_ebit_to_revenue,c_operatingIncome_to_revenue,c_incomeBeforeTax_to_revenue,c_netIncome_to_revenue,c_bottomLineNetIncome_to_revenue,c_netIncomeFromContinuingOperations_to_revenue,c_costOfRevenue_to_revenue,c_operatingExpenses_to_revenue,c_costAndExpenses_to_revenue,c_researchAndDevelopmentExpenses_to_revenue,c_generalAndAdministrativeExpenses_to_revenue,c_sellingAndMarketingExpenses_to_revenue,c_sellingGeneralAndAdministrativeExpenses_to_revenue,c_depreciationAndAmortization_to_revenue,c_interestExpense_to_revenue,c_incomeTaxExpense_to_revenue,c_stockBasedCompensation_to_revenue,c_otherExpenses_to_revenue,c_nonOperatingIncomeExcludingInterest_to_revenue,c_totalOtherIncomeExpensesNet_to_revenue,c_revenue_to_totalAssets,c_grossProfit_to_totalAssets,c_ebitda_to_totalAssets,c_ebit_to_totalAssets,c_operatingIncome_to_totalAssets,c_netIncome_to_totalAssets,c_operatingCashFlow_to_totalAssets,c_freeCashFlow_to_totalAssets,c_netIncome_to_totalEquity,c_operatingIncome_to_totalEquity,c_totalDebt_to_totalEquity,c_totalLiabilities_to_totalEquity,c_netDebt_to_totalEquity,c_netIncome_to_investedCapital,c_operatingIncome_to_investedCapital,c_ebit_to_investedCapital,c_netIncome_to_tangibleAssetValue,c_operatingIncome_to_tangibleAssetValue,c_totalDebt_to_totalAssets,c_totalLiabilities_to_totalAssets,c_netDebt_to_totalAssets,c_longTermDebt_to_totalAssets,c_shortTermDebt_to_totalAssets,c_longTermDebt_to_totalDebt,c_shortTermDebt_to_totalDebt,c_totalDebt_to_capital,c_longTermDebt_to_capital,c_cashAndCashEquivalents_to_totalDebt,c_cashAndShortTermInvestments_to_totalDebt,c_cashAndCashEquivalents_to_totalAssets,c_cashAndShortTermInvestments_to_totalAssets,c_workingCapital_to_totalAssets,c_workingCapital_to_revenue,c_investedCapital_to_totalAssets,c_totalCurrentAssets_to_totalCurrentLiabilities,c_cashAndCashEquivalents_to_totalCurrentLiabilities,c_cashAndShortTermInvestments_to_totalCurrentLiabilities,c_netReceivables_to_totalCurrentLiabilities,c_inventory_to_totalCurrentAssets,c_netReceivables_to_totalCurrentAssets,c_otherCurrentAssets_to_totalCurrentAssets,c_prepaids_to_totalCurrentAssets,c_totalCurrentAssets_to_totalAssets,c_totalNonCurrentAssets_to_totalAssets,c_propertyPlantEquipmentNet_to_totalAssets,c_inventory_to_totalAssets,c_netReceivables_to_totalAssets,c_goodwill_to_totalAssets,c_intangibleAssets_to_totalAssets,c_goodwillAndIntangibleAssets_to_totalAssets,c_longTermInvestments_to_totalAssets,c_totalInvestments_to_totalAssets,c_totalCurrentLiabilities_to_totalLiabilities,c_totalNonCurrentLiabilities_to_totalLiabilities,c_accountPayables_to_totalLiabilities,c_totalPayables_to_totalLiabilities,c_shortTermDebt_to_totalLiabilities,c_longTermDebt_to_totalLiabilities,c_revenue_to_averageReceivables,c_costOfRevenue_to_averagePayables,c_costOfRevenue_to_averageInventory,c_revenue_to_propertyPlantEquipmentNet,c_revenue_to_workingCapital,c_operatingCashFlow_to_revenue,c_freeCashFlow_to_revenue,c_operatingCashFlow_to_totalDebt,c_freeCashFlow_to_totalDebt,c_operatingCashFlow_to_totalCurrentLiabilities,c_operatingCashFlow_to_netIncome,c_freeCashFlow_to_netIncome,c_freeCashFlow_to_operatingCashFlow,c_ebit_to_interestExpense,c_operatingIncome_to_interestExpense,c_operatingCashFlow_to_interestExpense,c_capitalExpenditure_to_operatingCashFlow,c_investmentsInPropertyPlantAndEquipment_to_operatingCashFlow,c_netDividendsPaid_to_operatingCashFlow,c_commonDividendsPaid_to_operatingCashFlow,c_dividendsPaid_plus_capex_to_operatingCashFlow,c_incomeTaxExpense_to_incomeBeforeTax,c_netIncome_to_incomeBeforeTax,c_incomeBeforeTax_to_ebit,c_operatingCashFlow_to_netIncome_quality,c_marketCap_to_revenue,c_marketCap_to_operatingCashFlow,c_marketCap_to_freeCashFlow,c_marketCap_to_netIncome,c_revenue_to_marketCap,c_operatingCashFlow_to_marketCap,c_freeCashFlow_to_marketCap,c_netIncome_to_marketCap,c_totalEquity_to_marketCap,c_totalDebt_to_marketCap,c_netDebt_to_marketCap,c_enterpriseValue_to_revenue,c_enterpriseValue_to_operatingCashFlow,c_enterpriseValue_to_freeCashFlow,c_enterpriseValue_to_ebitda,c_enterpriseValue_to_ebit,c_stockPrice_to_eps,c_stockPrice_to_bookValuePerShare,c_stockPrice_to_revenuePerShare,c_stockPrice_to_operatingCashFlowPerShare,c_stockPrice_to_freeCashFlowPerShare,c_dividendPerShare_to_stockPrice,c_netDividendsPaid_to_netIncome,c_commonDividendsPaid_to_netIncome,c_netDividendsPaid_to_freeCashFlow,c_commonDividendsPaid_to_freeCashFlow,c_netDividendsPaid_to_marketCap,c_commonDividendsPaid_to_marketCap,c_revenue_to_weightedAverageShsOut,c_netIncome_to_weightedAverageShsOut,c_operatingCashFlow_to_weightedAverageShsOut,c_freeCashFlow_to_weightedAverageShsOut,c_totalEquity_to_weightedAverageShsOut,c_cashAndCashEquivalents_to_weightedAverageShsOut,symbol,date_fundamentals,acceptedDate,exchange,industry,sector,country,ipoDate,isEtf,isActivelyTrading,isAdr,isFund,iteracion,date_t0,rate_3m_t0,rate_2y_t0,rate_10y_t0,rate_30y_t0,industrial_production_t0,cfnai_t0,cpi_t0,core_cpi_t0,core_pce_t0,unemployment_t0,vix_t0,nfci_t0,baa_10y_t0,fed_funds_t0,house_price_index_t0,consumer_sentiment_t0,spread_10y_2y_t0,spread_10y_3m_t0,retail_sales_mom_t0,pce_mom_t0,payrolls_mom_t0,jobless_claims_mom_t0,m2_mom_t0,housing_starts_mom_t0,date_pred_t1,rate_3m_pred_t1,rate_2y_pred_t1,rate_10y_pred_t1,rate_30y_pred_t1,industrial_production_pred_t1,cfnai_pred_t1,cpi_pred_t1,core_cpi_pred_t1,core_pce_pred_t1,unemployment_pred_t1,vix_pred_t1,nfci_pred_t1,baa_10y_pred_t1,fed_funds_pred_t1,house_price_index_pred_t1,consumer_sentiment_pred_t1,spread_10y_2y_pred_t1,spread_10y_3m_pred_t1,retail_sales_mom_pred_t1,pce_mom_pred_t1,payrolls_mom_pred_t1,jobless_claims_mom_pred_t1,m2_mom_pred_t1,housing_starts_mom_pred_t1,date_pred_t2,rate_3m_pred_t2,rate_2y_pred_t2,rate_10y_pred_t2,rate_30y_pred_t2,industrial_production_pred_t2,cfnai_pred_t2,cpi_pred_t2,core_cpi_pred_t2,core_pce_pred_t2,unemployment_pred_t2,vix_pred_t2,nfci_pred_t2,baa_10y_pred_t2,fed_funds_pred_t2,house_price_index_pred_t2,consumer_sentiment_pred_t2,spread_10y_2y_pred_t2,spread_10y_3m_pred_t2,retail_sales_mom_pred_t2,pce_mom_pred_t2,payrolls_mom_pred_t2,jobless_claims_mom_pred_t2,m2_mom_pred_t2,housing_starts_mom_pred_t2,date_pred_t3,rate_3m_pred_t3,rate_2y_pred_t3,rate_10y_pred_t3,rate_30y_pred_t3,industrial_production_pred_t3,cfnai_pred_t3,cpi_pred_t3,core_cpi_pred_t3,core_pce_pred_t3,unemployment_pred_t3,vix_pred_t3,nfci_pred_t3,baa_10y_pred_t3,fed_funds_pred_t3,house_price_index_pred_t3,consumer_sentiment_pred_t3,spread_10y_2y_pred_t3,spread_10y_3m_pred_t3,retail_sales_mom_pred_t3,pce_mom_pred_t3,payrolls_mom_pred_t3,jobless_claims_mom_pred_t3,m2_mom_pred_t3,housing_starts_mom_pred_t3,target_return
0,1.0,0.181367,0.209279,0.149772,0.175654,0.073011,0.073011,0.073011,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,172.780113,0.0,0.0,0.000000,50.459270,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.0000,26.214876,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.415652,1.172807,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.415652,0.968499,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.001447,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,1.0,0.209279,0.181367,0.149772,0.175654,0.073011,0.073011,0.073011,0.0,0.172052,1.000000,0.0,0.00,0.0,0.00,0.059507,0.005713,0.071048,NaN,0.172052,-0.031595,0.025882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.744982,26.214876,NaN,NaN,NaN,NaN,NaN,NaN,0.404478,0.415652,0.968499,NaN,50.459270,NaN,NaN,691.120450,0.019818,NaN,NaN,0.001447,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000,487.000000,NaN,50.467302,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.192996,0.014091,NaN,NaN,NaN,NaN,RTO,1985-06-30,1985-06-29,NYSE,Specialty Business Services,Industrials,GB,1996-11-18,False,True,True,False,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,0.061467,0.102045,0.102045,0.000000,0.035405,0.035405,0.035405,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,51.842201,0.0,0.0,0.000000,7.341808,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.0000,1.660163,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.004822,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,1.0,0.102045,0.061467,0.102045,0.000000,0.035405,0.035405,0.035405,0.0,-0.897955,0.270848,0.0,0.00,0.0,0.00,0.000000,0.061467,0.012858,NaN,-0.897955,0.048263,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.660163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,7.341808,NaN,NaN,207.368803,0.136206,NaN,NaN,0.004822,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000,207.560976,NaN,7.342471,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.636042,0.164137,NaN,NaN,NaN,NaN,AEH,1985-06-30,1985-06-30,NYSE,Insurance - Diversified,Financial Services,NL,2005-06-15,False,False,True,False,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,0.134935,0.159777,0.134935,0.112669,0.064736,0.071230,0.071230,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,29.497002,0.0,0.0,0.000000,8.404259,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.0000,6.060185,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.632205,0.834989,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.632205,0.834989,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.008475,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,1.0,0.159777,0.134935,0.134935,0.112669,0.071230,0.071230,0.064736,0.0,1.000000,1.000000,0.0,0.00,0.0,0.00,0.024843,0.022266,0.047933,NaN,1.000000,-0.134935,-0.022266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.060185,6.060185,NaN,NaN,NaN,NaN,NaN,NaN,0.425435,0.632205,0.834989,NaN,8.404259,NaN,NaN,117.988007,0.118987,NaN,NaN,0.008475,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000,114.625000,NaN,8.408293,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.090590,0.077682,NaN,NaN,NaN,NaN,PSO,1985-06-30,1985-06-30,NYSE,Publishing,Communication Services,GB,1996-11-18,False,True,True,False,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,0.061467,0.102045,0.102045,0.000000,0.035405,0.035405,0.035405,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,51.571864,0.0,0.0,0.000000,7.303524,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.0000,1.660163,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.004848,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,1.0,0.102045,0.061467,0.102045,0.000000,0.035405,0.035405,0.035405,0.0,-0.897955,0.270848,0.0,0.00,0.0,0.00,0.000000,0.061467,0.012858,NaN,-0.897955,0.048263,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.660163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,7.303524,NaN,NaN,206.287458,0.136920,NaN,NaN,0.004848,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000,206.463415,NaN,7.303644,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.636042,0.164137,NaN,NaN,NaN,NaN,AEB,1985-06-30,1985-06-30,NYSE,Insurance - Diversified,Financial Services,NL,2005-11-23,False,False,True,False,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.000000,1.065978,1.006483,0.181724,0.040043,0.098394,0.098394,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.292819,0.0,0.0,0.000000,0.902402,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.00,0.0,0.0000,27.067707,0.0,0.0,0.0,0.0,3.970968,0.432979,43.297872,0.541448,0.180554,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.541448,0.181724,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.109036,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,1.0,1.065978,1.000000,1.006483,0.181724,0.098394,0.098394,0.040043,0.0,6.140876,6.140876,0.0,0.00,0.0,0.00,0.065978,0.037184,0.075703,NaN,6.140876,-0.212425,-0.818276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.893348,27.067707,NaN,NaN,NaN,NaN,NaN,NaN,0.416579,0.541448,0.181724,NaN,0.902402,NaN,NaN,9.171276,1.108154,NaN,NaN,0.109036,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000,11.681818,NaN,0.903540,NaN,NaN,0.432434,NaN,NaN,NaN,NaN,NaN,NaN,2.844369,0.279870,NaN,NaN,NaN,NaN,UL,1985-06-30,1985-06-30,NYSE,Household & Personal Products,Consumer Defensive,GB,1980-03-25,False,True,True,False,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.689268
5,1.0,0.000000,-0.500000,2.250000,1.583333,1.166667,1.500000,1.500000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.946828,0.0,0.0,0.000000,23.680967,31.574622,31.574622,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.75,1.0,0.0000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.947368,0.703704,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.0,0.947368,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.063342,0.031671,0.0,0.0,0.0,-1.25,0.0,0.0,0.000000,0.0,0.0,1.0,-0.500000,0.000000,2.250000,1.583333,1.500000,1.500000,1.166667,0.0,-1.250000,-1.250000,0.0,-1.25,0.0,-1.25,-1.166667,0.000000,0.083333,NaN,0.000000,2.750000,-1.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.052632,0.947368,NaN,NaN,23.680967,NaN,NaN,15.787311,0.042228,NaN,NaN,0.063342,NaN,NaN,NaN,0.000000,NaN,NaN,-0.000000,NaN,14.540541,NaN,23.680967,31.574622,31.574622,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.227187,0.340780,NaN,NaN,NaN,NaN,DXR,1985-06-30,1985-06-30,NASDAQ,Medical - Instruments & Supplies,Healthcare,US,1983-07-25,False,True,False,False,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.069767

In [49]:
# Suponiendo que tu columna se llama 'fecha'
df_final['date_fundamentals'] = pd.to_datetime(df_final['date_fundamentals']) # Asegurar que sea datetime

# Agrupar por año y contar el tamaño de cada grupo
conteo_por_anio = df_final.groupby(df_final['date_fundamentals'].dt.year).size()

print(conteo_por_anio)

date_fundamentals
1985     1594
1986     3674
1987     3913
1988     4135
1989     4446
1990     4792
1991     5095
1992     5510
1993     5976
1994     6524
1995     7047
1996     7683
1997     8251
1998     8805
1999    11141
2000    11992
2001    12427
2002    12950
2003    13735
2004    14595
2005    15635
2006    16357
2007    16697
2008    16969
2009    17524
2010    18285
2011    18982
2012    20916
2013    23468
2014    24490
2015    25302
2016    26110
2017    26844
2018    27603
2019    29256
2020    32859
2021    39778
2022    40486
2023    36663
2024    33585
2025    26034
2026       15
dtype: int64

In [50]:
revisar_nulos(df_final)

,column,dtype,NaN,None,Null_string,Empty_string,Zero
0,grossProfitMargin,float64,0,0,0,0,67286
1,ebitMargin,float64,0,0,0,0,101518
2,ebitdaMargin,float64,0,0,0,0,75005
3,operatingProfitMargin,float64,0,0,0,0,64412
4,pretaxProfitMargin,float64,0,0,0,0,94396
5,continuousOperationsProfitMargin,float64,0,0,0,0,67169
6,netProfitMargin,float64,0,0,0,0,65128
7,bottomLineProfitMargin,float64,0,0,0,0,65580
8,receivablesTurnover,float64,0,0,0,0,167142
9,payablesTurnover,float64,0,0,0,0,243814
10,inventoryTurnover,float64,0,0,0,0,386834
11,fixedAssetTurnover,float64,0,0,0,0,150786
12,assetTurnover,float64,0,0,0,0,91101
13,currentRatio,float64,0,0,0,0,81760
14,quickRatio,float64,0,0,0,0,81789
15,solvencyRatio,float64,0,0,0,0,41326
16,cashRatio,float64,0,0,0,0,88213
17,priceToEarningsRatio,float64,0,0,0,0,19478
18,priceToEarningsGrowthRatio,float64,0,0,0,0,63768
19,forwardPriceToEarningsGrowthRatio,float64,0,0,0,0,63768
20,priceToBookRatio,float64,0,0,0,0,48787
21,priceToSalesRatio,float64,0,0,0,0,72802
22,priceToFreeCashFlowRatio,float64,0,0,0,0,64791
23,priceToOperatingCashFlowRatio,float64,0,0,0,0,64675
24,debtToAssetsRatio,float64,0,0,0,0,133177
25,debtToEquityRatio,float64,0,0,0,0,132908
26,debtToCapitalRatio,float64,0,0,0,0,132474
27,longTermDebtToCapitalRatio,float64,0,0,0,0,207505
28,financialLeverageRatio,float64,0,0,0,0,39280
29,workingCapitalTurnoverRatio,float64,0,0,0,0,111820
30,operatingCashFlowRatio,float64,0,0,0,0,105218
31,operatingCashFlowSalesRatio,float64,0,0,0,0,105759
32,freeCashFlowOperatingCashFlowRatio,float64,0,0,0,0,55299
33,debtServiceCoverageRatio,float64,0,0,0,0,157304
34,interestCoverageRatio,float64,0,0,0,0,251895
35,shortTermOperatingCashFlowCoverageRatio,float64,0,0,0,0,323120
36,operatingCashFlowCoverageRatio,float64,0,0,0,0,152277
37,capitalExpenditureCoverageRatio,float64,0,0,0,0,159890
38,dividendPaidAndCapexCoverageRatio,float64,0,0,0,0,112812
39,dividendPayoutRatio,float64,0,0,0,0,374619
40,dividendYield,float64,0,0,0,0,378527
41,dividendYieldPercentage,float64,0,0,0,0,378527
42,netIncomePerEBT,float64,0,0,0,0,41032
43,ebtPerEbit,float64,0,0,0,0,43090
44,priceToFairValue,float64,0,0,0,0,48787
45,debtToMarketCap,float64,0,0,0,0,162218
46,evToSales,float64,287,0,0,0,96973
47,evToOperatingCashFlow,float64,287,0,0,0,71889
48,evToFreeCashFlow,float64,287,0,0,0,72056
49,evToEBITDA,float64,287,0,0,0,60228
50,netDebtToEBITDA,float64,287,0,0,0,56656
51,incomeQuality,float64,287,0,0,0,58919
52,taxBurden,float64,287,0,0,0,41018
53,interestBurden,float64,287,0,0,0,82933
54,returnOnAssets,float64,287,0,0,0,41112
55,operatingReturnOnAssets,float64,287,0,0,0,61802
56,returnOnTangibleAssets,float64,287,0,0,0,41029
57,returnOnEquity,float64,287,0,0,0,38761
58,returnOnInvestedCapital,float64,287,0,0,0,62048
59,returnOnCapitalEmployed,float64,287,0,0,0,42182
60,earningsYield,float64,287,0,0,0,19450
61,freeCashFlowYield,float64,287,0,0,0,64779
62,capexToOperatingCashFlow,float64,287,0,0,0,159877
63,capexToDepreciation,float64,287,0,0,0,184898
64,capexToRevenue,float64,287,0,0,0,178025
65,salesGeneralAndAdministrativeToRevenue,float64,287,0,0,0,281775
66,researchAndDevelopementToRevenue,float64,287,0,0,0,532235
67,stockBasedCompensationToRevenue,float64,287,0,0,0,392233
68,intangiblesToTotalAssets,float64,287,0,0,0,285430
69,freeCashFlowToEquity,float64,287,0,0,0,53698
70,freeCashFlowToFirm,float64,287,0,0,0,82243
71,c_grossProfit_to_revenue,float64,60553,0,0,0,6768
72,c_ebitda_to_revenue,float64,60553,0,0,0,14583
73,c_ebit_to_revenue,float64,60555,0,0,0,41205
74,c_operatingIncome_to_revenue,float64,60553,0,0,0,3903
75,c_incomeBeforeTax_to_revenue,float64,60554,0,0,0,33848
76,c_netIncome_to_revenue,float64,60553,0,0,0,4563
77,c_bottomLineNetIncome_to_revenue,float64,60659,0,0,0,5052
78,c_netIncomeFromContinuingOperations_to_revenue,float64,61967,0,0,0,5351
79,c_costOfRevenue_to_revenue,float64,60553,0,0,0,94731
80,c_operatingExpenses_to_revenue,float64,60554,0,0,0,16430
81,c_costAndExpenses_to_revenue,float64,60553,0,0,0,15459
82,c_researchAndDevelopmentExpenses_to_revenue,float64,60563,0,0,0,471978
83,c_generalAndAdministrativeExpenses_to_revenue,float64,60562,0,0,0,221517
84,c_sellingAndMarketingExpenses_to_revenue,float64,60563,0,0,0,414351
85,c_sellingGeneralAndAdministrativeExpenses_to_r...,float64,60554,0,0,0,54714
86,c_depreciationAndAmortization_to_revenue,float64,60553,0,0,0,52796
87,c_interestExpense_to_revenue,float64,61001,0,0,0,206902
88,c_incomeTaxExpense_to_revenue,float64,60554,0,0,0,90209
89,c_stockBasedCompensation_to_revenue,float64,688137,0,0,0,5
90,c_otherExpenses_to_revenue,float64,60553,0,0,0,218728
91,c_nonOperatingIncomeExcludingInterest_to_revenue,float64,60557,0,0,0,342828
92,c_totalOtherIncomeExpensesNet_to_revenue,float64,60554,0,0,0,148742
93,c_revenue_to_totalAssets,float64,38610,0,0,0,52508
94,c_grossProfit_to_totalAssets,float64,38607,0,0,0,44813
95,c_ebitda_to_totalAssets,float64,38607,0,0,0,16804
96,c_ebit_to_totalAssets,float64,38610,0,0,0,44578
97,c_operatingIncome_to_totalAssets,float64,38607,0,0,0,4538
98,c_netIncome_to_totalAssets,float64,38607,0,0,0,2519
99,c_operatingCashFlow_to_totalAssets,float64,688134,0,0,0,0
100,c_freeCashFlow_to_totalAssets,float64,688134,0,0,0,0
101,c_netIncome_to_totalEquity,float64,43182,0,0,0,2428
102,c_operatingIncome_to_totalEquity,float64,43182,0,0,0,4446
103,c_totalDebt_to_totalEquity,float64,43182,0,0,0,95135
104,c_totalLiabilities_to_totalEquity,float64,43182,0,0,0,2887
105,c_netDebt_to_totalEquity,float64,43182,0,0,0,4846
106,c_netIncome_to_investedCapital,float64,38506,0,0,0,2526
107,c_operatingIncome_to_investedCapital,float64,38506,0,0,0,4326
108,c_ebit_to_investedCapital,float64,38509,0,0,0,44454
109,c_netIncome_to_tangibleAssetValue,float64,37882,0,0,0,2533
110,c_operatingIncome_to_tangibleAssetValue,float64,37882,0,0,0,4555
111,c_totalDebt_to_totalAssets,float64,38607,0,0,0,94627
112,c_totalLiabilities_to_totalAssets,float64,38607,0,0,0,1431
113,c_netDebt_to_totalAssets,float64,38607,0,0,0,4567
114,c_longTermDebt_to_totalAssets,float64,38607,0,0,0,169375
115,c_shortTermDebt_to_totalAssets,float64,38608,0,0,0,270332
116,c_longTermDebt_to_totalDebt,float64,132495,0,0,0,81380
117,c_shortTermDebt_to_totalDebt,float64,132496,0,0,0,177101
118,c_totalDebt_to_capital,float64,38527,0,0,0,96041
119,c_longTermDebt_to_capital,float64,38527,0,0,0,171115
120,c_cashAndCashEquivalents_to_totalDebt,float64,132495,0,0,0,11225
121,c_cashAndShortTermInvestments_to_totalDebt,float64,132495,0,0,0,9504
122,c_cashAndCashEquivalents_to_totalAssets,float64,38607,0,0,0,14838
123,c_cashAndShortTermInvestments_to_totalAssets,float64,38607,0,0,0,12916
124,c_workingCapital_to_totalAssets,float64,38884,0,0,0,8078
125,c_workingCapital_to_revenue,float64,60834,0,0,0,36504
126,c_investedCapital_to_totalAssets,float64,38884,0,0,0,2496
127,c_totalCurrentAssets_to_totalCurrentLiabilities,float64,77195,0,0,0,4589
128,c_cashAndCashEquivalents_to_totalCurrentLiabil...,float64,77195,0,0,0,11109
129,c_cashAndShortTermInvestments_to_totalCurrentL...,float64,77195,0,0,0,9573
130,c_netReceivables_to_totalCurrentLiabilities,float64,77195,0,0,0,106491
131,c_inventory_to_totalCurrentAssets,float64,48172,0,0,0,325140
132,c_netReceivables_to_totalCurrentAssets,float64,48172,0,0,0,113284
133,c_otherCurrentAssets_to_totalCurrentAssets,float64,48172,0,0,0,235223
134,c_prepaids_to_totalCurrentAssets,float64,48173,0,0,0,394126
135,c_totalCurrentAssets_to_totalAssets,float64,38607,0,0,0,11663
136,c_totalNonCurrentAssets_to_totalAssets,float64,38607,0,0,0,17349
137,c_propertyPlantEquipmentNet_to_totalAssets,float64,38607,0,0,0,89660
138,c_inventory_to_totalAssets,float64,38607,0,0,0,334720
139,c_netReceivables_to_totalAssets,float64,38607,0,0,0,116341
140,c_goodwill_to_totalAssets,float64,38608,0,0,0,393083
141,c_intangibleAssets_to_totalAssets,float64,38608,0,0,0,296337
142,c_goodwillAndIntangibleAssets_to_totalAssets,float64,38608,0,0,0,246985
143,c_longTermInvestments_to_totalAssets,float64,38608,0,0,0,312706
144,c_totalInvestments_to_totalAssets,float64,38607,0,0,0,244778
145,c_totalCurrentLiabilities_to_totalLiabilities,float64,38715,0,0,0,38555
146,c_totalNonCurrentLiabilities_to_totalLiabilities,float64,38715,0,0,0,53593
147,c_accountPayables_to_totalLiabilities,float64,38715,0,0,0,137213
148,c_totalPayables_to_totalLiabilities,float64,38715,0,0,0,113924
149,c_shortTermDebt_to_totalLiabilities,float64,38716,0,0,0,269661
150,c_longTermDebt_to_totalLiabilities,float64,38715,0,0,0,168928
151,c_revenue_to_averageReceivables,float64,155893,0,0,0,13750
152,c_costOfRevenue_to_averagePayables,float64,175176,0,0,0,67912
153,c_costOfRevenue_to_averageInventory,float64,371075,0,0,0,11984
154,c_revenue_to_propertyPlantEquipmentNet,float64,128089,0,0,0,22726
155,c_revenue_to_workingCapital,float64,44092,0,0,0,53246
156,c_operatingCashFlow_to_revenue,float64,688137,0,0,0,0
157,c_freeCashFlow_to_revenue,float64,688137,0,0,0,0
158,c_operatingCashFlow_to_totalDebt,float64,688135,0,0,0,0
159,c_freeCashFlow_to_totalDebt,float64,688135,0,0,0,0
160,c_operatingCashFlow_to_totalCurrentLiabilities,float64,688137,0,0,0,0
161,c_operatingCashFlow_to_netIncome,float64,688135,0,0,0,0
162,c_freeCashFlow_to_netIncome,float64,688135,0,0,0,0
163,c_freeCashFlow_to_operatingCashFlow,float64,688134,0,0,0,0
164,c_ebit_to_interestExpense,float64,249194,0,0,0,12378
165,c_operatingIncome_to_interestExpense,float64,249194,0,0,0,2723
166,c_operatingCashFlow_to_interestExpense,float64,688139,0,0,0,0
167,c_capitalExpenditure_to_operatingCashFlow,float64,688134,0,0,0,7
168,c_investmentsInPropertyPlantAndEquipment_to_op...,float64,688134,0,0,0,8
169,c_netDividendsPaid_to_operatingCashFlow,float64,688134,0,0,0,6
170,c_commonDividendsPaid_to_operatingCashFlow,float64,688134,0,0,0,6
171,c_dividendsPaid_plus_capex_to_operatingCashFlow,float64,688134,0,0,0,5
172,c_incomeTaxExpense_to_incomeBeforeTax,float64,40343,0,0,0,105334
173,c_netIncome_to_incomeBeforeTax,float64,40339,0,0,0,680
174,c_incomeBeforeTax_to_ebit,float64,53326,0,0,0,29857
175,c_operatingCashFlow_to_netIncome_quality,float64,688135,0,0,0,0
176,c_marketCap_to_revenue,float64,60834,0,0,0,12266
177,c_marketCap_to_operatingCashFlow,float64,688134,0,0,0,0
178,c_marketCap_to_freeCashFlow,float64,688134,0,0,0,0
179,c_marketCap_to_netIncome,float64,6723,0,0,0,13020
180,c_revenue_to_marketCap,float64,13452,0,0,0,59648
181,c_operatingCashFlow_to_marketCap,float64,688134,0,0,0,0
182,c_freeCashFlow_to_marketCap,float64,688134,0,0,0,0
183,c_netIncome_to_marketCap,float64,13449,0,0,0,6294
184,c_totalEquity_to_marketCap,float64,48224,0,0,0,7626
185,c_totalDebt_to_marketCap,float64,48223,0,0,0,90300
186,c_netDebt_to_marketCap,float64,48223,0,0,0,4557
187,c_enterpriseValue_to_revenue,float64,60834,0,0,0,36433
188,c_enterpriseValue_to_operatingCashFlow,float64,688134,0,0,0,0
189,c_enterpriseValue_to_freeCashFlow,float64,688134,0,0,0,0
190,c_enterpriseValue_to_ebitda,float64,21394,0,0,0,39230
191,c_enterpriseValue_to_ebit,float64,53595,0,0,0,29817
192,c_stockPrice_to_eps,float64,8015,0,0,0,11
193,c_stockPrice_to_bookValuePerShare,float64,50491,0,0,0,10
194,c_stockPrice_to_revenuePerShare,float64,72792,0,0,0,10
195,c_stockPrice_to_operatingCashFlowPerShare,float64,64666,0,0,0,9
196,c_stockPrice_to_freeCashFlowPerShare,float64,64782,0,0,0,9
197,c_dividendPerShare_to_stockPrice,float64,24,0,0,0,378503
198,c_netDividendsPaid_to_netIncome,float64,688135,0,0,0,6
199,c_commonDividendsPaid_to_netIncome,float64,688135,0,0,0,6
200,c_netDividendsPaid_to_freeCashFlow,float64,688134,0,0,0,6
201,c_commonDividendsPaid_to_freeCashFlow,float64,688134,0,0,0,6
202,c_netDividendsPaid_to_marketCap,float64,688134,0,0,0,6
203,c_commonDividendsPaid_to_marketCap,float64,688134,0,0,0,6
204,c_revenue_to_weightedAverageShsOut,float64,13163,0,0,0,59646
205,c_netIncome_to_weightedAverageShsOut,float64,13160,0,0,0,6293
206,c_operatingCashFlow_to_weightedAverageShsOut,float64,688134,0,0,0,0
207,c_freeCashFlow_to_weightedAverageShsOut,float64,688134,0,0,0,0
208,c_totalEquity_to_weightedAverageShsOut,float64,47936,0,0,0,7623
209,c_cashAndCashEquivalents_to_weightedAverageShsOut,float64,47936,0,0,0,15127
210,symbol,object,0,0,0,0,0
211,date_fundamentals,datetime64[ns],0,0,0,0,0
212,acceptedDate,datetime64[ns],0,0,0,0,0
213,exchange,object,51824,0,0,0,0
214,industry,object,51824,0,0,0,0
215,sector,object,51824,0,0,0,0
216,country,object,51824,0,0,0,0
217,ipoDate,object,51824,0,0,4739,0
218,isEtf,object,51824,0,0,0,636109
219,isActivelyTrading,object,51824,0,0,0,138431
220,isAdr,object,51824,0,0,0,606024
221,isFund,object,51824,0,0,0,609919
222,iteracion,float64,75160,0,0,0,0
223,date_t0,datetime64[ns],75160,0,0,0,0
224,rate_3m_t0,float64,75160,0,0,0,1120
225,rate_2y_t0,float64,75160,0,0,0,0
226,rate_10y_t0,float64,75160,0,0,0,0
227,rate_30y_t0,float64,75160,0,0,0,0
228,industrial_production_t0,float64,75160,0,0,0,0
229,cfnai_t0,float64,75160,0,0,0,10616
230,cpi_t0,float64,75160,0,0,0,0
231,core_cpi_t0,float64,75160,0,0,0,0
232,core_pce_t0,float64,75160,0,0,0,0
233,unemployment_t0,float64,75160,0,0,0,0
234,vix_t0,float64,75160,0,0,0,0
235,nfci_t0,float64,75160,0,0,0,2501
236,baa_10y_t0,float64,75160,0,0,0,0
237,fed_funds_t0,float64,75160,0,0,0,0
238,house_price_index_t0,float64,75160,0,0,0,0
239,consumer_sentiment_t0,float64,75160,0,0,0,0
240,spread_10y_2y_t0,float64,75160,0,0,0,3178
241,spread_10y_3m_t0,float64,75160,0,0,0,942
242,retail_sales_mom_t0,float64,75160,0,0,0,0
243,pce_mom_t0,float64,75160,0,0,0,0
244,payrolls_mom_t0,float64,75160,0,0,0,2503
245,jobless_claims_mom_t0,float64,75160,0,0,0,18162
246,m2_mom_t0,float64,75160,0,0,0,0
247,housing_starts_mom_t0,float64,75160,0,0,0,4058
248,date_pred_t1,datetime64[ns],75160,0,0,0,0
249,rate_3m_pred_t1,float32,75160,0,0,0,0
250,rate_2y_pred_t1,float32,75160,0,0,0,0
251,rate_10y_pred_t1,float32,75160,0,0,0,0
252,rate_30y_pred_t1,float32,75160,0,0,0,0
253,industrial_production_pred_t1,float32,75160,0,0,0,0
254,cfnai_pred_t1,float32,75160,0,0,0,0
255,cpi_pred_t1,float32,75160,0,0,0,0
256,core_cpi_pred_t1,float32,75160,0,0,0,0
257,core_pce_pred_t1,float32,75160,0,0,0,0
258,unemployment_pred_t1,float32,75160,0,0,0,0
259,vix_pred_t1,float32,75160,0,0,0,0
260,nfci_pred_t1,float32,75160,0,0,0,0
261,baa_10y_pred_t1,float32,75160,0,0,0,0
262,fed_funds_pred_t1,float32,75160,0,0,0,0
263,house_price_index_pred_t1,float32,75160,0,0,0,0
264,consumer_sentiment_pred_t1,float32,75160,0,0,0,0
265,spread_10y_2y_pred_t1,float32,75160,0,0,0,0
266,spread_10y_3m_pred_t1,float32,75160,0,0,0,0
267,retail_sales_mom_pred_t1,float32,75160,0,0,0,0
268,pce_mom_pred_t1,float32,75160,0,0,0,0
269,payrolls_mom_pred_t1,float32,75160,0,0,0,0
270,jobless_claims_mom_pred_t1,float32,75160,0,0,0,0
271,m2_mom_pred_t1,float32,75160,0,0,0,0
272,housing_starts_mom_pred_t1,float32,75160,0,0,0,0
273,date_pred_t2,datetime64[ns],75160,0,0,0,0
274,rate_3m_pred_t2,float32,75160,0,0,0,0
275,rate_2y_pred_t2,float32,75160,0,0,0,0
276,rate_10y_pred_t2,float32,75160,0,0,0,0
277,rate_30y_pred_t2,float32,75160,0,0,0,0
278,industrial_production_pred_t2,float32,75160,0,0,0,0
279,cfnai_pred_t2,float32,75160,0,0,0,0
280,cpi_pred_t2,float32,75160,0,0,0,0
281,core_cpi_pred_t2,float32,75160,0,0,0,0
282,core_pce_pred_t2,float32,75160,0,0,0,0
283,unemployment_pred_t2,float32,75160,0,0,0,0
284,vix_pred_t2,float32,75160,0,0,0,0
285,nfci_pred_t2,float32,75160,0,0,0,0
286,baa_10y_pred_t2,float32,75160,0,0,0,0
287,fed_funds_pred_t2,float32,75160,0,0,0,0
288,house_price_index_pred_t2,float32,75160,0,0,0,0
289,consumer_sentiment_pred_t2,float32,75160,0,0,0,0
290,spread_10y_2y_pred_t2,float32,75160,0,0,0,0
291,spread_10y_3m_pred_t2,float32,75160,0,0,0,0
292,retail_sales_mom_pred_t2,float32,75160,0,0,0,0
293,pce_mom_pred_t2,float32,75160,0,0,0,0
294,payrolls_mom_pred_t2,float32,75160,0,0,0,0
295,jobless_claims_mom_pred_t2,float32,75160,0,0,0,0
296,m2_mom_pred_t2,float32,75160,0,0,0,0
297,housing_starts_mom_pred_t2,float32,75160,0,0,0,0
298,date_pred_t3,datetime64[ns],75160,0,0,0,0
299,rate_3m_pred_t3,float32,75160,0,0,0,0
300,rate_2y_pred_t3,float32,75160,0,0,0,0
301,rate_10y_pred_t3,float32,75160,0,0,0,0
302,rate_30y_pred_t3,float32,75160,0,0,0,0
303,industrial_production_pred_t3,float32,75160,0,0,0,0
304,cfnai_pred_t3,float32,75160,0,0,0,0
305,cpi_pred_t3,float32,75160,0,0,0,0
306,core_cpi_pred_t3,float32,75160,0,0,0,0
307,core_pce_pred_t3,float32,75160,0,0,0,0
308,unemployment_pred_t3,float32,75160,0,0,0,0
309,vix_pred_t3,float32,75160,0,0,0,0
310,nfci_pred_t3,float32,75160,0,0,0,0
311,baa_10y_pred_t3,float32,75160,0,0,0,0
312,fed_funds_pred_t3,float32,75160,0,0,0,0
313,house_price_index_pred_t3,float32,75160,0,0,0,0
314,consumer_sentiment_pred_t3,float32,75160,0,0,0,0
315,spread_10y_2y_pred_t3,float32,75160,0,0,0,0
316,spread_10y_3m_pred_t3,float32,75160,0,0,0,0
317,retail_sales_mom_pred_t3,float32,75160,0,0,0,0
318,pce_mom_pred_t3,float32,75160,0,0,0,0
319,payrolls_mom_pred_t3,float32,75160,0,0,0,0
320,jobless_claims_mom_pred_t3,float32,75160,0,0,0,0
321,m2_mom_pred_t3,float32,75160,0,0,0,0
322,housing_starts_mom_pred_t3,float32,75160,0,0,0,0
323,target_return,float64,170232,0,0,0,5073

In [51]:
df_final.to_parquet("archivos/df_input_incial.parquet", index=False)